#!/usr/bin/env python3
# ADAPTARI IG SCRAPED (operator 2026-07-02): 20 surse din vaultul lui Catalin, retraduse in
# context ULTRON. Fiecare deck: hooks virale, panouri clay cu utilitate distincta, CTA pe una
# din cele 3 pastile fixe (OPERATOR/FOUNDER/BUILDER, §30), marci de cover contextuale.
# Acest modul tine DOAR datele; build files + panourile se genereaza din el.

# (slug, TITLE, accent, mark, pill, cover(w,a), slides[8](eyebrow,hw,ha,sub,foot,stem), close(l1,l2,q))
# stem = cheia panoului din adapt_panels.SPECS[slug]

BATCH1=[
 dict(slug="aios", title="THE AI OPERATING SYSTEM", accent=(204,120,92), mark="claude", pill="operator",
  cover=("I quit 9 tools in one night.","They kept forgetting me."),
  close=("Save this to","own your OS.","Rented tools or your own command center?"),
  slides=[
   ("THE BOTTLENECK",("My AI asked who I was.","For the 40th time."),"Every chat starts from zero. That is the real bottleneck, not the model.",("The tab is not a system.",),"amnesia"),
   ("THE BRAIN",("It knows my no-list","better than my cofounder."),"Your ICP, voice, pricing and pipeline live in one memory, loaded in every run.",("Set once. Never re-briefed.",),"brain"),
   ("THE DASHBOARD",("Nine tabs died.","One screen survived."),"Every agent, flow and approval in one place, built on your own data.",("No tab zoo.",),"command"),
   ("THE HOURS",("3am. It closed a task.","I found out at 7."),"Flows fire on triggers around the clock, even with the laptop shut.",("Overnight is work time now.",),"always"),
   ("THE MEMORY",("I say things once.","That is the whole trick."),"Say no discounts once and the gate blocks them forever.",("It compounds monthly.",),"rules"),
   ("THE PROOF",("1,284 companies read.","My coffee was still hot."),"The OS briefed 200 accounts before the first coffee. One typed sentence.",("While you slept.",),"proof"),
   ("THE GATE",("It can do anything.","It may do nothing alone."),"Nothing external fires alone. You read, you tap, it moves.",("Power, gated.",),"gate"),
   ("THE OPERATOR",("Renters restart daily.","Owners compound."),"One subscription, one memory, one command center behind a chat.",("Build yours today.",),"own"),
  ]),
 dict(slug="loops", title="PROMPTS ARE DEAD, LOOPS RUN", accent=(200,70,35), mark="claude", pill="builder",
  cover=("Stop writing prompts.","Start setting exits."),
  close=("Save this before","your next prompt.","Which task would you loop first?"),
  slides=[
   ("THE OLD WAY",("You are a human cron job.","Admit it."),"If you type prompt after prompt, you work backwards, one output at a time.",("You are the cron job.",),"oldway"),
   ("THE LOOP",("212 cycles ran.","I typed 3 sentences."),"An Ultron flow has a goal, a checker and an exit. It cycles until done.",("24/7, no typing.",),"loop"),
   ("STEP 1",("One sentence replaced","my follow-up job."),"Follow up every lead that goes quiet for 3 days. One sentence, one flow.",("That is the whole setup.",),"define"),
   ("STEP 2",("9:00 fires without me.","Every single day."),"Daily 09:00, on every reply, on usage drop. Triggers replace your memory.",("No reminders app.",),"trigger"),
   ("STEP 3",("It grades its own work.","Before I ever see it."),"Every cycle checks the result before it reports. Failures retry, not repeat.",("The checker is built in.",),"verify"),
   ("THE TRAP",("Loops without exits","eat budgets alive."),"A loop without an exit spends while you sleep. Ultron caps every flow.",("Guardrails by default.",),"trap"),
   ("THE GATE",("Full speed inside.","Handbrake on the door."),"Anything external still parks on HOLD for your tap. Speed with brakes.",("You stay the exit.",),"gate"),
   ("THE SCALE",("My hours stopped scaling.","My systems did not."),"Nine flows ran 212 cycles last week. You typed three sentences.",("Scale past your hours.",),"scale"),
  ]),
 dict(slug="aibody", title="THE COMPLETE AI BODY", accent=(212,162,127), mark="orb", pill="founder",
  cover=("You bought a mouth.","You needed a body."),
  close=("Save this and","augment every part.","Which part of you needs the upgrade first?"),
  slides=[
   ("THE DIFFERENCE",("Talking is not working.","Ask your chatbot."),"Most founders rent one mouth. The top operators wire every organ.",("Augment, not chat.",),"difference"),
   ("THE BRAIN",("A brain that budgets","its own thinking."),"It reads each job, hires the right agent, picks the model tier per turn.",("You never pick a model.",),"router"),
   ("THE EYES",("It saw the funding round","before my VC did."),"Funding, hiring, stack, intent. Signals you would never spot by hand.",("Overnight, every night.",),"eyes"),
   ("THE VOICE",("It stole my writing style.","I approved."),"Sampled from your real posts. Banned words enforced on every draft.",("Your voice, multiplied.",),"voice"),
   ("THE HANDS",("Built, tested, shipped.","I was at dinner."),"Pages, dashboards and fixes from plain English, tested before you see them.",("Built while you sleep.",),"hands"),
   ("THE HEART",("Cut the memory","and the body dies."),"ICP, pipeline, pricing, docs. Every agent draws from the same core.",("Nothing forgets you.",),"heart"),
   ("THE GATE",("Strong body.","My reins."),"Every external move parks for your tap. Augmented, not replaced.",("Still your company.",),"gate"),
   ("THE OPERATOR",("Stop chatting with organs.","Assemble the body."),"One chat wires brain, eyes, voice, hands and heart into one operator.",("The full body, one login.",),"operator"),
  ]),
 dict(slug="fivesigns", title="5 SIGNS YOU NEED AI NOW", accent=(204,120,92), mark="orb", pill="founder",
  cover=("Answer 5 questions.","Count your leaks."),
  close=("Save this checklist","and score yourself.","How many of the 5 did you tick?"),
  slides=[
   ("SIGN 1",("Q1: same answer,","typed 40 times a week?"),"If support answers repeat daily, a flow should answer them in seconds.",("Ultron replies 24/7.",),"sign1"),
   ("SIGN 2",("Q2: is payroll","moving data by hand?"),"Hours spent moving data between apps is payroll spent on glue work.",("Flows move it instantly.",),"sign2"),
   ("SIGN 3",("Q3: does work queue","behind your thumbs?"),"You are the bottleneck. Ultron preps everything, you just tap.",("Approval, not assembly.",),"sign3"),
   ("SIGN 4",("Q4: do leads cool off","in your inbox?"),"Speed to lead decides the meeting. The flow answers in seconds, gated.",("First reply wins.",),"sign4"),
   ("SIGN 5",("Q5: does month-end","steal three days?"),"The numbers already exist. Ultron assembles them on demand, with sources.",("Reports in minutes.",),"sign5"),
   ("THE TEST",("Three yes or more?","You are the system."),"Five yes answers is not a staffing problem. It is missing systems.",("Friction, not headcount.",),"test"),
   ("THE FIX",("Plug the worst leak","this week. One sentence."),"Automate the worst leak first. Ultron sets it up from one sentence.",("Start small, compound.",),"fix"),
   ("THE GATE",("Automate the work.","Keep the veto."),"Every flow that touches a customer parks for your tap first.",("You stay in control.",),"gate"),
  ]),
 dict(slug="contentdesk", title="THE 500K CONTENT DESK", accent=(200,70,35), mark="claude", pill="operator",
  cover=("Five salaries quit my desk.","Output went up."),
  close=("Save the desk","and steal the setup.","Which of the five would you run first?"),
  slides=[
   ("SKILL 1",("Monday, 07:00.","The week plans itself."),"One line in, 14 slots out, spread across channels at 10:00 local.",("Zero coordinators.",),"cal"),
   ("SKILL 2",("Three hooks fight.","I crown one."),"Three angles per post from your proven hook bank. You pick the winner.",("A/B/C, one tap.",),"hooks"),
   ("SKILL 3",("It writes like me","on my best day."),"Sampled from your real posts, banned words enforced, ranked before you read.",("No AI-speak.",),"voice"),
   ("SKILL 4",("One brief.","Five channels, native."),"LinkedIn long-form, caption, carousel, newsletter, script. Same brief.",("Native per channel.",),"repurpose"),
   ("SKILL 5",("99.2% inboxed.","Unseen content is rent."),"Warm domains, ramped sends, 99.2% placement. Content nobody reads is free.",("Delivery is the job.",),"inbox"),
   ("THE DESK",("No standups.","The desk never meets."),"The whole pipeline runs behind one chat with one memory of your brand.",("PULSE owns it.",),"desk"),
   ("THE GATE",("My feed, my thumb.","Nothing posts alone."),"Every draft parks first. You approve the batch in one read.",("Your feed, your call.",),"gate"),
   ("THE MATH",("The desk bills in cents.","Not in Mondays."),"Planner, writer, designer, distributor: one subscription, metered by use.",("Payroll: zero.",),"math"),
  ]),
]

BATCH2=[
 dict(slug="unstuck", title="STUCK AT LEVEL ONE", accent=(204,120,92), mark="claude", pill="builder",
  cover=("You are at level 1.","The map goes to 5."),
  close=("Save the map","and climb one level.","Which level are you honestly at?"),
  slides=[
   ("LEVEL 1",("Ask. Copy. Close.","The hamster wheel."),"Ask, copy, close the tab. A smarter search bar, nothing more.",("The floor, not the ceiling.",),"floor"),
   ("LEVEL 2",("Level 2: it remembers","what you hate."),"Your ICP, voice and pricing persist. No more introductions every morning.",("It remembers you now.",),"memory"),
   ("LEVEL 3",("Level 3: it works","while you watch."),"Agents source, brief and draft while you do the one thing only you can do.",("Work, not answers.",),"jobs"),
   ("LEVEL 4",("Level 4: it ships","while you sell."),"Pages and fixes from plain English, tested before you ever see them.",("Your eng team in a chat.",),"ship"),
   ("LEVEL 5",("Level 5: it runs","while you sleep."),"Triggers replace typing. The digest waits for you at 07:00.",("The machine works nights.",),"routines"),
   ("THE GAP",("Nobody told you","level 3 exists."),"Most founders never hear that the next level exists. Now you have.",("Five levels, one chat.",),"gap"),
   ("THE GATE",("Climb fast.","Keep the handbrake."),"Autonomy grows, control does not shrink. External moves park for you.",("Climb without crashing.",),"gate"),
   ("THE CEILING",("The ceiling is quiet.","Just running."),"One founder, one subscription, a company that moves overnight.",("See you up there.",),"ceiling"),
  ]),
 dict(slug="hidden", title="THE HIDDEN SKILLS", accent=(212,162,127), mark="claude", pill="operator",
  cover=("Prompting is level zero.","Installing is the game."),
  close=("Save the list","before you prompt again.","Which skill would save you the most hours?"),
  slides=[
   ("THE MYTH",("Re-wording requests","is not a skill."),"The top operators install capabilities. The rest re-word requests.",("Skills beat phrasing.",),"myth"),
   ("DECKS",("The proposal built itself.","I added the price."),"Client name in, structured deck out, in your tokens and your voice.",("No blank slides.",),"decks"),
   ("SHEETS",("Numbers with receipts.","Every figure traces."),"Live figures with sources attached, not screenshots of spreadsheets.",("Ask, do not assemble.",),"sheets"),
   ("CONTRACTS",("The NDA came back","already redlined."),"COUNSEL reads the NDA, flags the risk lines, drafts the redlines.",("Minutes, not lawyers-first.",),"contracts"),
   ("VISUALS",("822 parts,","zero design queue."),"822 Crescendo components assemble into on-brand visuals and sites.",("No design queue.",),"visuals"),
   ("CONNECTORS",("It acts inside my tools.","Not beside them."),"Mail, CRM, calendar, payments. It acts in your tools, not beside them.",("No copy-paste bridge.",),"connectors"),
   ("THE RESULT",("Answers are cheap.","Execution is the product."),"Files created, work automated, tasks finished. That is the difference.",("Executor, not assistant.",),"result"),
   ("THE GATE",("Executes at AI speed.","Sends at my speed."),"Everything external parks first. You stay the only trigger.",("Power needs brakes.",),"gate"),
  ]),
 dict(slug="carouselcmd", title="THE CAROUSEL COMMAND", accent=(200,70,35), mark="claude", pill="operator",
  cover=("My designer invoice","died mid-month."),
  close=("Save this before","your next invoice.","What would you build with the saved retainer?"),
  slides=[
   ("THE OLD BILL",("A week per deck.","Plus revision rounds."),"Briefs, revisions, queue time. A week per deck, every deck.",("That bill ends today.",),"oldbill"),
   ("THE COMMAND",("It interviews me.","Then builds alone."),"PULSE interviews you for the angle, then owns the build end to end.",("It asks, you answer.",),"command"),
   ("THE VISUALS",("My tokens, my type.","No template smell."),"Brand colors, brand type, brand components. No template smell.",("Yours, not a template.",),"visuals"),
   ("THE SLIDES",("Ten pages assembled","on proven bones."),"Hook, body, CTA: structured like the decks that already performed.",("Built on receipts.",),"slides"),
   ("THE CAPTIONS",("The caption kit","writes itself in."),"CTA-first caption, hashtags, first comment. The whole posting kit.",("Nothing left to write.",),"captions"),
   ("THE CLOCK",("Coffee brewed.","Deck done."),"Cover, slides, captions, sized per channel. While the coffee brews.",("A week becomes minutes.",),"clock"),
   ("THE GATE",("One review. One tap.","Then it posts."),"You review the batch once. Nothing posts alone.",("Your feed, your call.",),"gate"),
   ("THE MATH",("Retainer money","became runway."),"Metered by use, not by seats. The retainer becomes runway.",("Cancel, then compound.",),"math"),
  ]),
 dict(slug="patterns", title="HOW REAL AGENTS ARE BUILT", accent=(204,120,92), mark="orb", pill="builder",
  cover=("Your agent is fine.","Your architecture is not."),
  close=("Save the patterns","and check your stack.","Which pattern is your setup missing?"),
  slides=[
   ("PATTERN 1",("Think, act, look.","Then think again."),"Real agents think before every tool call and check what came back.",("No blind execution.",),"react"),
   ("PATTERN 2",("It does not describe fixes.","It merges them."),"SENTINEL does not describe the fix. It writes it, tests it, ships it.",("Output you can merge.",),"codeact"),
   ("PATTERN 3",("Plan with the big brain.","Run with the cheap one."),"Deep judgement plans once, the light tier runs each step. Cents, not seats.",("The router does this.",),"plan"),
   ("PATTERN 4",("v1 never reaches you.","v3 does."),"Outputs are ranked against your bar before you ever see them.",("Quality is a loop.",),"reflect"),
   ("PATTERN 5",("Seven specialists","beat one giant."),"Research, outbound, deals, content: one job each, done extremely well.",("Seven agents, handoffs.",),"multi"),
   ("THE STACK",("Real systems","stack all five."),"Ultron composes all five per job. You just type the goal.",("Composed, not chosen.",),"stack"),
   ("PATTERN 6",("Pattern six:","a human on the trigger."),"The most reliable design keeps one human on the only external trigger.",("You are the exit.",),"gate"),
   ("THE OPERATOR",("Same models.","Different companies."),"The same models, structured right, become a workforce.",("Architecture wins.",),"operator"),
  ]),
 dict(slug="setup", title="60 MINUTES TO AN OPERATOR", accent=(212,162,127), mark="orb", pill="founder",
  cover=("60 minutes on a Sunday.","A coworker by lunch."),
  close=("Save the checklist","and block the hour.","Which minute are you stuck on?"),
  slides=[
   ("MIN 0-10",("Minute 10:","the stack clicks in."),"Mail, CRM, calendar, payments. Ultron plugs into what you already run.",("No migration.",),"connect"),
   ("MIN 10-20",("Minute 20:","it knows my business."),"It interviews you once: ICP, offer, pricing, the no-list.",("The memory is born.",),"init"),
   ("MIN 20-30",("Minute 30:","it sounds like me."),"Paste your best posts. Every future draft sounds like you wrote it.",("No AI-speak, ever.",),"voice"),
   ("MIN 30-40",("Minute 40:","the handbrake is set."),"Decide what runs free and what waits for your tap. Default: external waits.",("Permissions first.",),"permissions"),
   ("MIN 40-50",("Minute 50:","first job, done."),"Source 20 accounts and brief them. Watch it finish work, not answer.",("The first win.",),"firsttask"),
   ("MIN 50-60",("Minute 60:","the digest lands."),"Overnight jobs, parked approvals, hot threads. Your new morning paper.",("You built a coworker.",),"digest"),
   ("THE COMPOUND",("Week two:","smarter than week one."),"Corrections become rules. Month two beats month one on its own.",("Setup pays forever.",),"compound"),
   ("THE OPERATOR",("One hour once.","Leverage forever."),"One founder, one memory, a company that runs behind a chat.",("Block the hour.",),"operator"),
  ]),
]
BATCH3=[
 dict(slug="verified", title="I CHECKED THE LISTS", accent=(200,70,35), mark="claude", pill="operator",
  cover=("Everyone posts skill lists.","I actually tested them."),
  close=("Save the shortlist,","skip the flood.","Which list burned you last?"),
  slides=[
   ("THE FLOOD",("Fifty skills per list.","Zero receipts."),"The same recycled lists, reposted daily. Nobody installs them, nobody verifies them.",("So I did.",),"flood"),
   ("THE TEST",("I installed","every single one."),"One week, every skill run on real work: briefs, drafts, builds, audits.",("Real work, not demos.",),"test"),
   ("THE FAKES",("A third were","made up."),"Dead links, renamed duplicates, skills that answer instead of execute.",("Cut without mercy.",),"fakes"),
   ("THE KEEPERS",("What survived","earns its slot."),"Writing, research, design, build: the shortlist that finishes work.",("Grouped by job.",),"keepers"),
   ("THE ORDER",("Start with the two","built by Anthropic."),"First-party skills first, then the verified community layer on top.",("The safe install order.",),"safest"),
   ("ULTRON",("Ultron ships them","pre-verified."),"The techniques library is curated and tested before it reaches your desk.",("No gambling on links.",),"curated"),
   ("THE RULE",("If it cannot execute,","it does not count."),"A skill that returns advice is a bookmark. Keep the ones that finish work.",("Execution or nothing.",),"rule"),
   ("THE DESK",("My desk runs","on survivors."),"Twelve skills, each tested on my own pipeline, running daily.",("Quality beats quantity.",),"desk"),
  ]),
 dict(slug="fivepaid", title="THE 5 SKILLS THAT PAY", accent=(212,162,127), mark="orb", pill="founder",
  cover=("Learn what businesses","already pay for."),
  close=("Save this and","pick your one.","Which of the 5 fits you?"),
  slides=[
   ("SKILL 1",("Research","that closes."),"Account briefs that turn cold calls warm. Companies pay retainers for this.",("CORTEX does it daily.",),"research"),
   ("SKILL 2",("Outbound","that lands."),"Sequences with one trigger per email and domains that stay warm.",("Placement is the skill.",),"outbound"),
   ("SKILL 3",("Content","in a voice."),"Not words. A voice clients recognize in the feed before the handle.",("Voice is the asset.",),"content"),
   ("SKILL 4",("Builds","without builders."),"Landing pages and dashboards from plain English, live the same day.",("Assembly, not code.",),"builds"),
   ("SKILL 5",("Systems","that keep running."),"Flows on triggers, digests at 07:00. The skill is setting exits, not typing.",("Loops beat prompts.",),"systems"),
   ("THE PICK",("Pick exactly one.","Go deep."),"One skill run daily inside Ultron beats five certificates on a shelf.",("Depth sells.",),"one"),
   ("THE PROOF",("Your first client is","your own company."),"Run the skill on your business first. The receipts become the pitch.",("Results are the resume.",),"client"),
   ("THE MATH",("Cents to practice.","Real money to sell."),"The meter runs in cents while you learn. The invoice runs high when you deliver.",("Practice is free now.",),"meter"),
  ]),
 dict(slug="installs24", title="THE POWER USER SETUP", accent=(204,120,92), mark="claude", pill="builder",
  cover=("Your AI is stock.","Power users install."),
  close=("Save the setup","and install tonight.","Which install goes first?"),
  slides=[
   ("STOCK",("Out of the box","it only answers."),"Stock settings are training wheels. Installed right, it operates.",("Stock is the floor.",),"stock"),
   ("PLUGINS",("A whole team","in one install."),"Each plugin is a desk: research, content, deals, code. Installed once.",("Desks, not features.",),"plugins"),
   ("SKILLS",("One line runs","the whole play."),"A slash command replaces a page of prompting. Repeatable, every time.",("Shortcuts with depth.",),"skills"),
   ("CONNECTORS",("It acts inside","your real apps."),"Mail, docs, CRM, payments. No copy-paste bridge, no tab zoo.",("Wired, not beside.",),"connectors"),
   ("THE TRIO",("Install three tonight:","marketing, design, docs."),"The starter trio that covers the loudest jobs first.",("Twenty minutes total.",),"three"),
   ("ULTRON",("Or skip the setup.","It comes installed."),"71 skills, 7 agents, connectors wired. Day one behaves like day one hundred.",("Pre-built power user.",),"preinstalled"),
   ("THE GATE",("The brake comes","installed too."),"Everything external waits for your tap. Power without accidents.",("Default: gated.",),"gate"),
   ("COMPOUND",("Set once.","Collect monthly."),"Corrections become rules. The setup pays rent every month after.",("It only gets sharper.",),"compound"),
  ]),
 dict(slug="advisors", title="THE BOARD OF ADVISORS", accent=(200,70,35), mark="orb", pill="founder",
  cover=("I built a board","that knows my numbers."),
  close=("Save this and","seat your board.","Which advisor do you need first?"),
  slides=[
   ("THE PROBLEM",("Advice is cheap.","Context is not."),"Generic advice ignores your deals, your clients, your cash. That is why it fails.",("Context is the moat.",),"context"),
   ("THE BOARD",("Three advisors,","three lenses."),"The pricer, the editor, the strategist. Each one a skill, each one on call.",("Zero retainers.",),"three"),
   ("THE UNLOCK",("They read","your books."),"Wired into the same memory: deals, clients, numbers. They advise on your data.",("Your numbers, not averages.",),"books"),
   ("THE PRICER",("It ran the numbers","and said: raise."),"Unit economics on a real proposal. The floor was too low and it proved why.",("Math, not vibes.",),"pricer"),
   ("THE EDITOR",("It read the draft","and said: cut half."),"Overwritten proposals bury the offer. It stripped it to the spine.",("Less closed more.",),"editor"),
   ("THE STRATEGIST",("It asked one question:","does this open doors?"),"Not is the deal good. Is the deal a doorway. Better filter, better clients.",("Doors, not dollars.",),"strategist"),
   ("THE CLOSE",("The deal signed","clean."),"Repriced, rewritten, requalified. One of the cleanest signatures this year.",("Three lenses, one win.",),"closed"),
   ("THE SEAT",("Your board sits","in one chat."),"On call at 2am, briefed on everything you sell, costing cents.",("Seat them tonight.",),"board"),
  ]),
 dict(slug="ghosted", title="WHY COLD EMAILS DIE", accent=(212,162,127), mark="claude", pill="builder",
  cover=("Your copy is fine.","Your infra is dead."),
  close=("Save the 5 mistakes","before your next batch.","Which one is killing you?"),
  slides=[
   ("THE PATTERN",("Same writer.","Opposite results."),"Some campaigns crushed. Others went to spam without a trace. Copy was never the variable.",("The infra was.",),"sent"),
   ("MISTAKE 1",("You count opens.","Buyers count replies."),"Tracking pixels hurt placement and measure vanity. Kill them.",("Replies or nothing.",),"opens"),
   ("MISTAKE 2",("Fresh domain,","full blast."),"No reputation plus max volume equals the promotions folder, forever.",("Reputation is earned.",),"fresh"),
   ("MISTAKE 3",("One domain carries","your whole pipeline."),"One bad batch burns the only asset you have. Spread the load.",("Four domains minimum.",),"onedomain"),
   ("MISTAKE 4",("Volume spikes","kill overnight."),"60 then 60 then 60 beats 0 then 500. Ramps live, blasts die.",("Boring wins inboxes.",),"spike"),
   ("MISTAKE 5",("Catch-all lists","drag everyone down."),"Unverified addresses poison the batch for the verified ones.",("Verify or pay.",),"catchall"),
   ("ULTRON",("The infra runs","by default."),"Warm domains, ramped sends, watched spam rates. You never think about it.",("99.2% inboxed.",),"infra"),
   ("THE LESSON",("Fix the road,","then the car."),"Great copy on dead infra is a love letter in a locked mailbox.",("Infra first, always.",),"road"),
  ]),
]
BATCH4=[
 dict(slug="twohours", title="ONE IDEA, TWO HOURS", accent=(204,120,92), mark="orb", pill="founder",
  cover=("I gave it one idea","and two hours."),
  close=("Save this timeline","and pick your idea.","What would you build in two hours?"),
  slides=[
   ("14:00",("One sentence.","The idea goes in."),"A service for founders who hate bookkeeping. That was the entire input.",("No deck, no plan.",),"input"),
   ("14:20",("The offer","stands up."),"Positioning, price, guarantee: drafted against the niche, not a template.",("Offer before logo.",),"offer"),
   ("14:50",("The page","goes live."),"Crescendo assembles hero, pricing and FAQ from the pack, in brand tokens.",("Preview, tap, live.",),"page"),
   ("15:10",("The content plan","lands."),"14 slots, three hooks per post, queued at 10:00 local.",("Distribution included.",),"plan"),
   ("15:30",("The outreach","waits at the gate."),"Twenty openers, one trigger each, parked for your tap.",("Nothing sent alone.",),"outreach"),
   ("16:00",("You review.","It ships."),"Offer, page, plan, script: two hours, one operator, zero meetings.",("Your tap, then live.",),"review"),
   ("16:01",("The excuse","died here."),"No team, no budget, no time: none of the three survived the afternoon.",("Excuses need effort now.",),"excuse"),
   ("THE MOAT",("Speed is the moat.","The gate keeps it safe."),"Idea to live while others plan. Feedback to fix within the hour.",("Move first, gated.",),"moat"),
  ]),
 dict(slug="salesorg", title="A SALES ORG, NOT A BOT", accent=(200,70,35), mark="orb", pill="operator",
  cover=("100-node sales bots fail.","Structure wins."),
  close=("Save the org chart","before you build a bot.","Which desk do you need first?"),
  slides=[
   ("THE TRAP",("One agent doing all","does nothing well."),"The mega-automation collapses under its own hundred branches.",("Complexity is not power.",),"everything"),
   ("THE FIX",("Real teams","have structure."),"Chief, desks, specialists. Sales worked this way for a century for a reason.",("Copy what works.",),"structure"),
   ("DESK 1",("Research:","prospect intel."),"CORTEX profiles, scores and briefs before anyone writes a word.",("Intel first.",),"research"),
   ("DESK 2",("Outreach:","gated sends."),"SPECTER drafts per channel; every send parks for your tap.",("Volume with brakes.",),"outreach"),
   ("DESK 3",("Enablement:","paperwork, done."),"Proposals, scheduling, follow-ups: the work nobody loves, on time.",("No dropped balls.",),"enable"),
   ("DESK 4",("RevOps:","the pipe stays true."),"Stages move on replies, data stays clean, digests land daily.",("Truth in the CRM.",),"revops"),
   ("THE RULE",("One job per agent,","done extremely well."),"That is a workforce, not a chatbot with a hundred to-dos.",("Specialists win.",),"onejob"),
   ("THE CHIEF",("You sit on top.","One tap a day."),"The org runs; you approve. Hierarchy with a human at the head.",("Chief, not operator.",),"chief"),
  ]),
 dict(slug="adsagency", title="THE AD DESK, IN-HOUSE", accent=(212,162,127), mark="claude", pill="operator",
  cover=("I brought the ad desk","in-house. It fits in a chat."),
  close=("Save the ad desk,","cancel the retainer.","Which check would save you most?"),
  slides=[
   ("THE RETAINER",("It bought slides","and delays."),"Research, copy, audits: billed monthly, delivered quarterly.",("That bill ends here.",),"retainer"),
   ("MONDAY",("Rival ads,","diffed weekly."),"Every new creative your competitors launched, in one report.",("You see their moves.",),"spy"),
   ("THE GAP",("The empty angle","is found for you."),"Hooks ranked by frequency; the angles nobody covers become yours.",("Attack the gap.",),"gap"),
   ("THE DRAFTS",("Twenty variations","from one description."),"Short, medium, long: in your voice, against your brand rules.",("A week of copy, instantly.",),"variations"),
   ("THE AUDIT",("186 checks","before budget moves."),"Fatigue, overlap, anomalies: a health score with a fix list attached.",("Audit, then spend.",),"audit"),
   ("THE SCORE",("Any ad, scored","before it spends."),"Six dimensions; weak hooks get rewritten, not launched.",("No gut launches.",),"score"),
   ("THE CHAIN",("The retainer month,","in one morning."),"Spy, gap, draft, audit, score: chained, under an hour.",("Monday ritual.",),"chain"),
   ("THE SIGNATURE",("Every launch","signs with your tap."),"Nothing spends without you. In-house means in your hands.",("Your call, always.",),"sign"),
  ]),
 dict(slug="million", title="THE ONE-LAPTOP COMPANY", accent=(204,120,92), mark="orb", pill="founder",
  cover=("The next big company","is one person."),
  close=("Save this thesis,","then start tonight.","Could you run it alone?"),
  slides=[
   ("THE SHAPE",("Not a funded startup.","Not a team of 20."),"A laptop, a subscription measured in cents, systems that do not sleep.",("New shape of company.",),"notteam"),
   ("THE SPLIT",("The agents work.","The founder decides."),"Research, outreach, content, builds: parallel, gated by one tap.",("Judgement is the job.",),"agents"),
   ("THE CURVE",("Revenue compounds.","Headcount stays 1."),"Up 32% this month; payroll unchanged since day zero.",("The lines diverge.",),"revenue"),
   ("THE MOAT",("Speed beats size","every quarter now."),"Idea to live offer in an afternoon. Feedback to fix in an hour.",("Size became drag.",),"speed"),
   ("THE COSTS",("The meter runs cents.","The market pays full."),"Costs flat while output multiplies. That spread is the business.",("Margin by design.",),"costs"),
   ("THE CALENDAR",("Empty calendar.","Full pipeline."),"No standups, no syncs. Digests at 07:00, decisions when you choose.",("Time became yours.",),"calendar"),
   ("THE CONTROL",("Every send gated.","Every risk yours."),"Autonomy scaled, control kept. That is the whole architecture.",("Power with a keel.",),"gated"),
   ("THE BET",("Someone builds this","this year."),"The only question left is whether it is you.",("Why not you.",),"you"),
  ]),
 dict(slug="zerostart", title="STARTING FROM ZERO, 2026", accent=(200,70,35), mark="claude", pill="builder",
  cover=("If I started from zero,","I would write no code."),
  close=("Save the zero plan","and pick the niche.","What would you start with?"),
  slides=[
   ("THE SHIFT",("The barrier moved.","It is not technical."),"Niche, distribution, consistency: the only three problems left.",("Everything else is solved.",),"barrier"),
   ("THE BUILD",("The build is","a sentence now."),"Describe the offer; Crescendo assembles the page from 822 parts.",("Live the same day.",),"build"),
   ("THE ENGINE",("The workflow runs","without you."),"Flows on triggers handle follow-up, delivery and reporting.",("Set exits, not alarms.",),"workflow"),
   ("THE NICHE",("Pick a problem","people already pay for."),"Boring niches, real invoices. The unglamorous print money.",("Boring is beautiful.",),"problem"),
   ("THE HABIT",("Show up daily.","The desk makes it cheap."),"14 posts planned from one line; your only job is to be real.",("Consistency, automated.",),"daily"),
   ("THE ODDS",("Most solo founders","hit profit in year one."),"Because the cost base is cents and the output is a team's.",("The math flipped.",),"profit"),
   ("THE FIRST TEN",("Ten customers,","ten handshakes."),"The machine sources and drafts; you close like a human.",("Humans buy from humans.",),"ten"),
   ("THE DEED",("Zero code. One gate.","All yours."),"Build, run, approve. The stack finally fits one person.",("Ownership, complete.",),"yours"),
  ]),
]

ALL=BATCH1+BATCH2+BATCH3+BATCH4
