#!/usr/bin/env python3
# ADAPTARI IG SCRAPED (operator 2026-07-02): 20 surse din vaultul lui Catalin, retraduse in
# context ULTRON. Fiecare deck: hooks virale, panouri clay cu utilitate distincta, CTA pe una
# din cele 3 pastile fixe (OPERATOR/FOUNDER/BUILDER, §30), marci de cover contextuale.
# Acest modul tine DOAR datele; build files + panourile se genereaza din el.

# (slug, TITLE, accent, mark, pill, cover(w,a), slides[8](eyebrow,hw,ha,sub,foot,stem), close(l1,l2,q))
# stem = cheia panoului din adapt_panels.SPECS[slug]

BATCH1=[
 dict(slug="aios", title="THE AI OPERATING SYSTEM", accent=(204,120,92), mark="claude", pill="operator",
  cover=("I quit 9 tools in one night.","They kept forgetting me."),
  close=("Save this to","own your OS.","Rented tools or your own command center?"),
  slides=[
   ("THE BOTTLENECK",("My AI asked who I was.","For the 40th time."),"Every chat starts from zero. That is the real bottleneck, not the model.",("The tab is not a system.",),"amnesia"),
   ("THE BRAIN",("It knows my no-list","better than my cofounder."),"Your ICP, voice, pricing and pipeline live in one memory, loaded in every run.",("Set once. Never re-briefed.",),"brain"),
   ("THE DASHBOARD",("Nine tabs died.","One screen survived."),"Every agent, flow and approval in one place, built on your own data.",("No tab zoo.",),"command"),
   ("THE HOURS",("3am. It closed a task.","I found out at 7."),"Flows fire on triggers around the clock, even with the laptop shut.",("Overnight is work time now.",),"always"),
   ("THE MEMORY",("I say things once.","That is the whole trick."),"Say no discounts once and the gate blocks them forever.",("It compounds monthly.",),"rules"),
   ("THE PROOF",("1,284 companies read.","My coffee was still hot."),"The OS briefed 200 accounts before the first coffee. One typed sentence.",("While you slept.",),"proof"),
   ("THE GATE",("It can do anything.","It may do nothing alone."),"Nothing external fires alone. You read, you tap, it moves.",("Power, gated.",),"gate"),
   ("THE OPERATOR",("Renters restart daily.","Owners compound."),"One subscription, one memory, one command center behind a chat.",("Build yours today.",),"own"),
  ]),
 dict(slug="loops", title="PROMPTS ARE DEAD, LOOPS RUN", accent=(200,70,35), mark="claude", pill="builder",
  cover=("Stop writing prompts.","Start setting exits."),
  close=("Save this before","your next prompt.","Which task would you loop first?"),
  slides=[
   ("THE OLD WAY",("You are a human cron job.","Admit it."),"If you type prompt after prompt, you work backwards, one output at a time.",("You are the cron job.",),"oldway"),
   ("THE LOOP",("212 cycles ran.","I typed 3 sentences."),"An Ultron flow has a goal, a checker and an exit. It cycles until done.",("24/7, no typing.",),"loop"),
   ("STEP 1",("One sentence replaced","my follow-up job."),"Follow up every lead that goes quiet for 3 days. One sentence, one flow.",("That is the whole setup.",),"define"),
   ("STEP 2",("9:00 fires without me.","Every single day."),"Daily 09:00, on every reply, on usage drop. Triggers replace your memory.",("No reminders app.",),"trigger"),
   ("STEP 3",("It grades its own work.","Before I ever see it."),"Every cycle checks the result before it reports. Failures retry, not repeat.",("The checker is built in.",),"verify"),
   ("THE TRAP",("Loops without exits","eat budgets alive."),"A loop without an exit spends while you sleep. Ultron caps every flow.",("Guardrails by default.",),"trap"),
   ("THE GATE",("Full speed inside.","Handbrake on the door."),"Anything external still parks on HOLD for your tap. Speed with brakes.",("You stay the exit.",),"gate"),
   ("THE SCALE",("My hours stopped scaling.","My systems did not."),"Nine flows ran 212 cycles last week. You typed three sentences.",("Scale past your hours.",),"scale"),
  ]),
 dict(slug="aibody", title="THE COMPLETE AI BODY", accent=(212,162,127), mark="orb", pill="founder",
  cover=("You bought a mouth.","You needed a body."),
  close=("Save this and","augment every part.","Which part of you needs the upgrade first?"),
  slides=[
   ("THE DIFFERENCE",("Talking is not working.","Ask your chatbot."),"Most founders rent one mouth. The top operators wire every organ.",("Augment, not chat.",),"difference"),
   ("THE BRAIN",("A brain that budgets","its own thinking."),"It reads each job, hires the right agent, picks the model tier per turn.",("You never pick a model.",),"router"),
   ("THE EYES",("It saw the funding round","before my VC did."),"Funding, hiring, stack, intent. Signals you would never spot by hand.",("Overnight, every night.",),"eyes"),
   ("THE VOICE",("It stole my writing style.","I approved."),"Sampled from your real posts. Banned words enforced on every draft.",("Your voice, multiplied.",),"voice"),
   ("THE HANDS",("Built, tested, shipped.","I was at dinner."),"Pages, dashboards and fixes from plain English, tested before you see them.",("Built while you sleep.",),"hands"),
   ("THE HEART",("Cut the memory","and the body dies."),"ICP, pipeline, pricing, docs. Every agent draws from the same core.",("Nothing forgets you.",),"heart"),
   ("THE GATE",("Strong body.","My reins."),"Every external move parks for your tap. Augmented, not replaced.",("Still your company.",),"gate"),
   ("THE OPERATOR",("Stop chatting with organs.","Assemble the body."),"One chat wires brain, eyes, voice, hands and heart into one operator.",("The full body, one login.",),"operator"),
  ]),
 dict(slug="fivesigns", title="5 SIGNS YOU NEED AI NOW", accent=(204,120,92), mark="orb", pill="founder",
  cover=("Answer 5 questions.","Count your leaks."),
  close=("Save this checklist","and score yourself.","How many of the 5 did you tick?"),
  slides=[
   ("SIGN 1",("Q1: same answer,","typed 40 times a week?"),"If support answers repeat daily, a flow should answer them in seconds.",("Ultron replies 24/7.",),"sign1"),
   ("SIGN 2",("Q2: is payroll","moving data by hand?"),"Hours spent moving data between apps is payroll spent on glue work.",("Flows move it instantly.",),"sign2"),
   ("SIGN 3",("Q3: does work queue","behind your thumbs?"),"You are the bottleneck. Ultron preps everything, you just tap.",("Approval, not assembly.",),"sign3"),
   ("SIGN 4",("Q4: do leads cool off","in your inbox?"),"Speed to lead decides the meeting. The flow answers in seconds, gated.",("First reply wins.",),"sign4"),
   ("SIGN 5",("Q5: does month-end","steal three days?"),"The numbers already exist. Ultron assembles them on demand, with sources.",("Reports in minutes.",),"sign5"),
   ("THE TEST",("Three yes or more?","You are the system."),"Five yes answers is not a staffing problem. It is missing systems.",("Friction, not headcount.",),"test"),
   ("THE FIX",("Plug the worst leak","this week. One sentence."),"Automate the worst leak first. Ultron sets it up from one sentence.",("Start small, compound.",),"fix"),
   ("THE GATE",("Automate the work.","Keep the veto."),"Every flow that touches a customer parks for your tap first.",("You stay in control.",),"gate"),
  ]),
 dict(slug="contentdesk", title="THE 500K CONTENT DESK", accent=(200,70,35), mark="claude", pill="operator",
  cover=("Five salaries quit my desk.","Output went up."),
  close=("Save the desk","and steal the setup.","Which of the five would you run first?"),
  slides=[
   ("SKILL 1",("Monday, 07:00.","The week plans itself."),"One line in, 14 slots out, spread across channels at 10:00 local.",("Zero coordinators.",),"cal"),
   ("SKILL 2",("Three hooks fight.","I crown one."),"Three angles per post from your proven hook bank. You pick the winner.",("A/B/C, one tap.",),"hooks"),
   ("SKILL 3",("It writes like me","on my best day."),"Sampled from your real posts, banned words enforced, ranked before you read.",("No AI-speak.",),"voice"),
   ("SKILL 4",("One brief.","Five channels, native."),"LinkedIn long-form, caption, carousel, newsletter, script. Same brief.",("Native per channel.",),"repurpose"),
   ("SKILL 5",("99.2% inboxed.","Unseen content is rent."),"Warm domains, ramped sends, 99.2% placement. Content nobody reads is free.",("Delivery is the job.",),"inbox"),
   ("THE DESK",("No standups.","The desk never meets."),"The whole pipeline runs behind one chat with one memory of your brand.",("PULSE owns it.",),"desk"),
   ("THE GATE",("My feed, my thumb.","Nothing posts alone."),"Every draft parks first. You approve the batch in one read.",("Your feed, your call.",),"gate"),
   ("THE MATH",("The desk bills in cents.","Not in Mondays."),"Planner, writer, designer, distributor: one subscription, metered by use.",("Payroll: zero.",),"math"),
  ]),
]

BATCH2=[
 dict(slug="unstuck", title="STUCK AT LEVEL ONE", accent=(204,120,92), mark="claude", pill="builder",
  cover=("You are at level 1.","The map goes to 5."),
  close=("Save the map","and climb one level.","Which level are you honestly at?"),
  slides=[
   ("LEVEL 1",("Ask. Copy. Close.","The hamster wheel."),"Ask, copy, close the tab. A smarter search bar, nothing more.",("The floor, not the ceiling.",),"floor"),
   ("LEVEL 2",("Level 2: it remembers","what you hate."),"Your ICP, voice and pricing persist. No more introductions every morning.",("It remembers you now.",),"memory"),
   ("LEVEL 3",("Level 3: it works","while you watch."),"Agents source, brief and draft while you do the one thing only you can do.",("Work, not answers.",),"jobs"),
   ("LEVEL 4",("Level 4: it ships","while you sell."),"Pages and fixes from plain English, tested before you ever see them.",("Your eng team in a chat.",),"ship"),
   ("LEVEL 5",("Level 5: it runs","while you sleep."),"Triggers replace typing. The digest waits for you at 07:00.",("The machine works nights.",),"routines"),
   ("THE GAP",("Nobody told you","level 3 exists."),"Most founders never hear that the next level exists. Now you have.",("Five levels, one chat.",),"gap"),
   ("THE GATE",("Climb fast.","Keep the handbrake."),"Autonomy grows, control does not shrink. External moves park for you.",("Climb without crashing.",),"gate"),
   ("THE CEILING",("The ceiling is quiet.","Just running."),"One founder, one subscription, a company that moves overnight.",("See you up there.",),"ceiling"),
  ]),
 dict(slug="hidden", title="THE HIDDEN SKILLS", accent=(212,162,127), mark="claude", pill="operator",
  cover=("Prompting is level zero.","Installing is the game."),
  close=("Save the list","before you prompt again.","Which skill would save you the most hours?"),
  slides=[
   ("THE MYTH",("Re-wording requests","is not a skill."),"The top operators install capabilities. The rest re-word requests.",("Skills beat phrasing.",),"myth"),
   ("DECKS",("The proposal built itself.","I added the price."),"Client name in, structured deck out, in your tokens and your voice.",("No blank slides.",),"decks"),
   ("SHEETS",("Numbers with receipts.","Every figure traces."),"Live figures with sources attached, not screenshots of spreadsheets.",("Ask, do not assemble.",),"sheets"),
   ("CONTRACTS",("The NDA came back","already redlined."),"COUNSEL reads the NDA, flags the risk lines, drafts the redlines.",("Minutes, not lawyers-first.",),"contracts"),
   ("VISUALS",("822 parts,","zero design queue."),"822 Crescendo components assemble into on-brand visuals and sites.",("No design queue.",),"visuals"),
   ("CONNECTORS",("It acts inside my tools.","Not beside them."),"Mail, CRM, calendar, payments. It acts in your tools, not beside them.",("No copy-paste bridge.",),"connectors"),
   ("THE RESULT",("Answers are cheap.","Execution is the product."),"Files created, work automated, tasks finished. That is the difference.",("Executor, not assistant.",),"result"),
   ("THE GATE",("Executes at AI speed.","Sends at my speed."),"Everything external parks first. You stay the only trigger.",("Power needs brakes.",),"gate"),
  ]),
 dict(slug="carouselcmd", title="THE CAROUSEL COMMAND", accent=(200,70,35), mark="claude", pill="operator",
  cover=("My designer invoice","died mid-month."),
  close=("Save this before","your next invoice.","What would you build with the saved retainer?"),
  slides=[
   ("THE OLD BILL",("A week per deck.","Plus revision rounds."),"Briefs, revisions, queue time. A week per deck, every deck.",("That bill ends today.",),"oldbill"),
   ("THE COMMAND",("It interviews me.","Then builds alone."),"PULSE interviews you for the angle, then owns the build end to end.",("It asks, you answer.",),"command"),
   ("THE VISUALS",("My tokens, my type.","No template smell."),"Brand colors, brand type, brand components. No template smell.",("Yours, not a template.",),"visuals"),
   ("THE SLIDES",("Ten pages assembled","on proven bones."),"Hook, body, CTA: structured like the decks that already performed.",("Built on receipts.",),"slides"),
   ("THE CAPTIONS",("The caption kit","writes itself in."),"CTA-first caption, hashtags, first comment. The whole posting kit.",("Nothing left to write.",),"captions"),
   ("THE CLOCK",("Coffee brewed.","Deck done."),"Cover, slides, captions, sized per channel. While the coffee brews.",("A week becomes minutes.",),"clock"),
   ("THE GATE",("One review. One tap.","Then it posts."),"You review the batch once. Nothing posts alone.",("Your feed, your call.",),"gate"),
   ("THE MATH",("Retainer money","became runway."),"Metered by use, not by seats. The retainer becomes runway.",("Cancel, then compound.",),"math"),
  ]),
 dict(slug="patterns", title="HOW REAL AGENTS ARE BUILT", accent=(204,120,92), mark="orb", pill="builder",
  cover=("Your agent is fine.","Your architecture is not."),
  close=("Save the patterns","and check your stack.","Which pattern is your setup missing?"),
  slides=[
   ("PATTERN 1",("Think, act, look.","Then think again."),"Real agents think before every tool call and check what came back.",("No blind execution.",),"react"),
   ("PATTERN 2",("It does not describe fixes.","It merges them."),"SENTINEL does not describe the fix. It writes it, tests it, ships it.",("Output you can merge.",),"codeact"),
   ("PATTERN 3",("Plan with the big brain.","Run with the cheap one."),"Deep judgement plans once, the light tier runs each step. Cents, not seats.",("The router does this.",),"plan"),
   ("PATTERN 4",("v1 never reaches you.","v3 does."),"Outputs are ranked against your bar before you ever see them.",("Quality is a loop.",),"reflect"),
   ("PATTERN 5",("Seven specialists","beat one giant."),"Research, outbound, deals, content: one job each, done extremely well.",("Seven agents, handoffs.",),"multi"),
   ("THE STACK",("Real systems","stack all five."),"Ultron composes all five per job. You just type the goal.",("Composed, not chosen.",),"stack"),
   ("PATTERN 6",("Pattern six:","a human on the trigger."),"The most reliable design keeps one human on the only external trigger.",("You are the exit.",),"gate"),
   ("THE OPERATOR",("Same models.","Different companies."),"The same models, structured right, become a workforce.",("Architecture wins.",),"operator"),
  ]),
 dict(slug="setup", title="60 MINUTES TO AN OPERATOR", accent=(212,162,127), mark="orb", pill="founder",
  cover=("60 minutes on a Sunday.","A coworker by lunch."),
  close=("Save the checklist","and block the hour.","Which minute are you stuck on?"),
  slides=[
   ("MIN 0-10",("Minute 10:","the stack clicks in."),"Mail, CRM, calendar, payments. Ultron plugs into what you already run.",("No migration.",),"connect"),
   ("MIN 10-20",("Minute 20:","it knows my business."),"It interviews you once: ICP, offer, pricing, the no-list.",("The memory is born.",),"init"),
   ("MIN 20-30",("Minute 30:","it sounds like me."),"Paste your best posts. Every future draft sounds like you wrote it.",("No AI-speak, ever.",),"voice"),
   ("MIN 30-40",("Minute 40:","the handbrake is set."),"Decide what runs free and what waits for your tap. Default: external waits.",("Permissions first.",),"permissions"),
   ("MIN 40-50",("Minute 50:","first job, done."),"Source 20 accounts and brief them. Watch it finish work, not answer.",("The first win.",),"firsttask"),
   ("MIN 50-60",("Minute 60:","the digest lands."),"Overnight jobs, parked approvals, hot threads. Your new morning paper.",("You built a coworker.",),"digest"),
   ("THE COMPOUND",("Week two:","smarter than week one."),"Corrections become rules. Month two beats month one on its own.",("Setup pays forever.",),"compound"),
   ("THE OPERATOR",("One hour once.","Leverage forever."),"One founder, one memory, a company that runs behind a chat.",("Block the hour.",),"operator"),
  ]),
]
BATCH3=[]  # verified, fivepaid, installs24, advisors, ghosted
BATCH4=[]  # twohours, salesorg, adsagency, million, zerostart

ALL=BATCH1+BATCH2+BATCH3+BATCH4
