#!/usr/bin/env python3
# ADAPTARI IG SCRAPED (operator 2026-07-02): 20 surse din vaultul lui Catalin, retraduse in
# context ULTRON. Fiecare deck: hooks virale, panouri clay cu utilitate distincta, CTA pe una
# din cele 3 pastile fixe (OPERATOR/FOUNDER/BUILDER, §30), marci de cover contextuale.
# Acest modul tine DOAR datele; build files + panourile se genereaza din el.

# (slug, TITLE, accent, mark, pill, cover(w,a), slides[8](eyebrow,hw,ha,sub,foot,stem), close(l1,l2,q))
# stem = cheia panoului din adapt_panels.SPECS[slug]

BATCH1=[
 dict(slug="aios", title="THE AI OPERATING SYSTEM", accent=(204,120,92), mark="claude", pill="operator",
  cover=("Nine tools forgot who I was.","I quit all nine."),
  close=("Save this to","own your OS.","Rented tools or your own command center?"),
  slides=[
   ("THE BOTTLENECK",("My AI asked who I was.","For the 40th time."),"Every chat starts from zero. That is the real bottleneck, not the model.",("The tab is not a system.",),"amnesia"),
   ("THE BRAIN",("It knows my no-list","better than my cofounder."),"Your ICP, voice, pricing and pipeline live in one memory, loaded in every run.",("Set once. Never re-briefed.",),"brain"),
   ("THE DASHBOARD",("Nine tabs died.","One screen survived."),"Every agent, flow and approval in one place, built on your own data.",("No tab zoo.",),"command"),
   ("THE HOURS",("3am. It closed a task.","I found out at 7."),"Flows fire on triggers around the clock, even with the laptop shut.",("Overnight is work time now.",),"always"),
   ("THE MEMORY",("I say things once.","That is the whole trick."),"Say no discounts once and the gate blocks them forever.",("It compounds monthly.",),"rules"),
   ("THE PROOF",("1,284 companies read.","My coffee was still hot."),"The OS briefed 200 accounts before the first coffee. One typed sentence.",("While you slept.",),"proof"),
   ("THE GATE",("It can do anything.","It may do nothing alone."),"Nothing external fires alone. You read, you tap, it moves.",("Power, gated.",),"gate"),
   ("THE OPERATOR",("Renters restart daily.","Owners compound."),"One subscription, one memory, one command center behind a chat.",("Build yours today.",),"own"),
  ]),
 dict(slug="loops", title="PROMPTS ARE DEAD, LOOPS RUN", accent=(200,70,35), mark="claude", pill="builder",
  cover=("You are the cron job","in your own company."),
  close=("Save this before","your next prompt.","Which task would you loop first?"),
  slides=[
   ("THE OLD WAY",("You are a human cron job.","Admit it."),"If you type prompt after prompt, you work backwards, one output at a time.",("You are the cron job.",),"oldway"),
   ("THE LOOP",("212 cycles ran.","I typed 3 sentences."),"An Ultron flow has a goal, a checker and an exit. It cycles until done.",("24/7, no typing.",),"loop"),
   ("STEP 1",("One sentence replaced","my follow-up job."),"Follow up every lead that goes quiet for 3 days. One sentence, one flow.",("That is the whole setup.",),"define"),
   ("STEP 2",("9:00 fires without me.","Every single day."),"Daily 09:00, on every reply, on usage drop. Triggers replace your memory.",("No reminders app.",),"trigger"),
   ("STEP 3",("It grades its own work.","Before I ever see it."),"Every cycle checks the result before it reports. Failures retry, not repeat.",("The checker is built in.",),"verify"),
   ("THE TRAP",("Loops without exits","eat budgets alive."),"A loop without an exit spends while you sleep. Ultron caps every flow.",("Guardrails by default.",),"trap"),
   ("THE GATE",("Full speed inside.","Handbrake on the door."),"Anything external still parks on HOLD for your tap. Speed with brakes.",("You stay the exit.",),"gate"),
   ("THE SCALE",("My hours stopped scaling.","My systems did not."),"Nine flows ran 212 cycles last week. You typed three sentences.",("Scale past your hours.",),"scale"),
  ]),
 dict(slug="aibody", title="THE COMPLETE AI BODY", accent=(212,162,127), mark="claude", pill="founder",
  cover=("You rented a mouth.","Your company needs hands."),
  close=("Save this and","augment every part.","Which part of you needs the upgrade first?"),
  slides=[
   ("THE DIFFERENCE",("Talking is not working.","Ask your chatbot."),"Most founders rent one mouth. The top operators wire every organ.",("Augment, not chat.",),"difference"),
   ("THE BRAIN",("A brain that budgets","its own thinking."),"It reads each job, hires the right agent, picks the model tier per turn.",("You never pick a model.",),"router"),
   ("THE EYES",("It saw the funding round","before my VC did."),"Funding, hiring, stack, intent. Signals you would never spot by hand.",("Overnight, every night.",),"eyes"),
   ("THE VOICE",("It stole my writing style.","I approved."),"Sampled from your real posts. Banned words enforced on every draft.",("Your voice, multiplied.",),"voice"),
   ("THE HANDS",("Built, tested, shipped.","I was at dinner."),"Pages, dashboards and fixes from plain English, tested before you see them.",("Built while you sleep.",),"hands"),
   ("THE HEART",("Cut the memory","and the body dies."),"ICP, pipeline, pricing, docs. Every agent draws from the same core.",("Nothing forgets you.",),"heart"),
   ("THE GATE",("Strong body.","My reins."),"Every external move parks for your tap. Augmented, not replaced.",("Still your company.",),"gate"),
   ("THE OPERATOR",("Stop chatting with organs.","Assemble the body."),"One chat wires brain, eyes, voice, hands and heart into one operator.",("The full body, one login.",),"operator"),
  ]),
 dict(slug="fivesigns", title="5 SIGNS YOU NEED AI NOW", accent=(204,120,92), mark="claude", pill="founder",
  cover=("Most founders fail","this five-question test."),
  close=("Save this checklist","and score yourself.","How many of the 5 did you tick?"),
  slides=[
   ("SIGN 1",("Q1: same answer,","typed 40 times a week?"),"If support answers repeat daily, a flow should answer them in seconds.",("Ultron replies 24/7.",),"sign1"),
   ("SIGN 2",("Q2: is payroll","moving data by hand?"),"Hours spent moving data between apps is payroll spent on glue work.",("Flows move it instantly.",),"sign2"),
   ("SIGN 3",("Q3: does work queue","behind your thumbs?"),"You are the bottleneck. Ultron preps everything, you just tap.",("Approval, not assembly.",),"sign3"),
   ("SIGN 4",("Q4: do leads cool off","in your inbox?"),"Speed to lead decides the meeting. The flow answers in seconds, gated.",("First reply wins.",),"sign4"),
   ("SIGN 5",("Q5: does month-end","steal three days?"),"The numbers already exist. Ultron assembles them on demand, with sources.",("Reports in minutes.",),"sign5"),
   ("THE TEST",("Three yes or more?","You are the system."),"Five yes answers is not a staffing problem. It is missing systems.",("Friction, not headcount.",),"test"),
   ("THE FIX",("Plug the worst leak","this week. One sentence."),"Automate the worst leak first. Ultron sets it up from one sentence.",("Start small, compound.",),"fix"),
   ("THE GATE",("Automate the work.","Keep the veto."),"Every flow that touches a customer parks for your tap first.",("You stay in control.",),"gate"),
  ]),
 dict(slug="contentdesk", title="THE 500K CONTENT DESK", accent=(200,70,35), mark="claude", pill="operator",
  cover=("My content team never sleeps","and never meets."),
  close=("Save the desk","and steal the setup.","Which of the five would you run first?"),
  slides=[
   ("SKILL 1",("Monday, 07:00.","The week plans itself."),"One line in, 14 slots out, spread across channels at 10:00 local.",("Zero coordinators.",),"cal"),
   ("SKILL 2",("Three hooks fight.","I crown one."),"Three angles per post from your proven hook bank. You pick the winner.",("A/B/C, one tap.",),"hooks"),
   ("SKILL 3",("It writes like me","on my best day."),"Sampled from your real posts, banned words enforced, ranked before you read.",("No AI-speak.",),"voice"),
   ("SKILL 4",("One brief.","Five channels, native."),"LinkedIn long-form, caption, carousel, newsletter, script. Same brief.",("Native per channel.",),"repurpose"),
   ("SKILL 5",("99.2% inboxed.","Unseen content is rent."),"Warm domains, ramped sends, 99.2% placement. Content nobody reads is free.",("Delivery is the job.",),"inbox"),
   ("THE DESK",("No standups.","The desk never meets."),"The whole pipeline runs behind one chat with one memory of your brand.",("PULSE owns it.",),"desk"),
   ("THE GATE",("My feed, my thumb.","Nothing posts alone."),"Every draft parks first. You approve the batch in one read.",("Your feed, your call.",),"gate"),
   ("THE MATH",("The desk bills in cents.","Not in Mondays."),"Planner, writer, designer, distributor: one subscription, metered by use.",("Payroll: zero.",),"math"),
  ]),
]

BATCH2=[
 dict(slug="unstuck", title="STUCK AT LEVEL ONE", accent=(204,120,92), mark="claude", pill="builder",
  cover=("You use 12% of Claude.","Here is the other 88."),
  close=("Save the map","and climb one level.","Which level are you honestly at?"),
  slides=[
   ("LEVEL 1",("Ask. Copy. Close.","The hamster wheel."),"Ask, copy, close the tab. A smarter search bar, nothing more.",("The floor, not the ceiling.",),"floor"),
   ("LEVEL 2",("Level 2: it remembers","what you hate."),"Your ICP, voice and pricing persist. No more introductions every morning.",("It remembers you now.",),"memory"),
   ("LEVEL 3",("Level 3: it works","while you watch."),"Agents source, brief and draft while you do the one thing only you can do.",("Work, not answers.",),"jobs"),
   ("LEVEL 4",("Level 4: it ships","while you sell."),"Pages and fixes from plain English, tested before you ever see them.",("Your eng team in a chat.",),"ship"),
   ("LEVEL 5",("Level 5: it runs","while you sleep."),"Triggers replace typing. The digest waits for you at 07:00.",("The machine works nights.",),"routines"),
   ("THE GAP",("Nobody told you","level 3 exists."),"Most founders never hear that the next level exists. Now you have.",("Five levels, one chat.",),"gap"),
   ("THE GATE",("Climb fast.","Keep the handbrake."),"Autonomy grows, control does not shrink. External moves park for you.",("Climb without crashing.",),"gate"),
   ("THE CEILING",("The ceiling is quiet.","Just running."),"One founder, one subscription, a company that moves overnight.",("See you up there.",),"ceiling"),
  ]),
 dict(slug="hidden", title="THE HIDDEN SKILLS", accent=(212,162,127), mark="claude", pill="operator",
  cover=("You mastered prompting.","That was the tutorial level."),
  close=("Save the list","before you prompt again.","Which skill would save you the most hours?"),
  slides=[
   ("THE MYTH",("Re-wording requests","is not a skill."),"The top operators install capabilities. The rest re-word requests.",("Skills beat phrasing.",),"myth"),
   ("DECKS",("The proposal built itself.","I added the price."),"Client name in, structured deck out, in your tokens and your voice.",("No blank slides.",),"decks"),
   ("SHEETS",("Numbers with receipts.","Every figure traces."),"Live figures with sources attached, not screenshots of spreadsheets.",("Ask, do not assemble.",),"sheets"),
   ("CONTRACTS",("The NDA came back","already redlined."),"COUNSEL reads the NDA, flags the risk lines, drafts the redlines.",("Minutes, not lawyers-first.",),"contracts"),
   ("VISUALS",("822 parts,","zero design queue."),"822 Crescendo components assemble into on-brand visuals and sites.",("No design queue.",),"visuals"),
   ("CONNECTORS",("It acts inside my tools.","Not beside them."),"Mail, CRM, calendar, payments. It acts in your tools, not beside them.",("No copy-paste bridge.",),"connectors"),
   ("THE RESULT",("Answers are cheap.","Execution is the product."),"Files created, work automated, tasks finished. That is the difference.",("Executor, not assistant.",),"result"),
   ("THE GATE",("Executes at AI speed.","Sends at my speed."),"Everything external parks first. You stay the only trigger.",("Power needs brakes.",),"gate"),
  ]),
 dict(slug="carouselcmd", title="THE CAROUSEL COMMAND", accent=(200,70,35), mark="claude", pill="operator",
  cover=("This carousel built itself.","Yours can too."),
  close=("Save this before","your next invoice.","What would you build with the saved retainer?"),
  slides=[
   ("THE OLD BILL",("A week per deck.","Plus revision rounds."),"Briefs, revisions, queue time. A week per deck, every deck.",("That bill ends today.",),"oldbill"),
   ("THE COMMAND",("It interviews me.","Then builds alone."),"PULSE interviews you for the angle, then owns the build end to end.",("It asks, you answer.",),"command"),
   ("THE VISUALS",("My tokens, my type.","No template smell."),"Brand colors, brand type, brand components. No template smell.",("Yours, not a template.",),"visuals"),
   ("THE SLIDES",("Ten pages assembled","on proven bones."),"Hook, body, CTA: structured like the decks that already performed.",("Built on receipts.",),"slides"),
   ("THE CAPTIONS",("The caption kit","writes itself in."),"CTA-first caption, hashtags, first comment. The whole posting kit.",("Nothing left to write.",),"captions"),
   ("THE CLOCK",("Coffee brewed.","Deck done."),"Cover, slides, captions, sized per channel. While the coffee brews.",("A week becomes minutes.",),"clock"),
   ("THE GATE",("One review. One tap.","Then it posts."),"You review the batch once. Nothing posts alone.",("Your feed, your call.",),"gate"),
   ("THE MATH",("Retainer money","became runway."),"Metered by use, not by seats. The retainer becomes runway.",("Cancel, then compound.",),"math"),
  ]),
 dict(slug="patterns", title="HOW REAL AGENTS ARE BUILT", accent=(204,120,92), mark="claude", pill="builder",
  cover=("Agents do not fail.","Their builders do."),
  close=("Save the patterns","and check your stack.","Which pattern is your setup missing?"),
  slides=[
   ("PATTERN 1",("Think, act, look.","Then think again."),"Real agents think before every tool call and check what came back.",("No blind execution.",),"react"),
   ("PATTERN 2",("It does not describe fixes.","It merges them."),"SENTINEL does not describe the fix. It writes it, tests it, ships it.",("Output you can merge.",),"codeact"),
   ("PATTERN 3",("Plan with the big brain.","Run with the cheap one."),"Deep judgement plans once, the light tier runs each step. Cents, not seats.",("The router does this.",),"plan"),
   ("PATTERN 4",("v1 never reaches you.","v3 does."),"Outputs are ranked against your bar before you ever see them.",("Quality is a loop.",),"reflect"),
   ("PATTERN 5",("Seven specialists","beat one giant."),"Research, outbound, deals, content: one job each, done extremely well.",("Seven agents, handoffs.",),"multi"),
   ("THE STACK",("Real systems","stack all five."),"Ultron composes all five per job. You just type the goal.",("Composed, not chosen.",),"stack"),
   ("PATTERN 6",("Pattern six:","a human on the trigger."),"The most reliable design keeps one human on the only external trigger.",("You are the exit.",),"gate"),
   ("THE OPERATOR",("Same models.","Different companies."),"The same models, structured right, become a workforce.",("Architecture wins.",),"operator"),
  ]),
 dict(slug="setup", title="60 MINUTES TO AN OPERATOR", accent=(212,162,127), mark="claude", pill="founder",
  cover=("Give me one hour.","Get back a coworker."),
  close=("Save the checklist","and block the hour.","Which minute are you stuck on?"),
  slides=[
   ("MIN 0-10",("Minute 10:","the stack clicks in."),"Mail, CRM, calendar, payments. Ultron plugs into what you already run.",("No migration.",),"connect"),
   ("MIN 10-20",("Minute 20:","it knows my business."),"It interviews you once: ICP, offer, pricing, the no-list.",("The memory is born.",),"init"),
   ("MIN 20-30",("Minute 30:","it sounds like me."),"Paste your best posts. Every future draft sounds like you wrote it.",("No AI-speak, ever.",),"voice"),
   ("MIN 30-40",("Minute 40:","the handbrake is set."),"Decide what runs free and what waits for your tap. Default: external waits.",("Permissions first.",),"permissions"),
   ("MIN 40-50",("Minute 50:","first job, done."),"Source 20 accounts and brief them. Watch it finish work, not answer.",("The first win.",),"firsttask"),
   ("MIN 50-60",("Minute 60:","the digest lands."),"Overnight jobs, parked approvals, hot threads. Your new morning paper.",("You built a coworker.",),"digest"),
   ("THE COMPOUND",("Week two:","smarter than week one."),"Corrections become rules. Month two beats month one on its own.",("Setup pays forever.",),"compound"),
   ("THE OPERATOR",("One hour once.","Leverage forever."),"One founder, one memory, a company that runs behind a chat.",("Block the hour.",),"operator"),
  ]),
]
BATCH3=[
 dict(slug="verified", title="I CHECKED THE LISTS", accent=(200,70,35), mark="claude", pill="operator",
  cover=("I installed all 50 viral skills.","A third are fake."),
  close=("Save the shortlist,","skip the flood.","Which list burned you last?"),
  slides=[
   ("THE FLOOD",("Fifty skills per list.","Zero receipts."),"The same recycled lists, reposted daily. Nobody installs them, nobody verifies them.",("So I did.",),"flood"),
   ("THE TEST",("I installed","every single one."),"One week, every skill run on real work: briefs, drafts, builds, audits.",("Real work, not demos.",),"test"),
   ("THE FAKES",("A third were","made up."),"Dead links, renamed duplicates, skills that answer instead of execute.",("Cut without mercy.",),"fakes"),
   ("THE KEEPERS",("What survived","earns its slot."),"Writing, research, design, build: the shortlist that finishes work.",("Grouped by job.",),"keepers"),
   ("THE ORDER",("Start with the two","built by Anthropic."),"First-party skills first, then the verified community layer on top.",("The safe install order.",),"safest"),
   ("ULTRON",("Ultron ships them","pre-verified."),"The techniques library is curated and tested before it reaches your desk.",("No gambling on links.",),"curated"),
   ("THE RULE",("If it cannot execute,","it does not count."),"A skill that returns advice is a bookmark. Keep the ones that finish work.",("Execution or nothing.",),"rule"),
   ("THE DESK",("My desk runs","on survivors."),"Twelve skills, each tested on my own pipeline, running daily.",("Quality beats quantity.",),"desk"),
  ]),
 dict(slug="fivepaid", title="THE 5 SKILLS THAT PAY", accent=(212,162,127), mark="claude", pill="founder",
  cover=("Stop learning AI skills","nobody will pay for."),
  close=("Save this and","pick your one.","Which of the 5 fits you?"),
  slides=[
   ("SKILL 1",("Research","that closes."),"Account briefs that turn cold calls warm. Companies pay retainers for this.",("CORTEX does it daily.",),"research"),
   ("SKILL 2",("Outbound","that lands."),"Sequences with one trigger per email and domains that stay warm.",("Placement is the skill.",),"outbound"),
   ("SKILL 3",("Content","in a voice."),"Not words. A voice clients recognize in the feed before the handle.",("Voice is the asset.",),"content"),
   ("SKILL 4",("Builds","without builders."),"Landing pages and dashboards from plain English, live the same day.",("Assembly, not code.",),"builds"),
   ("SKILL 5",("Systems","that keep running."),"Flows on triggers, digests at 07:00. The skill is setting exits, not typing.",("Loops beat prompts.",),"systems"),
   ("THE PICK",("Pick exactly one.","Go deep."),"One skill run daily inside Ultron beats five certificates on a shelf.",("Depth sells.",),"one"),
   ("THE PROOF",("Your first client is","your own company."),"Run the skill on your business first. The receipts become the pitch.",("Results are the resume.",),"client"),
   ("THE MATH",("Cents to practice.","Real money to sell."),"The meter runs in cents while you learn. The invoice runs high when you deliver.",("Practice is free now.",),"meter"),
  ]),
 dict(slug="installs24", title="THE POWER USER SETUP", accent=(204,120,92), mark="claude", pill="builder",
  cover=("Stock Claude answers questions.","Installed Claude runs your company."),
  close=("Save the setup","and install tonight.","Which install goes first?"),
  slides=[
   ("STOCK",("Out of the box","it only answers."),"Stock settings are training wheels. Installed right, it operates.",("Stock is the floor.",),"stock"),
   ("PLUGINS",("A whole team","in one install."),"Each plugin is a desk: research, content, deals, code. Installed once.",("Desks, not features.",),"plugins"),
   ("SKILLS",("One line runs","the whole play."),"A slash command replaces a page of prompting. Repeatable, every time.",("Shortcuts with depth.",),"skills"),
   ("CONNECTORS",("It acts inside","your real apps."),"Mail, docs, CRM, payments. No copy-paste bridge, no tab zoo.",("Wired, not beside.",),"connectors"),
   ("THE TRIO",("Install three tonight:","marketing, design, docs."),"The starter trio that covers the loudest jobs first.",("Twenty minutes total.",),"three"),
   ("ULTRON",("Or skip the setup.","It comes installed."),"71 skills, 7 agents, connectors wired. Day one behaves like day one hundred.",("Pre-built power user.",),"preinstalled"),
   ("THE GATE",("The brake comes","installed too."),"Everything external waits for your tap. Power without accidents.",("Default: gated.",),"gate"),
   ("COMPOUND",("Set once.","Collect monthly."),"Corrections become rules. The setup pays rent every month after.",("It only gets sharper.",),"compound"),
  ]),
 dict(slug="advisors", title="THE BOARD OF ADVISORS", accent=(200,70,35), mark="claude", pill="founder",
  cover=("Three advisors, on call at 2am.","They know my numbers."),
  close=("Save this and","seat your board.","Which advisor do you need first?"),
  slides=[
   ("THE PROBLEM",("Advice is cheap.","Context is not."),"Generic advice ignores your deals, your clients, your cash. That is why it fails.",("Context is the moat.",),"context"),
   ("THE BOARD",("Three advisors,","three lenses."),"The pricer, the editor, the strategist. Each one a skill, each one on call.",("Zero retainers.",),"three"),
   ("THE UNLOCK",("They read","your books."),"Wired into the same memory: deals, clients, numbers. They advise on your data.",("Your numbers, not averages.",),"books"),
   ("THE PRICER",("It ran the numbers","and said: raise."),"Unit economics on a real proposal. The floor was too low and it proved why.",("Math, not vibes.",),"pricer"),
   ("THE EDITOR",("It read the draft","and said: cut half."),"Overwritten proposals bury the offer. It stripped it to the spine.",("Less closed more.",),"editor"),
   ("THE STRATEGIST",("It asked one question:","does this open doors?"),"Not is the deal good. Is the deal a doorway. Better filter, better clients.",("Doors, not dollars.",),"strategist"),
   ("THE CLOSE",("The deal signed","clean."),"Repriced, rewritten, requalified. One of the cleanest signatures this year.",("Three lenses, one win.",),"closed"),
   ("THE SEAT",("Your board sits","in one chat."),"On call at 2am, briefed on everything you sell, costing cents.",("Seat them tonight.",),"board"),
  ]),
 dict(slug="ghosted", title="WHY COLD EMAILS DIE", accent=(212,162,127), mark="claude", pill="builder",
  cover=("Nobody reads your cold emails.","Nobody even gets them."),
  close=("Save the 5 mistakes","before your next batch.","Which one is killing you?"),
  slides=[
   ("THE PATTERN",("Same writer.","Opposite results."),"Some campaigns crushed. Others went to spam without a trace. Copy was never the variable.",("The infra was.",),"sent"),
   ("MISTAKE 1",("You count opens.","Buyers count replies."),"Tracking pixels hurt placement and measure vanity. Kill them.",("Replies or nothing.",),"opens"),
   ("MISTAKE 2",("Fresh domain,","full blast."),"No reputation plus max volume equals the promotions folder, forever.",("Reputation is earned.",),"fresh"),
   ("MISTAKE 3",("One domain carries","your whole pipeline."),"One bad batch burns the only asset you have. Spread the load.",("Four domains minimum.",),"onedomain"),
   ("MISTAKE 4",("Volume spikes","kill overnight."),"60 then 60 then 60 beats 0 then 500. Ramps live, blasts die.",("Boring wins inboxes.",),"spike"),
   ("MISTAKE 5",("Catch-all lists","drag everyone down."),"Unverified addresses poison the batch for the verified ones.",("Verify or pay.",),"catchall"),
   ("ULTRON",("The infra runs","by default."),"Warm domains, ramped sends, watched spam rates. You never think about it.",("99.2% inboxed.",),"infra"),
   ("THE LESSON",("Fix the road,","then the car."),"Great copy on dead infra is a love letter in a locked mailbox.",("Infra first, always.",),"road"),
  ]),
]
BATCH4=[
 dict(slug="twohours", title="ONE IDEA, TWO HOURS", accent=(204,120,92), mark="claude", pill="founder",
  cover=("Idea at 14:00.","Business live at 16:00."),
  close=("Save this timeline","and pick your idea.","What would you build in two hours?"),
  slides=[
   ("14:00",("One sentence.","The idea goes in."),"A service for founders who hate bookkeeping. That was the entire input.",("No deck, no plan.",),"input"),
   ("14:20",("The offer","stands up."),"Positioning, price, guarantee: drafted against the niche, not a template.",("Offer before logo.",),"offer"),
   ("14:50",("The page","goes live."),"Crescendo assembles hero, pricing and FAQ from the pack, in brand tokens.",("Preview, tap, live.",),"page"),
   ("15:10",("The content plan","lands."),"14 slots, three hooks per post, queued at 10:00 local.",("Distribution included.",),"plan"),
   ("15:30",("The outreach","waits at the gate."),"Twenty openers, one trigger each, parked for your tap.",("Nothing sent alone.",),"outreach"),
   ("16:00",("You review.","It ships."),"Offer, page, plan, script: two hours, one operator, zero meetings.",("Your tap, then live.",),"review"),
   ("16:01",("The excuse","died here."),"No team, no budget, no time: none of the three survived the afternoon.",("Excuses need effort now.",),"excuse"),
   ("THE MOAT",("Speed is the moat.","The gate keeps it safe."),"Idea to live while others plan. Feedback to fix within the hour.",("Move first, gated.",),"moat"),
  ]),
 dict(slug="salesorg", title="A SALES ORG, NOT A BOT", accent=(200,70,35), mark="claude", pill="operator",
  cover=("Your sales bot failed","because nobody was in charge."),
  close=("Save the org chart","before you build a bot.","Which desk do you need first?"),
  slides=[
   ("THE TRAP",("One agent doing all","does nothing well."),"The mega-automation collapses under its own hundred branches.",("Complexity is not power.",),"everything"),
   ("THE FIX",("Real teams","have structure."),"Chief, desks, specialists. Sales worked this way for a century for a reason.",("Copy what works.",),"structure"),
   ("DESK 1",("Research:","prospect intel."),"CORTEX profiles, scores and briefs before anyone writes a word.",("Intel first.",),"research"),
   ("DESK 2",("Outreach:","gated sends."),"SPECTER drafts per channel; every send parks for your tap.",("Volume with brakes.",),"outreach"),
   ("DESK 3",("Enablement:","paperwork, done."),"Proposals, scheduling, follow-ups: the work nobody loves, on time.",("No dropped balls.",),"enable"),
   ("DESK 4",("RevOps:","the pipe stays true."),"Stages move on replies, data stays clean, digests land daily.",("Truth in the CRM.",),"revops"),
   ("THE RULE",("One job per agent,","done extremely well."),"That is a workforce, not a chatbot with a hundred to-dos.",("Specialists win.",),"onejob"),
   ("THE CHIEF",("You sit on top.","One tap a day."),"The org runs; you approve. Hierarchy with a human at the head.",("Chief, not operator.",),"chief"),
  ]),
 dict(slug="adsagency", title="THE AD DESK, IN-HOUSE", accent=(212,162,127), mark="claude", pill="operator",
  cover=("I fired my ad agency.","A chat window replaced it."),
  close=("Save the ad desk,","cancel the retainer.","Which check would save you most?"),
  slides=[
   ("THE RETAINER",("It bought slides","and delays."),"Research, copy, audits: billed monthly, delivered quarterly.",("That bill ends here.",),"retainer"),
   ("MONDAY",("Rival ads,","diffed weekly."),"Every new creative your competitors launched, in one report.",("You see their moves.",),"spy"),
   ("THE GAP",("The empty angle","is found for you."),"Hooks ranked by frequency; the angles nobody covers become yours.",("Attack the gap.",),"gap"),
   ("THE DRAFTS",("Twenty variations","from one description."),"Short, medium, long: in your voice, against your brand rules.",("A week of copy, instantly.",),"variations"),
   ("THE AUDIT",("186 checks","before budget moves."),"Fatigue, overlap, anomalies: a health score with a fix list attached.",("Audit, then spend.",),"audit"),
   ("THE SCORE",("Any ad, scored","before it spends."),"Six dimensions; weak hooks get rewritten, not launched.",("No gut launches.",),"score"),
   ("THE CHAIN",("The retainer month,","in one morning."),"Spy, gap, draft, audit, score: chained, under an hour.",("Monday ritual.",),"chain"),
   ("THE SIGNATURE",("Every launch","signs with your tap."),"Nothing spends without you. In-house means in your hands.",("Your call, always.",),"sign"),
  ]),
 dict(slug="million", title="THE ONE-LAPTOP COMPANY", accent=(204,120,92), mark="claude", pill="founder",
  cover=("Your next competitor","has no employees."),
  close=("Save this thesis,","then start tonight.","Could you run it alone?"),
  slides=[
   ("THE SHAPE",("Not a funded startup.","Not a team of 20."),"A laptop, a subscription measured in cents, systems that do not sleep.",("New shape of company.",),"notteam"),
   ("THE SPLIT",("The agents work.","The founder decides."),"Research, outreach, content, builds: parallel, gated by one tap.",("Judgement is the job.",),"agents"),
   ("THE CURVE",("Revenue compounds.","Headcount stays 1."),"Up 32% this month; payroll unchanged since day zero.",("The lines diverge.",),"revenue"),
   ("THE MOAT",("Speed beats size","every quarter now."),"Idea to live offer in an afternoon. Feedback to fix in an hour.",("Size became drag.",),"speed"),
   ("THE COSTS",("The meter runs cents.","The market pays full."),"Costs flat while output multiplies. That spread is the business.",("Margin by design.",),"costs"),
   ("THE CALENDAR",("Empty calendar.","Full pipeline."),"No standups, no syncs. Digests at 07:00, decisions when you choose.",("Time became yours.",),"calendar"),
   ("THE CONTROL",("Every send gated.","Every risk yours."),"Autonomy scaled, control kept. That is the whole architecture.",("Power with a keel.",),"gated"),
   ("THE BET",("Someone builds this","this year."),"The only question left is whether it is you.",("Why not you.",),"you"),
  ]),
 dict(slug="zerostart", title="STARTING FROM ZERO, 2026", accent=(200,70,35), mark="claude", pill="builder",
  cover=("Do not learn to code.","Build the business instead."),
  close=("Save the zero plan","and pick the niche.","What would you start with?"),
  slides=[
   ("THE SHIFT",("The barrier moved.","It is not technical."),"Niche, distribution, consistency: the only three problems left.",("Everything else is solved.",),"barrier"),
   ("THE BUILD",("The build is","a sentence now."),"Describe the offer; Crescendo assembles the page from 822 parts.",("Live the same day.",),"build"),
   ("THE ENGINE",("The workflow runs","without you."),"Flows on triggers handle follow-up, delivery and reporting.",("Set exits, not alarms.",),"workflow"),
   ("THE NICHE",("Pick a problem","people already pay for."),"Boring niches, real invoices. The unglamorous print money.",("Boring is beautiful.",),"problem"),
   ("THE HABIT",("Show up daily.","The desk makes it cheap."),"14 posts planned from one line; your only job is to be real.",("Consistency, automated.",),"daily"),
   ("THE ODDS",("Most solo founders","hit profit in year one."),"Because the cost base is cents and the output is a team's.",("The math flipped.",),"profit"),
   ("THE FIRST TEN",("Ten customers,","ten handshakes."),"The machine sources and drafts; you close like a human.",("Humans buy from humans.",),"ten"),
   ("THE DEED",("Zero code. One gate.","All yours."),"Build, run, approve. The stack finally fits one person.",("Ownership, complete.",),"yours"),
  ]),
]

BATCH5=[
 dict(slug="diytrap", title="THE BUILD-IT-YOURSELF TRAP", accent=(204,120,92), mark="claude", pill="builder",
  cover=("I built an agent from scratch.","Installing took 10 minutes."),
  close=("Save the comparison","before you open the tutorial.","Would you build or install?"),
  slides=[
   ("THE TUTORIAL",("Ten slides in,","you are an engineer."),"Frameworks, graphs, state machines, control flow. The tutorial forgot you run a company.",("You wanted leverage, not a job.",),"recipe"),
   ("THE WIRING",("Plan, act, observe.","You wire every arrow."),"The loop the tutorials teach is real. Wiring it yourself is three weekends.",("The diagram is the easy part.",),"wiring"),
   ("THE REALITY",("It breaks the week","you stop watching."),"Edge cases, silent failures, no gate on sends. DIY agents fail in private.",("Nobody audits your graph.",),"breaks"),
   ("THE BILL",("The hours went in.","The leads did not come out."),"Every weekend on plumbing is a weekend not selling. That is the real invoice.",("Opportunity cost compounds.",),"bill"),
   ("THE INSTALL",("Seven agents,","already wired."),"CORTEX, SPECTER, STRIKER and the rest: built, tested, composing with each other.",("Ten minutes to first run.",),"install"),
   ("THE DIFFERENCE",("Their loop is a demo.","This one is audited."),"Every cycle checks its own work, every external send parks for your tap.",("Power with a keel.",),"audited"),
   ("THE FIRST RUN",("One sentence in.","Twenty briefs out."),"Source my next twenty accounts: typed at 09:14, briefed by 09:23.",("That was minute ten.",),"firstrun"),
   ("THE VERDICT",("Build your product.","Not your plumbing."),"The company wins on offers and distribution, not on hand-wired graphs.",("Leverage, not homework.",),"verdict"),
  ]),
 dict(slug="anatomy", title="ONE LOOP, HOUR BY HOUR", accent=(200,70,35), mark="claude", pill="operator",
  cover=("A prompt is one guess.","A loop finishes the job."),
  close=("Save the anatomy","and set your first loop.","What would you put on repeat?"),
  slides=[
   ("09:00",("The trigger fires.","Nobody typed anything."),"Three leads went quiet for three days. The follow-up loop wakes itself up.",("Set once, weeks ago.",),"trigger"),
   ("09:01",("It reads the thread","before it writes a word."),"Last reply, the objection, your pricing rules: loaded from memory, not pasted.",("Context first, always.",),"reads"),
   ("09:03",("Draft one.","It grades itself: 71."),"Too long, weak trigger line. The loop does not ask you. It redoes.",("Your bar, applied.",),"draft1"),
   ("09:06",("Draft three scores 90.","Now it stops."),"Exit condition met. Not tired, not lazy, not hopeful. Verified.",("Loops end on proof.",),"draft3"),
   ("09:07",("Three sends,","parked at the gate."),"The loop is autonomous inside. Outside, it waits for one tap from you.",("Nothing leaves alone.",),"parked"),
   ("09:40",("You tap twice,","kill one."),"Ten seconds of judgement on top of forty minutes of machine work.",("That is the whole job now.",),"tap"),
   ("14:20",("A reply lands.","The loop already logged it."),"Pipeline moved, next follow-up scheduled, digest updated for 07:00.",("It closes its own circle.",),"reply"),
   ("THE POINT",("One guess versus","a finished job."),"A prompt gives you words. A loop gives you outcomes with receipts.",("Put one thing on repeat.",),"point"),
  ]),
 dict(slug="mintskills", title="MINT YOUR OWN SKILLS", accent=(212,162,127), mark="claude", pill="builder",
  cover=("Stop downloading skills.","Start minting your own."),
  close=("Save the minting steps","and cast your first one.","Which workflow would you mint?"),
  slides=[
   ("THE ADMISSION",("Building agents","was the wrong move."),"Even Anthropic says it now: the unit of leverage is the skill, not the mega-agent.",("Smaller is the fix.",),"admission"),
   ("THE STACK",("Five folders.","One SKILL file."),"That is the entire anatomy of a skill. No graphs, no framework, no PhD.",("Small enough to own.",),"folders"),
   ("THE ORE",("Your best workflow","is the raw material."),"The proposal you always write the same way. The audit you repeat monthly.",("You already have it.",),"ore"),
   ("THE MINT",("Discover. Scaffold.","Distill. Audit."),"Four passes and the workflow becomes a command anyone on your desk can run.",("Ten minutes flat.",),"mint"),
   ("THE VOICE",("A downloaded skill","writes like everyone."),"A minted one carries your rules, your no-list, your phrasing. Unfair by design.",("Yours cannot be copied.",),"voice"),
   ("THE SHELF",("Six skills minted","from my own desk."),"Proposal, audit, brief, pricing, follow-up, report: each one born from a repeated job.",("My playbook, executable.",),"shelf"),
   ("THE COMPOUND",("Every correction","hardens the skill."),"Fix it once, the skill remembers forever. Month three runs sharper than month one.",("Assets, not chores.",),"compound"),
   ("THE SHIFT",("Downloaders collect.","Minters compound."),"The library you make beats the library you save.",("Cast the first one tonight.",),"shift"),
  ]),
 dict(slug="freestack", title="THE PRICE OF FULL PRICE", accent=(204,120,92), mark="strip", pill="founder",
  cover=("You pay full price","for tools that exist free."),
  close=("Save this before","your next renewal.","Which bill would you kill first?"),
  slides=[
   ("THE TERMINAL",("One desk pays yearly","what a clone gives free."),"The Bloomberg-style terminal has an open twin at zero. Same charts, same data feeds.",("The gap is knowledge.",),"terminal"),
   ("THE AUDIT",("Agencies bill monthly","for a script that runs daily."),"Ad audits, inbox triage, model routers: open versions exist for all of them.",("You fund their margin.",),"agencyfee"),
   ("THE CATCH",("Free tools are free","like a puppy is free."),"Setup, updates, breakage, no gate, no memory. Assembly is the hidden invoice.",("Someone pays in weekends.",),"catch"),
   ("THE GLUE",("Ten free tools","is eleven new jobs."),"Each one alone, logged out, forgetting you. The glue between them is the product.",("Nobody ships the glue.",),"glue"),
   ("THE LAYER",("One operator layer","over the whole stack."),"Ultron wires mail, docs, CRM and payments into one desk with one memory.",("Assembled, not collected.",),"layer"),
   ("THE METER",("The meter runs cents.","The retainers ran monthly."),"Pay per run, not per seat, not per logo. High bills only live in the old stack.",("Cents, by design.",),"meter"),
   ("THE KEEP",("Keep the free gems.","Wire them, gated."),"Open tools plug into the desk; every external action still parks for your tap.",("Best of both, one gate.",),"keep"),
   ("THE MATH",("Knowledge is the discount.","Assembly is the price."),"Know the free twin, pay only for the layer that runs it while you sleep.",("That spread is yours.",),"math"),
  ]),
 dict(slug="no120", title="DELETE THE PROMPT LIBRARY", accent=(200,70,35), mark="claude", pill="operator",
  cover=("Delete your prompt library.","Install 12 skills instead."),
  close=("Save this and","empty the notebook.","How many saved prompts do you own?"),
  slides=[
   ("THE HOARD",("120 saved prompts.","You reopened four."),"The cheat sheet felt like leverage. It is a filing cabinet you never visit.",("Saving is not a system.",),"hoard"),
   ("THE ROT",("Prompts rot","the week models change."),"Copy-paste magic words decay. Skills get maintained, versioned, corrected.",("One survives updates.",),"rot"),
   ("THE RETYPE",("Every use costs","a fresh re-wording."),"Paste, tweak, hope. The 120 need YOU every single time they run.",("That is the tell.",),"retype"),
   ("THE TWELVE",("Twelve installed skills","cover the 120."),"Brief, draft, audit, price, follow up, report: one command each, same play every run.",("Compression is power.",),"twelve"),
   ("ONE LINE",("The whole prompt","became /audit my funnel."),"A page of instructions lives inside the skill now. You type five words.",("The page is installed.",),"oneline"),
   ("THE RUNS",("Skills run without you.","Prompts wait for you."),"On triggers, on schedules, overnight: a skill fires itself. A prompt never will.",("That gap is everything.",),"runs"),
   ("THE GATE",("Autonomous inside.","Your tap outside."),"Skills execute and compose, and every external send still parks for you.",("Speed with a keel.",),"gate"),
   ("THE PURGE",("I deleted mine","in one afternoon."),"Kept zero prompts, minted twelve skills. The notebook is empty and the desk is full.",("Empty yours tonight.",),"purge"),
  ]),
]

BATCH6=[
 dict(slug="modelwars", title="THE MODEL OF THE WEEK", accent=(212,162,127), mark="claude", pill="founder",
  cover=("A new model drops weekly.","Your system should not care."),
  close=("Save this before","the next launch thread.","Which model panic did you buy?"),
  slides=[
   ("THE CYCLE",("Every Tuesday,","a new king is crowned."),"A benchmark, a hype thread, a migration guide. By Friday there is another one.",("You cannot build on a carousel.",),"cycle"),
   ("THE SWITCHERS",("They moved stacks","four times this year."),"Each move: new quirks, new prompts, new bugs. Their pipeline never noticed a difference.",("Motion, not progress.",),"switchers"),
   ("THE TRUTH",("Models converged.","Systems did not."),"The top models are within points of each other. The gap is everything wrapped around them.",("The wrapper is the moat.",),"truth"),
   ("THE ROUTER",("One goal in,","the right tier picked."),"Lite for lookups, Smart for the daily work, Deep for judgement. Chosen per turn, not per hype.",("You never pick a model again.",),"router"),
   ("THE ASSETS",("Memory, skills, gate:","none of them expire."),"Your ICP, your voice, your rules survive every model release untouched.",("Launches cannot erase them.",),"assets"),
   ("THE UPGRADE",("New model lands,","your desk just improves."),"The router adopts it under the hood. Same commands, same memory, better engine.",("Zero migration, ever.",),"upgrade"),
   ("THE COST",("Chasing models is","a part-time job."),"Reinstalling, re-prompting, re-learning: hours that never touch revenue.",("Hype is expensive.",),"cost"),
   ("THE POSITION",("Own the layer","above the models."),"Let them fight. Whoever wins, your system gets stronger the same afternoon.",("That is the only safe seat.",),"position"),
  ]),
 dict(slug="dayone", title="DAY ONE: THE FIVE PLAYS", accent=(204,120,92), mark="claude", pill="builder",
  cover=("Day one with Claude:","run these five plays."),
  close=("Save the five plays","for your first hour.","Which play do you run first?"),
  slides=[
   ("PLAY 1",("Teach it your business","before you ask anything."),"/init: one interview, ICP, offer, pricing, no-list. Ten minutes that change every answer after.",("Context beats clever prompts.",),"teach"),
   ("PLAY 2",("Make it read","before it speaks."),"First research run: twenty accounts profiled and scored against YOUR customer, not averages.",("Warm beats generic.",),"read"),
   ("PLAY 3",("Feed it your voice,","not your instructions."),"Paste your five best posts. Every draft after sounds like you on a good day.",("Voice is set once.",),"voice"),
   ("PLAY 4",("Put one chore","on a trigger."),"Follow up every quiet lead: typed once, runs daily, exits set, sends parked.",("Your first employee-shaped flow.",),"chore"),
   ("PLAY 5",("End the day","with a digest."),"Everything it did, everything it wants approved, tomorrow queued: one page at 07:00.",("You read, tap, done.",),"digest"),
   ("THE HOUR",("Five plays,","sixty minutes total."),"Not a course, not a certification. One hour of setup on the Ultron desk.",("Beginner is a choice.",),"hour"),
   ("THE TRAP",("Skipping play one","breaks the other four."),"Generic context makes generic outputs. Every disappointment traces back here.",("Do not skip the interview.",),"trap"),
   ("THE CURVE",("Day one is the floor.","It only compounds."),"Corrections become rules, rules become skills, the desk gets sharper weekly.",("Start the clock.",),"curve"),
  ]),
 dict(slug="neverhire", title="THE HIRING FREEZE", accent=(200,70,35), mark="claude", pill="founder",
  cover=("I froze five job openings.","The desk absorbed them."),
  close=("Save the freeze list","before your next posting.","Which role would you freeze first?"),
  slides=[
   ("ROLE 1",("Lead generation:","frozen."),"Sourcing, scoring, briefing: CORTEX runs it overnight on your ICP, every day.",("The intern became a flow.",),"leadgen"),
   ("ROLE 2",("Support triage:","frozen."),"Inbox read, sorted, drafted. The rare hard case escalates to you with context attached.",("First reply in seconds.",),"support"),
   ("ROLE 3",("Content ops:","frozen."),"Fourteen slots planned from one line, drafts in your voice, queued at 10:00 local.",("The desk never misses Monday.",),"content"),
   ("ROLE 4",("Sales follow-ups:","frozen."),"Every quiet thread chased on a trigger, every send parked for your tap.",("Nothing slips, nothing sent alone.",),"followups"),
   ("ROLE 5",("Review collection:","frozen."),"Asked at the right moment, chased politely, logged where you see it.",("The quiet growth lever.",),"reviews"),
   ("THE MATH",("Five salaries stayed","in the company."),"The fastest growing companies are not working more. They run systems that work around the clock.",("Systems, not headcount.",),"math"),
   ("THE LINE",("Freeze the repetitive.","Hire the judgement."),"People for taste, relationships and calls. Flows for everything that repeats.",("That is the split.",),"line"),
   ("THE TEST",("Would a checklist","do this job?"),"If yes, it is a flow, not a hire. Run the test before every job posting.",("Post fewer jobs, ship more.",),"test"),
  ]),
 dict(slug="boring", title="BORING BEATS CLEVER", accent=(204,120,92), mark="claude", pill="operator",
  cover=("Clever got 800 views.","Boring got 47,000."),
  close=("Save the 4-second test","and run it on your next post.","Are you writing for the scroll?"),
  slides=[
   ("THE WINDOW",("You get 1.7 seconds.","Nobody is reading."),"They are scrolling. The brain picks safe and predictable over smart and subtle, every time.",("Confusion kills reach.",),"window"),
   ("THE PROOF",("Same idea, two posts,","one week apart."),"The clever version optimised asymmetric distribution. The boring one said: post daily for 30 days.",("800 versus 47,000.",),"proof"),
   ("THE RULES",("One idea per post.","Payoff in two seconds."),"Words a 12-year-old gets, a format the feed already knows. That is the whole religion.",("Boring is a discipline.",),"rules"),
   ("THE EGO",("Clever is for you.","Boring is for them."),"Sounding smart is a founder vanity metric. Being understood is a growth metric.",("Kill the vanity.",),"ego"),
   ("THE TEST",("Four boxes","before every post."),"Point lands in 2 seconds? One idea only? Your dad gets it? Format familiar?",("Fail one, rewrite.",),"fourtest"),
   ("THE SKILL",("My desk runs the test","before I ever see a draft."),"PULSE drafts to the boring rules: one idea, plain words, visible payoff. Ranked before review.",("Discipline, automated.",),"skill"),
   ("THE CLIENT",("One trader switched.","2K to 30K in 25 days."),"Same expertise, same niche. One trade idea per post instead of technical essays.",("Boring delivery, expert core.",),"client"),
   ("THE REFRAME",("Boring does not mean","low value."),"It means legible at scroll speed. The smartest content looks the simplest.",("Simple is the flex.",),"reframe"),
  ]),
 dict(slug="loweffort", title="LOW EFFORT, DONE RIGHT", accent=(212,162,127), mark="strip", pill="operator",
  cover=("Low effort content works.","Just not the guru way."),
  close=("Save the honest version","of low effort.","Where does your effort actually go?"),
  slides=[
   ("THE PITCH",("The gurus sell","effortless posting."),"Faceless clips, recycled quotes, ten minutes a day. The feed is drowning in it.",("And the feed ignores it.",),"pitch"),
   ("THE CATCH",("Zero effort in","reads as zero value out."),"Audiences smell templates. Recycled content gets recycled reach.",("The shortcut is the ceiling.",),"catchg"),
   ("THE REFRAME",("Low effort is an","output, not an input."),"The posting should be light. The system behind it should be heavy.",("Move the effort upstream.",),"reframe2"),
   ("THE HEAVY",("Build once:","voice, bank, cadence."),"Your voice sampled, your hook bank stocked, your calendar wired. That is the real work.",("One weekend, honestly spent.",),"heavy"),
   ("THE LIGHT",("Then daily is","one line and one tap."),"The desk plans, drafts to your bar, queues at 10:00. You approve on your phone.",("Ten minutes, for real now.",),"light"),
   ("THE DIFFERENCE",("Guru low effort skips work.","System low effort front-loads it."),"Same daily minutes, opposite outcomes. The system version compounds.",("Effort moved, not removed.",),"difference"),
   ("THE RECEIPTS",("Fourteen posts a week","from one planning line."),"In my voice, on my niche, each one passing the boring test before I see it.",("Light hands, heavy system.",),"receipts"),
   ("THE VERDICT",("Work hard once.","Post easy forever."),"That is the honest version of low effort. Everything else is a template farm.",("Front-load, then fly.",),"verdictl"),
  ]),
]

BATCH7=[
 dict(slug="wrongaisle", title="THE WRONG PLUGIN AISLE", accent=(204,120,92), mark="claude", pill="builder",
  cover=("You installed developer toys.","Your pipeline noticed nothing."),
  close=("Save this before","your next install spree.","Which aisle are you shopping in?"),
  slides=[
   ("THE AISLE",("The plugin lists are","written for engineers."),"Repo mappers, knowledge graphs, code navigators. Impressive, and irrelevant to your quarter.",("Wrong aisle for a founder.",),"aisle"),
   ("THE TELL",("Cool demo,","zero revenue path."),"If you cannot name the deal it moves or the hour it saves, it is a toy.",("Name it or skip it.",),"tell"),
   ("THE FLIP",("Founder plugins","are desks, not tools."),"Research, outbound, deals, content, legal: each install owns an outcome.",("Outcomes, not extensions.",),"flip"),
   ("DESK CHECK",("Every plugin answers","one question:"),"What lands in the pipeline because this exists? CORTEX: briefs. SPECTER: replies. STRIKER: closes.",("One job, named.",),"deskcheck"),
   ("THE STACK",("Five desks cover","a founder company."),"Intel, outreach, deals, content, paperwork. The sixth is you, on the gate.",("That is the whole aisle.",),"stackp"),
   ("THE TEST RUN",("Install, then demand","a receipt in 48 hours."),"Twenty briefs, ten drafts, one proposal out. No receipt, uninstall.",("Plugins earn their slot.",),"testrun"),
   ("THE TRAP",("Ten dev plugins deep,","still drafting alone."),"The graph mapper cannot write your follow-up. The desk can.",("Tools do not sell.",),"trapb"),
   ("THE RULE",("Shop by outcome,","never by demo."),"If the plugin page shows code, you are in the wrong aisle. If it shows pipeline, install.",("Buy desks. Skip toys.",),"rule7"),
  ]),
 dict(slug="selflearn", title="AGENTS THAT LEARN", accent=(200,70,35), mark="claude", pill="builder",
  cover=("Most agents forget everything.","Mine files the lesson."),
  close=("Save the learning loop","and stop repeating yourself.","What has yours learned this month?"),
  slides=[
   ("THE AMNESIA",("Same mistakes.","Every single run."),"A task finishes, the context dies, tomorrow starts from zero. That is most agents today.",("Groundhog day, automated.",),"amnesia7"),
   ("THE TAX",("You correct the same error","for the fortieth time."),"Every repeated correction is payroll you pay in attention.",("Forgetting is expensive.",),"tax"),
   ("THE LOOP",("Evaluate. Reflect.","Store. Apply."),"The self-improving loop: the agent grades its output, writes the lesson, uses it next run.",("Sharper every cycle.",),"looplearn"),
   ("THE FILE",("Corrections become rules.","Rules become skills."),"Say no discounts once: blocked forever. Fix a draft once: the fix generalizes.",("Your feedback compounds.",),"file7"),
   ("THE CURVE",("Run one is average.","Run one hundred is yours."),"The same flow, months later, writes like you, prices like you, filters like you.",("Time turns it native.",),"curve7"),
   ("THE PROOF",("My no-list has 34 rules.","I wrote none of them twice."),"Each one came from a single correction that never needed repeating.",("Said once, kept forever.",),"proof7"),
   ("THE GATE",("It learns alone.","It still sends with you."),"Self-improvement stays internal; every external move parks for your tap.",("Smarter, not looser.",),"gate7"),
   ("THE QUESTION",("If it cannot remember you,","why are you training it daily?"),"Demand memory before you demand intelligence.",("Memory first. Always.",),"question7"),
  ]),
 dict(slug="carouselcode", title="THE CAROUSEL CODE", accent=(212,162,127), mark="claude", pill="operator",
  cover=("Eight months of carousels.","The patterns finally cracked."),
  close=("Save the code","and grade your last post.","Which pattern were you missing?"),
  slides=[
   ("THE MYTH",("It was never","the pretty template."),"Eight months of posting proved it: sophistication and polish did not move a single metric.",("Patterns move metrics.",),"myth7"),
   ("PATTERN 1",("The cover sells","the swipe, nothing else."),"One promise, one visual, zero cleverness. Its only job is the next slide.",("Covers are doormen.",),"pat1"),
   ("PATTERN 2",("One beat per page.","Cut everything else."),"Two ideas on a slide is one idea too many. The swipe rhythm is the retention.",("Rhythm beats density.",),"pat2"),
   ("PATTERN 3",("Slide two decides","if they finish."),"The swipe-off page carries the tension: open a loop the last page closes.",("Hook them twice.",),"pat3"),
   ("PATTERN 4",("The save happens","on the reference page."),"One page they will need again: the list, the test, the map. Saves are the algorithm.",("Build the save page in.",),"pat4"),
   ("THE GRADE",("I review posts","against the code now."),"Cover promise, beat rhythm, loop tension, save page, one CTA. Five boxes, thirty seconds.",("Growth became a checklist.",),"grade7"),
   ("THE DESK",("PULSE builds to the code","by default."),"Every deck it drafts carries the five patterns before I ever see it.",("The code, automated.",),"desk7"),
   ("THE PAYOFF",("Growth stopped being luck","and became a consequence."),"Same niche, same effort, patterned delivery. The metrics followed.",("Consequence, not lottery.",),"payoff7"),
  ]),
 dict(slug="onetool", title="FIVE ASSISTANTS, NO MEMORY", accent=(204,120,92), mark="strip", pill="founder",
  cover=("You do not need five assistants.","You need one that remembers."),
  close=("Save this before","you add tool number six.","How many assistants do you juggle?"),
  slides=[
   ("THE LIST",("Inbox tool, calendar tool,","meeting tool, note tool."),"The listicles sell you a specialist for every slice of your day.",("Five logins, five bills.",),"list7"),
   ("THE SEAMS",("None of them","know the others exist."),"The inbox tool cannot see the deal. The meeting tool never met your pipeline.",("You are the integration.",),"seams"),
   ("THE COST",("Five memories","means no memory."),"Your context lives nowhere, so you re-explain yourself to software all day.",("Amnesia at scale.",),"cost7"),
   ("THE DESK",("One desk holds","inbox, calendar, pipeline."),"Mail read, meetings booked, follow-ups drafted: one memory underneath all of it.",("One brain, many hands.",),"desk7b"),
   ("THE COMPOUND",("Tool five forgets you.","The desk knows the thread."),"The follow-up references the call, the call references the deal, the deal references the history.",("Context is the feature.",),"compound7"),
   ("THE SLEEP",("It clears the inbox","while you sleep."),"Triage at 23:00, drafts by 06:00, digest at 07:00. In your voice, parked for your tap.",("The night shift, unified.",),"sleep7"),
   ("THE PRICE",("Five subscriptions","became one meter."),"Cents per run instead of a stack of seats.",("The math got simple.",),"price7"),
   ("THE RULE",("Never add a tool","that cannot share memory."),"That single filter kills most of the listicle.",("Memory or nothing.",),"rule7b"),
  ]),
 dict(slug="oneskill", title="ONE SKILL, FIVE INCOMES", accent=(200,70,35), mark="claude", pill="founder",
  cover=("You do not need a new skill.","You need five shapes of it."),
  close=("Save the five shapes","and pick your second one.","Which shape is your skill missing?"),
  slides=[
   ("THE MYTH",("Everyone hunts","a new skill."),"The money was in the one you already have, reshaped five ways.",("Look again, differently.",),"mythos"),
   ("SHAPE 1",("The service:","done for them."),"Your skill, applied to their business. The desk handles briefs, delivery and chasing.",("Highest price, first cash.",),"service"),
   ("SHAPE 2",("The product:","packaged once."),"Templates, audits, systems from your own workflow, assembled and delivered automatically.",("Sell while you sleep.",),"product"),
   ("SHAPE 3",("The content:","proof in public."),"The desk turns your client work into daily posts in your voice. Content sells shapes one and two.",("The flywheel spins here.",),"contents"),
   ("SHAPE 4",("The teaching:","the method, priced."),"Your process, structured into a course or cohort by the same desk that runs it.",("Expertise, multiplied.",),"teaching"),
   ("SHAPE 5",("The tool:","your method, executable."),"Mint the workflow as a skill others run. No code, just your judgement packaged.",("The 2026 shape.",),"tool5"),
   ("THE ENGINE",("One desk runs","all five shapes."),"Same memory, same voice, same gate: service, product, content, teaching, tool.",("Five incomes, one login.",),"engine5"),
   ("THE ORDER",("Service first.","Tool last."),"Cash from shape one funds the rest; each shape feeds the next.",("Sequence beats ambition.",),"order5"),
  ]),
]

BATCH8=[
 dict(slug="firstpass", title="FIRST PASS, HUMAN FINISH", accent=(204,120,92), mark="claude", pill="operator",
  cover=("The desk does the first pass.","Your taste does the rest."),
  close=("Save the split","and audit your week with it.","Where does your first pass go?"),
  slides=[
   ("THE CHATBOX",("Most people run a team","like a chat box."),"One prompt at a time, one person typing, nine roles unfilled.",("Wire it like an org chart.",),"chatbox"),
   ("THE ROSTER",("Researcher, editor,","analyst, deck builder."),"Ten roles, each an installed skill with a real job, not a prompt with a nickname.",("An org chart, not a toy.",),"roster"),
   ("THE SPLIT",("It drafts.","You decide."),"The first pass is volume work: reading, sorting, drafting. The finish is judgement.",("Machines pass, humans finish.",),"split8"),
   ("THE MORNING",("Nine first passes","waiting at 07:00."),"Briefs read, drafts ranked, deck skeletons built. Your day starts at the decision layer.",("You skipped the grind layer.",),"morning"),
   ("THE CRAFT",("Your team stops producing","and starts directing."),"Editors edit taste, not typos. Analysts read meaning, not spreadsheets.",("Everyone moves up one level.",),"craft"),
   ("THE SKILL MAKER",("One skill on the roster","builds new skills."),"Spot a repeated job, mint it into the org chart by Friday.",("The team grows itself.",),"skillmaker"),
   ("THE LINE",("Nothing external ships","without a human finish."),"First passes run free inside. The last touch is always yours.",("That line never moves.",),"line8"),
   ("THE RESULT",("Same headcount.","Triple the throughput."),"Not replacement: elevation. The work everyone hated does itself now.",("First pass, solved.",),"result8"),
  ]),
 dict(slug="studyyou", title="IT STUDIED MY BEST POSTS", accent=(200,70,35), mark="claude", pill="operator",
  cover=("It studied my 50 best posts.","Then it wrote the 51st."),
  close=("Save the self-study loop","and feed it your archive.","Which post should it study first?"),
  slides=[
   ("THE ARCHIVE",("Your best posts are","training data you own."),"Fifty posts that already worked, sitting unused in your profile.",("The goldmine is behind you.",),"archive"),
   ("THE EXTRACT",("Pull them all.","Every winner, dated."),"The desk collects your top posts with their numbers attached.",("Receipts, not memories.",),"extract"),
   ("THE AUTOPSY",("What actually worked","was not what I thought."),"Short openers, one number per post, questions that end. The data disagreed with my taste.",("Patterns beat opinions.",),"autopsy"),
   ("THE DISTILL",("The findings became","a reusable skill."),"Not notes, not a doc: an installed play the desk runs on every future draft.",("Insight, made executable.",),"distill"),
   ("THE 51ST",("The next post came out","sounding like my best day."),"Drafted against my own winning patterns, ranked before I saw it.",("Me, on repeat.",),"fifty1"),
   ("THE REFRESH",("Every month,","the study reruns."),"New winners join the corpus; the skill updates itself with fresh patterns.",("The bar keeps moving up.",),"refresh"),
   ("THE MOAT",("Nobody can copy","your archive."),"Generic AI writes averages. This writes from evidence only you own.",("Your history is the moat.",),"moat8"),
   ("THE ORDER",("Study first.","Generate second."),"Most people ask AI to write. Operators make it learn, then write.",("Reverse the order.",),"order8"),
  ]),
 dict(slug="proofstack", title="BUILDS THAT PAY RENT", accent=(212,162,127), mark="claude", pill="builder",
  cover=("Stop building portfolio pieces.","Build things that invoice."),
  close=("Save the three builds","and ship the first one.","Which build pays your rent first?"),
  slides=[
   ("THE TRAP",("Demo projects impress.","They do not deposit."),"Tutorial agents and portfolio repos collect stars, not revenue.",("Recruiters are not your market.",),"trapd"),
   ("BUILD 1",("The lead machine:","live in a weekend."),"Sources your ICP nightly, briefs every account, parks the openers for your tap.",("Pipeline while you sleep.",),"build1"),
   ("BUILD 2",("The follow-up loop:","zero dropped threads."),"Fires on silence, drafts on replies, logs everything to the pipe.",("Deals stop leaking.",),"build2"),
   ("BUILD 3",("The content desk:","proof in public, daily."),"Fourteen posts a week from one line, in your voice, gated.",("Distribution, automated.",),"build3"),
   ("THE STACK",("Three builds,","one memory, one gate."),"Each feeds the others: content warms leads, leads feed loops, loops close.",("A system, not a portfolio.",),"stack8"),
   ("THE RECEIPTS",("Every build reports","in money terms."),"Briefs became calls, threads became invoices, posts became inbound.",("Stars do not compound. This does.",),"receipts8"),
   ("THE TIME",("Each build is","an evening, not a semester."),"Described in plain English, assembled by the desk, tested on your real pipeline.",("Ship all three this week.",),"time8"),
   ("THE FILTER",("Would a client pay","for this build?"),"If not, it is a hobby. Hobbies are fine. Just label them honestly.",("Invoice or hobby. Choose.",),"filter8"),
  ]),
 dict(slug="tokendiet", title="THE CENTS DISCIPLINE", accent=(204,120,92), mark="claude", pill="builder",
  cover=("Your AI bill is a habit,","not a price."),
  close=("Save the discipline","before your next session.","Which habit is burning yours?"),
  slides=[
   ("THE LEAK",("The meter does not lie.","Habits inflate it."),"Same tool, same work: one founder pays cents, another pays multiples.",("The difference is discipline.",),"leak"),
   ("HABIT 1",("Clear the context","between tasks."),"Dragging yesterday into today makes every answer heavier and worse.",("Fresh task, fresh slate.",),"habit1"),
   ("HABIT 2",("Right tier,","right job."),"Light for lookups, standard for daily work, deep only where judgement pays.",("The router does this for you.",),"habit2"),
   ("HABIT 3",("Filter the noise","before it reads."),"Logs, dumps and threads get summarized first, not swallowed whole.",("Feed it signal, not bulk.",),"habit3"),
   ("HABIT 4",("Keep the memory files","short and sharp."),"A lean context file beats a bloated one on both cost and quality.",("Trim monthly.",),"habit4"),
   ("HABIT 5",("Batch the small stuff.","One run, ten items."),"Ten tiny asks cost more than one structured pass.",("Bundle, then fire.",),"habit5"),
   ("THE AUTOPILOT",("On the desk,","the discipline is default."),"The router tiers every turn, contexts reset per task, spend caps sit on every flow.",("Cents by design, not effort.",),"autopilot"),
   ("THE REFRAME",("Do not chase cheap.","Chase clean."),"The habits that cut cost are the same ones that raise quality.",("Discipline pays twice.",),"reframe8"),
  ]),
 dict(slug="brandguard", title="ON-BRAND WITHOUT A DESIGNER", accent=(200,70,35), mark="strip", pill="operator",
  cover=("Every asset on-brand.","No designer on payroll."),
  close=("Save the guardrail setup","and lock your look.","What does your brand drift on?"),
  slides=[
   ("THE DRIFT",("Ten posts,","ten shades of you."),"Without a designer, every asset negotiates its own fonts and colors.",("Drift reads as amateur.",),"drift"),
   ("THE TOKENS",("Your look, written down","once, as law."),"Colors, type, spacing, logo rules: one token file every asset obeys.",("Brand as configuration.",),"tokens"),
   ("THE PACK",("822 components","already on-brand."),"Cards, heroes, charts, covers: assembled from your pack, never from scratch.",("Consistency is prebuilt.",),"pack"),
   ("THE OUTPUTS",("Decks, pages, posts:","one family."),"The proposal matches the landing page matches the carousel.",("Everything rhymes.",),"outputs"),
   ("THE SPEED",("On-brand became","the fast path."),"No review cycles, no drift fixes: the guardrail makes the quick version the correct one.",("Fast and consistent, finally.",),"speed8"),
   ("THE GATE",("New asset types","get one approval."),"You bless the template once; every instance after inherits the blessing.",("Approve patterns, not pieces.",),"gate8"),
   ("THE COST",("The design retainer","became a token file."),"High bills live in the old workflow. This one is configuration.",("Paid once, in setup.",),"cost8"),
   ("THE TEST",("Screenshot any two assets.","Same company?"),"If a stranger cannot tell, the guardrail works.",("Run it on your last five.",),"test8"),
  ]),
]

BATCH9=[
 dict(slug="sellonce", title="CREATE ONCE, SELL FOREVER", accent=(204,120,92), mark="claude", pill="founder",
  cover=("You do not need 50 ideas.","You need one, shipped."),
  close=("Save the pipeline","and ship idea number one.","Which product have you been postponing?"),
  slides=[
   ("THE LIST TRAP",("Fifty ideas saved.","Zero products live."),"Idea lists feel like progress. Shipping is the only progress.",("Lists are procrastination.",),"listtrap"),
   ("THE PICK",("Sell what you already","get asked about."),"The template, the checklist, the audit you explain weekly: that is the product.",("Demand is already visible.",),"pick9"),
   ("THE BUILD",("Described in a sentence.","Assembled by the desk."),"Your workflow becomes the template pack, the guide, the system: from your own files.",("An evening, not a launch.",),"build9"),
   ("THE PAGE",("The offer page","went live the same day."),"Hero, pricing, FAQ from the component pack, in your brand tokens.",("No designer, no delay.",),"page9"),
   ("THE DELIVERY",("Paid at 03:14.","Delivered at 03:14."),"The flow sends the product, the receipt and the follow-up while you sleep.",("Inventory of nothing.",),"delivery"),
   ("THE LOOP9",("Feedback becomes","version two."),"Every buyer question funnels into the next update, drafted for your tap.",("The product self-improves.",),"loop9"),
   ("THE SPREAD",("One product funds","the second."),"Validate one niche, then let the desk clone the pipeline sideways.",("Library, not lottery.",),"spread"),
   ("THE MATH9",("Created once.","Sold while you slept."),"The digital shelf never closes and never reorders stock.",("Ship idea number one.",),"math9"),
  ]),
 dict(slug="starthere", title="THE PLATFORM WAS NEVER IT", accent=(200,70,35), mark="strip", pill="founder",
  cover=("45 websites to make money.","You needed a system, not a list."),
  close=("Save this instead","of another platform list.","Which platform are you blaming?"),
  slides=[
   ("THE LISTS",("Another 45 platforms.","Still no first dollar."),"Freelance sites, store builders, writing platforms: the doors were never locked.",("Access was never the issue.",),"lists9"),
   ("THE REAL GAP",("Platforms reward","systems, not signups."),"The winners on every list show up daily, respond fast, and follow up. That is it.",("Boring, repeated, paid.",),"gap9"),
   ("THE PROFILE",("Your profile is","an offer page."),"The desk drafts it like one: outcome, proof, one clear next step.",("Most read like resumes.",),"profile9"),
   ("THE RESPONSE",("First reply wins","on every platform."),"Briefs read, responses drafted in minutes, parked for your tap.",("Speed is the algorithm.",),"response9"),
   ("THE FOLLOW",("The money is in","reply number three."),"Quiet clients get chased on triggers; delivered work gets reviewed and re-pitched.",("Nobody does this part.",),"follow9"),
   ("THE PORTFOLIO",("Every delivery becomes","public proof."),"The desk turns finished work into posts and case notes automatically.",("The flywheel starts here.",),"portfolio9"),
   ("ONE PLATFORM",("Pick one door.","Run the system on it."),"One platform, thirty days, the full loop. Then and only then, add the second.",("Depth beats directory.",),"onedoor"),
   ("THE TRUTH9",("The list was free.","The discipline was not."),"45 websites, one differentiator: the operator behind the account.",("Be the operator.",),"truth9"),
  ]),
 dict(slug="fivetools", title="FIVE CLAUDES, ONE FOUNDER", accent=(212,162,127), mark="claude", pill="builder",
  cover=("You are using one Claude.","There are five."),
  close=("Save the map","and open the right door.","Which Claude have you never opened?"),
  slides=[
   ("DOOR 1",("Chat:","the fast answer."),"Quick questions, summaries, first drafts. Where everyone starts and most people stop.",("The lobby, not the building.",),"door1"),
   ("DOOR 2",("Projects:","the memory."),"Recurring workstreams with context that survives: reporting, client work, board prep.",("Stop re-explaining yourself.",),"door2"),
   ("DOOR 3",("Cowork:","the hands on files."),"Reads your folders, works your spreadsheets, drafts your reports where they live.",("Real files, real work.",),"door3"),
   ("DOOR 4",("Skills:","the repeatable plays."),"Your workflows installed as commands: same play, every run, no re-prompting.",("Where leverage lives.",),"door4"),
   ("DOOR 5",("Code:","the builder."),"Pages, dashboards, tools from plain English, tested and shipped.",("For outcomes, not engineers.",),"door5"),
   ("THE MISTAKE",("Using door one","for door four jobs."),"Re-typing a workflow into Chat weekly is a Skills job done badly.",("Match the door to the job.",),"mistake9"),
   ("THE DESK9",("Ultron wires all five","behind one composer."),"Type the goal; the router opens the right door and carries your memory through it.",("No door knowledge required.",),"desk9"),
   ("THE UNLOCK",("Non-technical was never","the barrier."),"Knowing which door exists is 80% of mastering the machine.",("Open door two tonight.",),"unlock9"),
  ]),
 dict(slug="direction", title="DIRECTION BEATS PROMPTS", accent=(204,120,92), mark="claude", pill="operator",
  cover=("Your AI is not weak.","It is undirected."),
  close=("Save the seven directions","and re-run your last ask.","Which direction were you missing?"),
  slides=[
   ("THE MISTAKE",("Everyone prompts.","Few direct."),"The biggest error is asking without direction: no audience, no tone, no goal attached.",("Direction is the skill.",),"mist10"),
   ("DIRECTION 1",("Give it the reader,","not the topic."),"Founders scanning at 1.7 seconds is a brief. Write about AI is a shrug.",("Audience first.",),"dir1"),
   ("DIRECTION 2",("Feed it your tone","from real samples."),"Five best posts in, voice locked, every draft yours.",("Tone is data, not adjectives.",),"dir2"),
   ("DIRECTION 3",("Demand hooks","in three shapes."),"Confession, number, enemy: pick the winner instead of accepting the first.",("Options beat outputs.",),"dir3"),
   ("DIRECTION 4",("One idea in,","five formats out."),"Post, carousel, reel script, caption, newsletter: the multiplication is free.",("Never one-and-done.",),"dir4"),
   ("DIRECTION 5",("Set the bar","before the draft."),"Your scoring rules go in the instructions, so ranking happens before you look.",("The desk grades itself.",),"dir5"),
   ("THE BURNOUT",("Consistency is a system,","not a mood."),"Planned slots, drafted queues, gated sends: showing up became automatic.",("The desk holds the streak.",),"burnout"),
   ("THE SHIFT9",("Stop prompting harder.","Start directing better."),"Same model, same cost: direction is the whole difference.",("Direct, then delegate.",),"shift9"),
  ]),
 dict(slug="skipcourse", title="SKIP THE COURSE", accent=(200,70,35), mark="claude", pill="builder",
  cover=("Mastery is not a course.","It is a hundred gated runs."),
  close=("Save the operator path","and run job one today.","What would your first real run be?"),
  slides=[
   ("THE PATH",("Prompting course, automation","course, coding course."),"The mastery ladder the feed sells you is three curriculums deep.",("You run a company, not a degree.",),"path9"),
   ("THE FLIP9",("Learn on your pipeline,","not on toy examples."),"Every lesson that matters comes from a real run on real work.",("Tuition: cents.",),"flip9"),
   ("RUN 1",("Ship one research job","end to end."),"Twenty accounts briefed teaches more than any prompt anatomy lecture.",("Lesson one: context.",),"run1"),
   ("RUN 10",("Correct it ten times.","Watch the rules stick."),"By run ten your no-list exists and the drafts stop disappointing.",("Lesson two: memory.",),"run10"),
   ("RUN 50",("Wire the triggers.","Stop initiating."),"The jobs fire themselves; you approve. This is the automation course, lived.",("Lesson three: exits.",),"run50"),
   ("RUN 100",("Mint your workflow","as a skill."),"The coding course you skipped becomes one command you own.",("Lesson four: leverage.",),"run100"),
   ("THE GATE9",("Every run is safe","to learn on."),"Nothing external ships without your tap, so mistakes stay internal.",("The classroom has a keel.",),"gate9"),
   ("THE DIPLOMA",("A hundred runs in,","the desk works like you."),"No certificate. Just a pipeline that moves and a system that remembers.",("That is mastery.",),"diploma"),
  ]),
]

BATCH10=[
 dict(slug="eyes", title="WIRE ITS EYES", accent=(212,162,127), mark="claude", pill="builder",
  cover=("Your AI is blind by default.","Wire its eyes."),
  close=("Save the wiring list","and give yours sight.","What is yours still blind to?"),
  slides=[
   ("THE JAR",("A brain in a jar","answers from memory."),"Out of the box it cannot see your market, your inbox or this morning's news.",("Smart and sightless.",),"jar"),
   ("THE EYES",("Search built for agents,","not for humans."),"Structured results instead of blue links: the difference between browsing and knowing.",("Sight is an install.",),"eyes10"),
   ("THE CRAWL",("Any website becomes","readable data."),"Competitor pages, pricing changes, job boards: crawled into briefs.",("The web is its territory.",),"crawl"),
   ("THE WATCH",("It monitors","while you operate."),"Rival launches, market moves, mention spikes: watched on triggers, reported in digests.",("Eyes that never blink.",),"watch"),
   ("THE PROOF10",("CORTEX reads 1,284","companies live."),"Hiring signals, funding news, stack changes: this morning's web, not last year's training.",("Fresh beats trained.",),"proof10"),
   ("THE DIFFERENCE",("Blind AI guesses.","Sighted AI cites."),"Every claim in every brief carries its source and its date.",("Receipts, attached.",),"diff10"),
   ("THE SETUP",("Wired in minutes,","not weekends."),"The senses come connected on the desk: search, crawl, watch, all gated.",("Sight, preinstalled.",),"setup10"),
   ("THE BAR10",("Never trust an answer","that cannot see today."),"Ask yours what changed in your market this week. Watch it guess.",("Run that test now.",),"bar10"),
  ]),
 dict(slug="syllabus", title="THE 3-HOUR COURSE, INSTALLED", accent=(204,120,92), mark="claude", pill="operator",
  cover=("I read the 3-hour syllabus.","My desk ships it preinstalled."),
  close=("Save the checklist","and skip the course.","Which module are you still doing by hand?"),
  slides=[
   ("MODULE 1",("Memory files and","system prompts."),"The course teaches you to write them. The desk interviews you once and writes its own.",("Module one: automated.",),"mod1"),
   ("MODULE 2",("Agent teams and","parallel harnesses."),"Three hours on orchestration; here the seven agents already compose and hand off.",("Module two: wired.",),"mod2"),
   ("MODULE 3",("Skills and subagents,","the leverage layer."),"The syllabus explains the concept. The desk ships 71 working ones.",("Module three: stocked.",),"mod3"),
   ("MODULE 4",("Browser automation","and computer use."),"The lecture shows demos. The desk books, fills, checks and files, gated.",("Module four: hands, live.",),"mod4"),
   ("MODULE 5",("Security, permissions","and org hygiene."),"The course warns you. The desk defaults to the gate: nothing external without a tap.",("Module five: the keel.",),"mod5"),
   ("THE GAP10",("Courses teach configuration.","Founders need outcomes."),"Every hour configuring is an hour not selling. The config IS the product here.",("Buy outcomes, not setup.",),"gap10"),
   ("THE HOUR10",("The 3 hours became","one onboarding."),"Connect, interview, first run: the whole syllabus, lived by lunch.",("Watch it work instead.",),"hour10"),
   ("THE POINT10",("Knowledge was never","the moat."),"The people shipping are not the ones studying. Install, run, correct, repeat.",("Operators outlearn students.",),"point10"),
  ]),
 dict(slug="fiveam", title="THE 5AM SHIFT", accent=(200,70,35), mark="claude", pill="operator",
  cover=("My team clocks in at 5am.","I meet them at seven."),
  close=("Save the 5am setup","and hire the night shift.","What should run before you wake?"),
  slides=[
   ("05:00",("The shift starts.","Nobody set an alarm."),"Research, triage and drafting wake on schedule, not on willpower.",("Scheduled beats motivated.",),"clockin"),
   ("05:10",("Trends read.","Signals scored."),"Overnight movers in your niche, ranked against your ICP before sunrise.",("The market got read first.",),"trends"),
   ("05:30",("Content drafted","against the calendar."),"Today's slots filled in your voice, ranked by your bar, parked for your tap.",("The feed is prepped.",),"drafted"),
   ("06:00",("Workflows built","from yesterday's friction."),"The repeated job you cursed at 16:00 became a flow by 06:00.",("The desk self-extends.",),"builtflow"),
   ("06:45",("The digest compiles.","One page, everything."),"Done, parked, waiting, suggested: your whole company on one screen.",("Reading time: 4 minutes.",),"digest10"),
   ("07:00",("You walk in.","The work is staged."),"Approvals, two calls, one judgement decision: the day is already moving.",("You start at the top.",),"walkin"),
   ("THE COST10",("The night shift","bills in cents."),"No overtime, no burnout, no Monday mood.",("Payroll stayed flat.",),"cost10"),
   ("THE FLIP10",("Stop starting your day.","Start joining it."),"The 5am team exists. Yours is just not hired yet.",("Hire it tonight.",),"flip10"),
  ]),
 dict(slug="citedweb", title="REPORTS THAT CITE TODAY", accent=(212,162,127), mark="claude", pill="founder",
  cover=("Your AI answers from 2024.","Your business runs on today."),
  close=("Save the receipts standard","and audit your last report.","Would your numbers survive an audit?"),
  slides=[
   ("THE STALE",("Confident answers,","expired facts."),"Training data ends; your market does not. Unwired AI improvises the difference.",("Confidence is not currency.",),"stale"),
   ("THE STANDARD",("Every figure","traces to a source."),"Reports on the desk carry links and dates: this morning's web, named.",("Citations or silence.",),"standard"),
   ("THE BRIEF10",("The account brief quotes","yesterday's hiring page."),"Not remembers: quotes. Role, date, link, in the brief.",("Warm data closes.",),"brief10"),
   ("THE NUMBERS",("Month-end pulls live,","argues nothing."),"Revenue, pipeline, spend: fetched fresh, source attached, zero meetings about whose sheet is right.",("The argument died.",),"numbers10"),
   ("THE RIVALS",("Competitor moves,","dated and linked."),"Price changes and launches land in the digest with receipts, not rumors.",("You quote, they guess.",),"rivals"),
   ("THE TRUST",("Cited output is","delegable output."),"You can forward what you can verify. Guesses stay on your desk; receipts travel.",("Trust scales delegation.",),"trust10"),
   ("THE HABIT10",("Ask for the source","one time."),"Set the standard once; the desk cites forever after.",("One rule, permanent.",),"habit10"),
   ("THE LINE10",("If it cannot say when,","it does not know."),"Undated knowledge is opinion wearing a suit.",("Demand the date.",),"line10"),
  ]),
 dict(slug="twentyplays", title="MARKETING AS A COMMAND PALETTE", accent=(204,120,92), mark="strip", pill="operator",
  cover=("Your marketing department","is now a command palette."),
  close=("Save the palette","and run play one.","Which play replaces your Monday?"),
  slides=[
   ("THE PALETTE",("Twenty plays,","one line each."),"Blog factory, repurpose engine, tone cloning, hook generator: commands, not campaigns.",("Marketing became typing.",),"palette"),
   ("PLAY /BLOG",("An SEO post","in one command."),"Keyword in, structured draft out, in your voice, ranked before review.",("The factory floor.",),"playblog"),
   ("PLAY /REPURPOSE",("One article becomes","eight platforms."),"Posts, tweets, carousel scripts, newsletter: the matrix runs itself.",("Nothing dies as one format.",),"playrep"),
   ("PLAY /SEQUENCE",("The funnel emails,","written to stage."),"Describe the stage; five to seven emails land with CTAs, parked.",("The nurture, automated.",),"playseq"),
   ("PLAY /AUDIT",("Competitor content,","gutted for gaps."),"URLs in, angles and frequencies out, the unclaimed spaces flagged.",("Attack maps on demand.",),"playaudit"),
   ("PLAY /HEADLINE",("Ten headlines scored","before one ships."),"Emotion, clarity, curiosity: graded against the boring rules.",("No gut launches.",),"playhead"),
   ("THE DIFFERENCE10",("Tools give you features.","The palette gives you plays."),"Each command is a whole workflow with your voice and your gate inside.",("Plays, not prompts.",),"diff10b"),
   ("THE MONDAY",("The marketing Monday","runs before coffee."),"Plan, draft, repurpose, audit, queue: five commands, one hour, gated.",("The department, typed.",),"monday10"),
  ]),
]

ALL=BATCH1+BATCH2+BATCH3+BATCH4+BATCH5+BATCH6+BATCH7+BATCH8+BATCH9+BATCH10
