#!/usr/bin/env python3
# FROM PROMPT TO PRODUCT (s2src43) - Ultron reframe of the "vibe design cheatsheet" carousel
# (Claude Code + a design tool -> shipped app) into a build-to-ship recipe. Generated by adapt_build.py.
import importlib.util
spec=importlib.util.spec_from_file_location("T2","/home/user/tiberiu-claude/content/_hitl-src/build_team_3d.py")
T2=importlib.util.module_from_spec(spec); spec.loader.exec_module(T2)
wo=lambda s:(s,T2.WHITE); co=lambda s:(s,T2.CORAL); mu=lambda s:(s,T2.MUTED)
M="/home/user/tiberiu-claude/content/_hitl-src/models_clay/s2src43"; LIB=T2.LIB
PREMIUM=1
TITLE="FROM PROMPT TO PRODUCT"
T2.ACCENT=(212, 162, 127); T2.CORAL=T2.ACCENT
T2.OBJ_THR=30
T2.COVER=dict(head=[[wo('You typed one sentence.')],[co('It shipped the product.')]])
T2.CONTENT=[
 ('THE BRIEF', [[wo('Just say what you want.')],[co('In plain english.')]], 'No design tool, no dev shop, no brief document. One sentence in the chat.', [co('One sentence in.')], f"{M}/brief.png", 1.0),
 ('THE ROUTER', [[wo('It reads the job')],[co('and hires the agent.')]], 'Seven agents, one router. It picks the agent and the model tier per turn.', [co('You never pick a model.')], f"{M}/router.png", 1.0),
 ('THE BUILD', [[wo('It ships the real page.')],[co('Not a mockup.')]], 'SENTINEL writes, tests and ships the actual page, live on your domain.', [co('Live, not a demo.')], f"{M}/build.png", 1.0),
 ('THE LIBRARY', [[wo('Every asset,')],[co('one shelf.')]], 'Pages, emails, posts and decks. A dashboard and a library in one place.', [co('Dashboard plus library.')], f"{M}/library.png", 1.0),
 ('THE SPEC', [[wo('It remembers')],[co('your brand.')]], 'ICP, voice, pricing, palette. Written once, applied to every asset it builds.', [co('Written once, used always.')], f"{M}/memory.png", 1.0),
 ('THE GATE', [[wo('Nothing goes live')],[co('without your tap.')]], 'Every deploy parks at the human gate. You approve, then it ships.', [co('You hold the switch.')], f"{M}/gate.png", 1.0),
 ('THE MATH', [[wo('The old stack')],[co('cost hundreds.')]], 'Design tool, dev, copy tool, agency. Ultron does the lot for cents per run.', [co('Ours is cents.')], f"{M}/cost.png", 1.0),
 ('THE SYSTEM', [[wo('Not a prompt.')],[co('A running system.')]], 'It keeps working after you close the tab. Briefs in, assets out, every day.', [co('It keeps running.')], f"{M}/system.png", 1.0),
]
T2.CTA=("SAVE THIS", [[wo('Want the build recipe?')],[co('comment BUILDER.')]], "/home/user/tiberiu-claude/content/_hitl-src/_templates/cta/cta-builder.png", 0.82)
T2.CLOSE=dict(l1='Save this and',l2='build yours in one sentence.',q='What would you ship first?')
MARK2="claude"
