#!/usr/bin/env python3
"""The ten ULTRON CLAY decks: time-boxed transformations, not feature tours.

Genre set by the operator (2026-08-05) from the reference deck: launch a startup in 24 hours,
become the CEO, zero code. Every deck is a CLOCK plus an OUTCOME plus the identity change at
the end, and the mechanism is only ever the middle. What Ultron does is real (the seven agents,
the router, the gate, the documented behaviour in docs-01 to docs-13); what changes is that it
is framed as what you become rather than what the product has.

Object runs are asserted unique at build time, so no two decks read alike.
"""
import pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from _clay import build, dial, cards, badge, stack3, phone, grid2, rail

DECKS = []


def D(slug, title, kw, steps, slides, run):
    DECKS.append(dict(slug=slug, title=title, kw=kw, steps=steps, slides=slides, run=run))


def cta(kw, sub, body, badge_title):
    return dict(eyebrow="COMMENT", h=kw, sub=sub, body=body,
                obj=badge("ALL ACCESS", badge_title, "ACCESS: GRANTED", "51ULTRON.COM"))


# ---------------------------------------------------------------- 01
D("clay-01-48h", "48 HOUR RUN", "48H", ["2H", "6H", "24H", "48H"], [
  dict(eyebrow="THE 48 HOUR RUN", h="48 HOURS.<br>ONE PAYING<br><em>CUSTOMER.</em>",
       sub="No team. No code. No agency invoice.",
       body="While the plan is still in a doc, this one has already sent, built and closed.",
       obj=dial("48", "HOURS")),
  dict(eyebrow="HOUR 1 - 2", h="FIND<br><em>THEM.</em>",
       sub="Forty accounts, ranked before the coffee goes cold.",
       body="CORTEX reads the company, the person who signs and the signal that says now.",
       obj=cards([dict(n="01", b="Reads the company", i="sector, size, region, the stack they pay for"),
                  dict(n="02", b="Finds who signs", i="what they own and what they posted", acc=True),
                  dict(n="03", b="Ranks the forty", i="one page, before you open a tab")]),
       rail=rail(["2H","6H","24H","48H"], 0)),
  dict(eyebrow="HOUR 3 - 6", h="REACH<br><em>THEM.</em>",
       sub="Every message written on what CORTEX just found.",
       body="SPECTER writes the first touch and the follow ups. Nothing sends without you.",
       obj=stack3([dict(b="THE TRIGGER", u="why now, in one line"),
                   dict(b="THE ASK", u="a question, not a pitch", acc=True),
                   dict(b="THE GATE", u="you approve before it sends", inset=True)]),
       rail=rail(["2H","6H","24H","48H"], 1)),
  dict(eyebrow="HOUR 7 - 24", h="BUILD<br><em>IT.</em>",
       sub="The page they land on ships while you sleep.",
       body="SENTINEL writes the files, deploys, and checks its own work before it stops.",
       obj=grid2([dict(u="WRITES", b="Files", i="pages, copy, the form"),
                  dict(u="RUNS", b="Deploy", i="shell exec to a live URL", acc=True),
                  dict(u="OPENS", b="Browser", i="checks the page renders"),
                  dict(u="SHIPS", b="The PR", i="branch, commit, opened")]),
       rail=rail(["2H","6H","24H","48H"], 2)),
  dict(eyebrow="HOUR 25 - 48", h="CLOSE<br><em>THEM.</em>",
       sub="The objection you were about to walk past, surfaced.",
       body="STRIKER runs qualification, handles the objection, drafts the close.",
       obj=phone([(34,0),(52,0),(44,1),(78,1)], "FIRST SALE", "$49"),
       rail=rail(["2H","6H","24H","48H"], 3)),
  dict(eyebrow="WHAT ACTUALLY CHANGED", h="YOU DID NOT<br>WORK <em>HARDER.</em>",
       sub="You ran a team you never hired.",
       body="Seven agents, one operator, one gate. The work of a GTM team and the payroll of none of it.",
       obj=cards([dict(n="0", b="Hires", i="no roles, no onboarding"),
                  dict(n="7", b="Agents", i="research, outbound, deals, content, code", acc=True),
                  dict(n="1", b="Operator", i="you, holding the send button")])),
  cta("48H", "and I will send you the exact run.",
      "The prompts, the order, and where the human gate sits.", "THE 48 HOUR RUN"),
], run="dial,cards,stack3,grid2,phone,cards,badge")

# ---------------------------------------------------------------- 02
D("clay-02-90min", "90 MINUTES", "90MIN", ["15M", "40M", "70M", "90M"], [
  dict(eyebrow="BEFORE LUNCH", h="90 MINUTES.<br>FORTY <em>ACCOUNTS</em><br>YOU CAN CALL.",
       sub="The research that used to eat your Monday.",
       body="Not a list you bought. A list that knows why now, and who signs.",
       obj=dial("90", "MINUTES")),
  dict(eyebrow="MINUTE 1 - 15", h="ONE<br><em>DOMAIN.</em>",
       sub="You paste a domain. Nothing else.",
       body="No form to fill, no filters to tune, no seat to configure first.",
       obj=badge("THE INPUT", "PASTE ONE DOMAIN", "NO FORM", "NO FILTERS")),
  dict(eyebrow="MINUTE 16 - 40", h="IT READS<br>THE <em>COMPANY.</em>",
       sub="Sector, size, region, and the stack they already pay for.",
       body="CORTEX pulls the shape of the business before it ever looks at a person.",
       obj=grid2([dict(u="SECTOR", b="IT svc", i="what they actually sell"),
                  dict(u="SIZE", b="2-50", i="inside your ICP", acc=True),
                  dict(u="REGION", b="US / UK", i="where they buy"),
                  dict(u="STACK", b="7 tools", i="what they already pay for")]),
       rail=rail(["15M","40M","70M","90M"], 1)),
  dict(eyebrow="MINUTE 41 - 70", h="THEN THE ONE<br>WHO <em>SIGNS.</em>",
       sub="What they own, and what they posted last week.",
       body="Not the org chart. The person whose budget this comes out of.",
       obj=cards([dict(n="01", b="What they own", i="the number they are measured on"),
                  dict(n="02", b="What they posted", i="the opening line writes itself", acc=True),
                  dict(n="03", b="Why now", i="funding, hiring, a launch")]),
       rail=rail(["15M","40M","70M","90M"], 2)),
  dict(eyebrow="MINUTE 71 - 90", h="RANKED.<br>ONE <em>PAGE.</em>",
       sub="Forty accounts in the order you should work them.",
       body="Sitting there before your coffee goes cold, with the reason attached.",
       obj=stack3([dict(b="TIER 1", u="call today", acc=True),
                   dict(b="TIER 2", u="sequence this week"),
                   dict(b="TIER 3", u="nurture", inset=True)]),
       rail=rail(["15M","40M","70M","90M"], 3)),
  dict(eyebrow="WHAT ACTUALLY CHANGED", h="YOU STOPPED<br><em>OPENING TABS.</em>",
       sub="The first hour of every deal, given back.",
       body="Research was never the work. It was the tax you paid before the work.",
       obj=phone([(88,0),(62,0),(30,1),(14,1)], "TABS PER DEAL", "1")),
  cta("90MIN", "and I will send you the exact research run.",
      "One domain in, forty ranked accounts out.", "THE 90 MINUTE BRIEF"),
], run="dial,badge,grid2,cards,stack3,phone,badge")

# ---------------------------------------------------------------- 03
D("clay-03-weekend", "ONE WEEKEND", "WEEKEND", ["FRI", "SAT", "SUN", "MON"], [
  dict(eyebrow="ZERO CODE", h="ONE WEEKEND.<br>A LIVE<br><em>PRODUCT.</em>",
       sub="You describe it Friday. Monday it has a URL.",
       body="Not a mockup you still have to build. An address you can send a customer.",
       obj=dial("72", "HOURS")),
  dict(eyebrow="FRIDAY", h="YOU<br><em>DESCRIBE</em> IT.",
       sub="One paragraph. What it is for, and who it is for.",
       body="No repo to clone, no pipeline to configure, no engineer to interrupt.",
       obj=badge("THE BRIEF", "ONE PARAGRAPH", "NO REPO", "NO PIPELINE")),
  dict(eyebrow="SATURDAY", h="IT <em>WRITES</em><br>THE FILES.",
       sub="Pages, styles, the form, and the copy in your voice.",
       body="PULSE writes the words from your own material. SENTINEL writes the rest.",
       obj=stack3([dict(b="THE PAGE", u="layout, styles, states"),
                   dict(b="THE COPY", u="your voice, not a template", acc=True),
                   dict(b="THE FORM", u="wired to somewhere real", inset=True)]),
       rail=rail(["FRI","SAT","SUN","MON"], 1)),
  dict(eyebrow="SUNDAY", h="IT <em>SHIPS</em><br>ITSELF.",
       sub="Shell exec, a dev server, then a real address.",
       body="Then it opens a browser against the page it just deployed and checks it renders.",
       obj=cards([dict(n="01", b="Deploys", i="not a preview link that expires"),
                  dict(n="02", b="Opens the page", i="confirms it renders", acc=True),
                  dict(n="03", b="Fires the form", i="before it calls the job done")]),
       rail=rail(["FRI","SAT","SUN","MON"], 2)),
  dict(eyebrow="MONDAY", h="YOU SEND<br>THE <em>LINK.</em>",
       sub="To a customer. Not to a designer for review.",
       body="Changes are another sentence, not another sprint.",
       obj=phone([(20,0),(38,0),(60,1),(92,1)], "STATUS", "LIVE"),
       rail=rail(["FRI","SAT","SUN","MON"], 3)),
  dict(eyebrow="WHAT ACTUALLY CHANGED", h="YOU STOPPED<br><em>WAITING</em> ON<br>SOMEONE.",
       sub="The bottleneck was never the idea.",
       body="It was the three weeks between deciding and having something to show.",
       obj=grid2([dict(u="BEFORE", b="3 wks", i="brief, wait, review, wait"),
                  dict(u="AFTER", b="1 wknd", i="describe, ship, send", acc=True),
                  dict(u="COST", b="0", i="no agency invoice"),
                  dict(u="CODE", b="0", i="you wrote none of it")])),
  cta("WEEKEND", "and I will send you the build and deploy run.",
      "A sentence in, a live URL out, verified.", "THE WEEKEND BUILD"),
], run="dial,badge,stack3,cards,phone,grid2,badge")

# ---------------------------------------------------------------- 04
D("clay-04-hires", "ZERO HIRES", "HIRES", ["ROLE", "BRIEF", "RUN", "GATE"], [
  dict(eyebrow="THE 7 AGENT COMPANY", h="ZERO HIRES.<br>A SEVEN PERSON<br><em>GTM TEAM.</em>",
       sub="You are not short of people. You are short of a system.",
       body="Seven roles that would take a year and a payroll. Running tonight.",
       obj=dial("7", "AGENTS")),
  dict(eyebrow="WHAT YOU WOULD HAVE HIRED", h="SEVEN<br><em>ROLES.</em>",
       sub="Priced honestly, at the salaries these actually cost.",
       body="This is the comparison founders make in their head and never write down.",
       obj=cards([dict(n="01", b="A researcher", i="two hours before every call"),
                  dict(n="02", b="An SDR", i="the outbound you keep postponing", acc=True),
                  dict(n="03", b="A sales lead", i="the objection you did not hear")])),
  dict(eyebrow="WHAT YOU DO INSTEAD", h="YOU <em>TYPE</em><br>WHAT YOU WANT.",
       sub="Plain English. No agent picker, no model dropdown.",
       body="The router reads the job and sends it to whichever agent owns it.",
       obj=stack3([dict(b="YOU WRITE IT", u="one line, plain English"),
                   dict(b="THE ROUTER READS IT", u="who owns it, how deep", acc=True),
                   dict(b="THE AGENT ANSWERS", u="and hands off mid turn", inset=True)]),
       rail=rail(["ROLE","BRIEF","RUN","GATE"], 1)),
  dict(eyebrow="THE ROSTER", h="EACH ONE OWNS<br>A <em>JOB.</em>",
       sub="End to end. None of them is a chatbot with a costume on.",
       body="CORTEX, SPECTER, STRIKER, PULSE, SENTINEL, AMPLIFY, COUNSEL.",
       obj=grid2([dict(u="CORTEX", b="Research", i="one ranked brief"),
                  dict(u="SPECTER", b="Outbound", i="sequences that land", acc=True),
                  dict(u="STRIKER", b="Deals", i="objections and close plans"),
                  dict(u="SENTINEL", b="Code", i="ships it, opens the PR")]),
       rail=rail(["ROLE","BRIEF","RUN","GATE"], 2)),
  dict(eyebrow="THE ONE RULE", h="NOTHING SENDS<br>WITHOUT <em>YOU.</em>",
       sub="Seven agents, one gate, and you are holding it.",
       body="Autonomy without a gate is not leverage, it is a liability with good grammar.",
       obj=badge("HUMAN GATE", "YOU APPROVE THE SEND", "AGENTS: 7", "GATEKEEPERS: 1"),
       rail=rail(["ROLE","BRIEF","RUN","GATE"], 3)),
  dict(eyebrow="WHAT ACTUALLY CHANGED", h="YOU BECAME<br>THE <em>OPERATOR.</em>",
       sub="Not a busier founder. A different job.",
       body="You stopped doing the work of five people and started directing it.",
       obj=phone([(90,0),(66,0),(34,1),(12,1)], "HOURS ON TOOLS", "-78%")),
  cta("HIRES", "and I will send you the full roster.",
      "What each agent owns, and where the gate sits.", "THE 7 AGENT COMPANY"),
], run="dial,cards,stack3,grid2,badge,phone,badge")

# ---------------------------------------------------------------- 05
D("clay-05-tools", "TWELVE TO ONE", "TOOLS", ["AUDIT", "MOVE", "ROUTE", "CANCEL"], [
  dict(eyebrow="ONE AFTERNOON", h="TWELVE TABS.<br>ONE <em>BOX.</em>",
       sub="You are not paying for tools. You are paying for tabs.",
       body="Every one of them holds a piece of your context and none of them share it.",
       obj=dial("12", "TABS")),
  dict(eyebrow="THE AUDIT", h="WHAT YOU<br>ACTUALLY <em>OPEN.</em>",
       sub="Count the ones you touched this week. It is never twelve.",
       body="The rest are a subscription and a login you have stopped noticing.",
       obj=grid2([dict(u="PAID FOR", b="12", i="on the card every month"),
                  dict(u="OPENED", b="4", i="in the last seven days", acc=True),
                  dict(u="SHARED CONTEXT", b="0", i="none of them talk"),
                  dict(u="TIME LOST", b="Daily", i="pasting between them")])),
  dict(eyebrow="THE MOVE", h="THE WORK GOES<br>IN <em>ONE PLACE.</em>",
       sub="Same jobs. One input. Memory underneath all of it.",
       body="Research, outbound, deals, content and code, one keystroke apart.",
       obj=stack3([dict(b="ONE INPUT", u="plain English, no picker"),
                   dict(b="ONE MEMORY", u="profile, facts, open work", acc=True),
                   dict(b="ONE GATE", u="nothing sends without you", inset=True)]),
       rail=rail(["AUDIT","MOVE","ROUTE","CANCEL"], 1)),
  dict(eyebrow="THE ROUTING", h="THE JOB PICKS<br>THE <em>MODEL.</em>",
       sub="You stop deciding which one is smart enough today.",
       body="Lite for lookups, Smart for the standing work, Deep when judgement is hard.",
       obj=cards([dict(n="01", b="It reads the job first", i="volume, depth, cost of being wrong"),
                  dict(n="02", b="Then it picks the tier", i="per turn, not per user", acc=True),
                  dict(n="03", b="You never choose again", i="and never overpay for a lookup")]),
       rail=rail(["AUDIT","MOVE","ROUTE","CANCEL"], 2)),
  dict(eyebrow="THE CANCEL", h="THE PART THAT<br><em>HURTS</em> NOBODY.",
       sub="Eight subscriptions you will not miss by Friday.",
       body="Keep the two that do something nothing else does. Cancel the rest.",
       obj=phone([(96,0),(70,0),(40,1),(16,1)], "TABS PER JOB", "1"),
       rail=rail(["AUDIT","MOVE","ROUTE","CANCEL"], 3)),
  dict(eyebrow="WHAT ACTUALLY CHANGED", h="THE STACK<br>STOPPED BEING<br>YOUR <em>JOB.</em>",
       sub="You were the integration layer. That was the problem.",
       body="Twelve tools with no shared memory made you the thing that carried context.",
       obj=badge("THE AUDIT", "TWELVE TO ONE", "TABS: 1", "CONTEXT: KEPT")),
  cta("TOOLS", "and I will send you the stack audit.",
      "What to keep, what to cancel, and in what order.", "THE STACK AUDIT"),
], run="dial,grid2,stack3,cards,phone,badge,badge")

# ---------------------------------------------------------------- 06
D("clay-06-calendar", "ONE SITTING", "CALENDAR", ["ANGLE", "DRAFT", "FORMAT", "QUEUE"], [
  dict(eyebrow="ONE SITTING", h="THIRTY DAYS<br>OF <em>CONTENT.</em><br>ONE SITTING.",
       sub="Not thirty posts. Thirty days of a point of view.",
       body="The reason you post twice and stop is that every post starts from nothing.",
       obj=dial("30", "DAYS")),
  dict(eyebrow="THE ANGLE", h="IT STARTS FROM<br>YOUR <em>MATERIAL.</em>",
       sub="What you already said, decided and shipped.",
       body="PULSE writes in your voice because it reads what you actually wrote.",
       obj=grid2([dict(u="POSTS", b="Yours", i="the ones that already worked"),
                  dict(u="DECISIONS", b="Yours", i="what you changed and why", acc=True),
                  dict(u="NUMBERS", b="Real", i="not rounded, not invented"),
                  dict(u="VOICE", b="Yours", i="read, not imitated")])),
  dict(eyebrow="THE DRAFT", h="THIRTY <em>HOOKS</em><br>BEFORE ONE POST.",
       sub="The hook is the whole thing. Write those first.",
       body="Then only the ones that stop a scroll get a body written under them.",
       obj=stack3([dict(b="30 HOOKS", u="written first, ranked"),
                   dict(b="THE SURVIVORS", u="the ones worth a body", acc=True),
                   dict(b="THE POSTS", u="written under a proven line", inset=True)]),
       rail=rail(["ANGLE","DRAFT","FORMAT","QUEUE"], 1)),
  dict(eyebrow="THE FORMAT", h="ONE IDEA.<br>THREE <em>CHANNELS.</em>",
       sub="AMPLIFY cuts each one to the channel it is going to.",
       body="A carousel, a short video, and a text post are not the same post resized.",
       obj=cards([dict(n="01", b="LinkedIn carousel", i="1080x1350, the save play"),
                  dict(n="02", b="Reels and TikTok", i="1080x1920, the reach play", acc=True),
                  dict(n="03", b="Posted 10 to 11 AM", i="your proven window")]),
       rail=rail(["ANGLE","DRAFT","FORMAT","QUEUE"], 2)),
  dict(eyebrow="THE QUEUE", h="SCHEDULED<br>AND <em>GATED.</em>",
       sub="Sized, slotted, and waiting for you to say yes.",
       body="Thirty days sitting in a queue you approve once, not thirty times.",
       obj=badge("THE QUEUE", "30 DAYS SCHEDULED", "APPROVALS: 1", "POSTS: 30"),
       rail=rail(["ANGLE","DRAFT","FORMAT","QUEUE"], 3)),
  dict(eyebrow="WHAT ACTUALLY CHANGED", h="YOU STOPPED<br>POSTING<br>WHEN YOU FELT<br><em>LIKE IT.</em>",
       sub="Consistency was never discipline. It was inventory.",
       body="Nobody posts daily on willpower. They post daily because it is already written.",
       obj=phone([(18,0),(30,0),(58,1),(94,1)], "POSTS THIS MONTH", "30")),
  cta("CALENDAR", "and I will send you the thirty day run.",
      "Angles, hooks, formats and the posting window.", "THE 30 DAY QUEUE"),
], run="dial,grid2,stack3,cards,badge,phone,badge")

# ---------------------------------------------------------------- 07
D("clay-07-legal", "TEN MINUTES", "LEGAL", ["READ", "FLAG", "REDLINE", "SEND"], [
  dict(eyebrow="TEN MINUTES", h="THE NDA THAT<br>SAT THERE<br>FOR <em>A WEEK.</em>",
       sub="Read, flagged and redlined before your next call.",
       body="You were not avoiding it because it was hard. You were avoiding it because it was dull.",
       obj=dial("10", "MINUTES")),
  dict(eyebrow="IT READS IT", h="EVERY <em>CLAUSE.</em><br>NOT THE SUMMARY.",
       sub="COUNSEL reads the document you were going to skim.",
       body="The one that matters is never in the first two pages.",
       obj=stack3([dict(b="THE WHOLE DOC", u="not the executive summary"),
                   dict(b="THE DEFINITIONS", u="where the trap usually lives", acc=True),
                   dict(b="THE SCHEDULES", u="the part nobody opens", inset=True)])),
  dict(eyebrow="IT FLAGS IT", h="WHAT WOULD<br>COST <em>YOU.</em>",
       sub="Ranked by what it actually does to you, not by clause order.",
       body="Term, liability, IP, and the exclusivity you did not notice you granted.",
       obj=cards([dict(n="01", b="Liability", i="uncapped, and pointing at you"),
                  dict(n="02", b="IP assignment", i="broader than the work", acc=True),
                  dict(n="03", b="Term", i="auto renewing, quietly")]),
       rail=rail(["READ","FLAG","REDLINE","SEND"], 1)),
  dict(eyebrow="IT REDLINES IT", h="WITH THE <em>WORDS</em><br>TO SEND BACK.",
       sub="Not advice. The actual replacement sentence.",
       body="So the reply is a paste, not a paragraph you have to compose at 11pm.",
       obj=grid2([dict(u="CLAUSE", b="Cap it", i="at fees paid, 12 months"),
                  dict(u="CLAUSE", b="Narrow IP", i="to the deliverable only", acc=True),
                  dict(u="CLAUSE", b="Kill auto", i="renew becomes opt in"),
                  dict(u="TONE", b="Reasonable", i="you still want the deal")]),
       rail=rail(["READ","FLAG","REDLINE","SEND"], 2)),
  dict(eyebrow="YOU SEND IT", h="AFTER <em>YOU</em><br>READ IT.",
       sub="COUNSEL drafts. It does not sign anything.",
       body="The gate matters most on the documents that bind you.",
       obj=badge("HUMAN GATE", "YOU SIGN, NOT IT", "DRAFTED: BY COUNSEL", "SIGNED: BY YOU"),
       rail=rail(["READ","FLAG","REDLINE","SEND"], 3)),
  dict(eyebrow="WHAT ACTUALLY CHANGED", h="THE PAPER<br>STOPPED BEING<br>THE <em>DELAY.</em>",
       sub="Deals do not die on price. They die in the inbox.",
       body="A week of silence on an NDA is a week the buyer spends cooling off.",
       obj=phone([(92,0),(64,0),(28,1),(10,1)], "DAYS ON PAPER", "0.5")),
  cta("LEGAL", "and I will send you the review run.",
      "What COUNSEL flags first, and the redlines it drafts.", "THE 10 MINUTE REVIEW"),
], run="dial,stack3,cards,grid2,badge,phone,badge")

# ---------------------------------------------------------------- 08
D("clay-08-overnight", "ONE NIGHT", "OVERNIGHT", ["BRIEF", "RUN", "SHIP", "WAKE"], [
  dict(eyebrow="ONE NIGHT", h="YOU CLOSED<br>THE LAPTOP.<br>IT KEPT <em>GOING.</em>",
       sub="The company only moves while you are at the desk. It does not have to.",
       body="Anything that will not finish before you sleep becomes a job instead.",
       obj=dial("8", "HOURS")),
  dict(eyebrow="23:47", h="ONE LINE<br>BEFORE <em>BED.</em>",
       sub="Not a spec. Not a ticket. One sentence of intent.",
       body="Nobody to brief in the morning and no standup to schedule.",
       obj=badge("THE BRIEF", "ONE SENTENCE", "SPEC: NONE", "MEETINGS: 0")),
  dict(eyebrow="02:14", h="IT DISPATCHES<br>A <em>TEAM.</em>",
       sub="Not one model answering alone.",
       body="Browsing the sources, running the skill that owns the job, writing the files.",
       obj=cards([dict(n="01", b="Searches memory", i="before it asks the internet"),
                  dict(n="02", b="Runs the skill", i="the workflow that owns this job", acc=True),
                  dict(n="03", b="Saves what it learned", i="so the next run starts smarter")]),
       rail=rail(["BRIEF","RUN","SHIP","WAKE"], 1)),
  dict(eyebrow="05:30", h="IT <em>SHIPS</em><br>AND CHECKS.",
       sub="A real address, then a browser opened against it.",
       body="Output you still have to verify is not finished work. It is homework.",
       obj=stack3([dict(b="SHELL EXEC", u="build, deploy, a live URL"),
                   dict(b="OPENS THE PAGE", u="confirms it renders", acc=True),
                   dict(b="THEN STOPS", u="not before", inset=True)]),
       rail=rail(["BRIEF","RUN","SHIP","WAKE"], 2)),
  dict(eyebrow="07:02", h="YOU WAKE UP<br>TO A <em>RESULT.</em>",
       sub="Three assets in the queue, sized and slotted.",
       body="The page live, a carousel for Tuesday, a video cut for Reels.",
       obj=grid2([dict(u="LIVE", b="The page", i="a URL you can open"),
                  dict(u="QUEUED", b="Carousel", i="1080x1350, Tuesday 09:00", acc=True),
                  dict(u="QUEUED", b="Video", i="1080x1920, Reels"),
                  dict(u="YOUR INPUT", b="1 line", i="typed at 23:47")]),
       rail=rail(["BRIEF","RUN","SHIP","WAKE"], 3)),
  dict(eyebrow="WHAT ACTUALLY CHANGED", h="THE DAY STOPPED<br>ENDING WHEN<br><em>YOU</em> DID.",
       sub="Eight hours a night you were never using anyway.",
       body="You did not find more time. You stopped being the thing time depended on.",
       obj=phone([(12,0),(30,0),(62,1),(96,1)], "SHIPPED BY 07:02", "3")),
  cta("OVERNIGHT", "and I will send you the overnight setup.",
      "How to brief it, and how it verifies before it stops.", "THE OVERNIGHT RUN"),
], run="dial,badge,cards,stack3,grid2,phone,badge")

# ---------------------------------------------------------------- 09
D("clay-09-router", "ONE PROMPT", "ROUTER", ["READ", "PICK", "RUN", "PAY"], [
  dict(eyebrow="ONE PROMPT", h="YOU NEVER<br>PICK THE<br><em>MODEL.</em> AGAIN.",
       sub="Every other tool opens by asking you a question you cannot answer.",
       body="Nobody knows which model wins a job before they see the output.",
       obj=dial("0", "CHOICES")),
  dict(eyebrow="THE READ", h="IT READS<br>THE <em>JOB</em> FIRST.",
       sub="Four reads, before a single token of output.",
       body="How big it is, how deep it goes, what wrong costs, and how fast you need it.",
       obj=grid2([dict(u="VOLUME", b="How big", i="forty accounts or one answer"),
                  dict(u="DEPTH", b="How deep", i="a lookup or a judgement", acc=True),
                  dict(u="RISK", b="Cost of wrong", i="you review it, or a customer sees it"),
                  dict(u="SPEED", b="How fast", i="now, or by morning")])),
  dict(eyebrow="THE PICK", h="THE TIER<br>AND THE <em>EFFORT.</em>",
       sub="Two decisions, not one, and neither of them is yours.",
       body="Haiku on low for lookups. Sonnet on high for the work. Opus when it is hard.",
       obj=cards([dict(n="01", b="Haiku 4.5, low", i="lookups, classifying, high volume"),
                  dict(n="02", b="Sonnet 5, high", i="the standing default", acc=True),
                  dict(n="03", b="Opus 5, xhigh", i="hard judgement, strategy")]),
       rail=rail(["READ","PICK","RUN","PAY"], 1)),
  dict(eyebrow="THE RUN", h="ONE INPUT.<br>EIGHT <em>JOBS.</em>",
       sub="Research, enrichment, scoring, outbound, prep, proposals, objections, close.",
       body="Run all eight through one model and it is the right tool for exactly one.",
       obj=stack3([dict(b="ONE MODEL, 8 JOBS", u="right for one of them"),
                   dict(b="ROUTED, 8 JOBS", u="right for all eight", acc=True),
                   dict(b="CONTEXT", u="held across every one", inset=True)]),
       rail=rail(["READ","PICK","RUN","PAY"], 2)),
  dict(eyebrow="THE BILL", h="YOU STOP<br><em>OVERPAYING</em><br>FOR LOOKUPS.",
       sub="The cheap model runs the cheap work. Automatically.",
       body="Haiku is a third of Sonnet on the volume that never needed more.",
       obj=badge("THE SPREAD", "1x  3x  5x  10x", "HAIKU TO FABLE", "PER MILLION TOKENS"),
       rail=rail(["READ","PICK","RUN","PAY"], 3)),
  dict(eyebrow="WHAT ACTUALLY CHANGED", h="THE TOOL<br>STOPPED ASKING<br>YOU TO <em>RUN IT.</em>",
       sub="Model choice was never a preference. It is a routing problem.",
       body="Routing problems belong to the system, not the person using it.",
       obj=phone([(94,0),(70,0),(38,1),(8,1)], "DECISIONS PER TURN", "0")),
  cta("ROUTER", "and I will send you the routing setup.",
      "What it reads, and how it picks the tier and the effort.", "THE ROUTING LAYER"),
], run="dial,grid2,cards,stack3,badge,phone,badge")

# ---------------------------------------------------------------- 10
D("clay-10-30days", "THIRTY DAYS", "30DAYS", ["WK1", "WK2", "WK3", "WK4"], [
  dict(eyebrow="THIRTY DAYS", h="A GTM THAT<br>RUNS WITHOUT<br><em>YOU.</em>",
       sub="Not automated. Operated, by someone who is not at the desk.",
       body="Thirty days is not a promise. It is how long the four changes take in order.",
       obj=dial("30", "DAYS")),
  dict(eyebrow="WEEK 1", h="STOP<br><em>CHOOSING.</em>",
       sub="The cheapest change and the biggest jump.",
       body="Take model choice off the screen. Everything downstream gets easier.",
       obj=badge("WEEK ONE", "ROUTING FIRST", "EFFORT: LOW", "PAYOFF: HIGH")),
  dict(eyebrow="WEEK 2", h="PUT MEMORY<br><em>UNDERNEATH.</em>",
       sub="Stop paying the blank page tax on every single turn.",
       body="Profile, saved facts and open work, stitched in before the answer starts.",
       obj=cards([dict(n="01", b="Tell it once", i="who you are, what you sell"),
                  dict(n="02", b="It keeps it", i="and pulls it back when relevant", acc=True),
                  dict(n="03", b="Every turn writes back", i="it gets better the longer you run")]),
       rail=rail(["WK1","WK2","WK3","WK4"], 1)),
  dict(eyebrow="WEEK 3", h="MAKE IT<br><em>VERIFY.</em>",
       sub="Output you still have to check is not finished work.",
       body="Ship to a real address, open it, confirm it, then call it done.",
       obj=stack3([dict(b="IT SHIPS", u="to a real address"),
                   dict(b="IT CHECKS", u="its own output", acc=True),
                   dict(b="THEN IT STOPS", u="not before", inset=True)]),
       rail=rail(["WK1","WK2","WK3","WK4"], 2)),
  dict(eyebrow="WEEK 4", h="HOLD THE<br><em>GATE.</em>",
       sub="The one almost nobody builds, and everybody needs.",
       body="Governance is the reason most agent projects die. It is also the easiest to add.",
       obj=badge("THE ORDER", "ROUTE, REMEMBER,<br>VERIFY, GATE",
                 "WEEKS: 4", "REVERSIBLE: NO"),
       rail=rail(["WK1","WK2","WK3","WK4"], 3)),
  dict(eyebrow="WHAT ACTUALLY CHANGED", h="YOU STOPPED<br>BEING THE<br><em>BOTTLENECK.</em>",
       sub="Every one of those four took something off your desk permanently.",
       body="Not a productivity trick. Four structural changes, in the order that pays.",
       obj=phone([(96,0),(72,0),(44,1),(18,1)], "DEPENDS ON YOU", "-80%")),
  cta("30DAYS", "and I will send you the thirty day order.",
      "The four changes, in the sequence that actually pays.", "THE 30 DAY PLAN"),
], run="dial,badge,cards,stack3,badge,phone,badge")


def main():
    seen = {}
    for d in DECKS:
        if d["run"] in seen:
            sys.exit(f"{d['slug']} repeats the object run of {seen[d['run']]}")
        seen[d["run"]] = d["slug"]
    for d in DECKS:
        p = build(d["slug"], d["title"], d["slides"])
        print(f"  {p.name:22} {len(d['slides'])} slides  {d['kw']:9} {d['run']}")
    print(f"{len(DECKS)} decks, every object run unique")


if __name__ == "__main__":
    main()
