#!/usr/bin/env python3
"""Export a Claude Code session transcript to a plain text file.

The raw session log is one JSON object per line and runs to tens of megabytes,
almost all of it tool results and base64 image payloads. This writes the part a
human wants to keep: every operator message verbatim, every reply verbatim, and
one line per tool action so the record still shows what was done between them.

  python3 content/_convexport.py                       # newest session in this project
  python3 content/_convexport.py --out analysis/x.txt
  python3 content/_convexport.py --thinking            # include reasoning blocks
  python3 content/_convexport.py --results 400         # keep N chars of each tool result

Operator messages are copied CHARACTER FOR CHARACTER. This file is a record, not
a material, so the 21 charscan does not apply to it: correcting the operator's
own punctuation inside a transcript would falsify the transcript.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from datetime import datetime, timezone, timedelta

PROJECTS = "/root/.claude/projects"
RO = timezone(timedelta(hours=3))  # operator is on Romania time

SKIP_TAGS = re.compile(
    r"<system-reminder>.*?</system-reminder>"
    r"|<local-command-stdout>.*?</local-command-stdout>"
    r"|<local-command-caveat>.*?</local-command-caveat>"
    r"|<command-message>.*?</command-message>"
    r"|<command-args>.*?</command-args>",
    re.S,
)
CMD_NAME = re.compile(r"<command-name>(.*?)</command-name>", re.S)

# Plumbing that reaches the log as if the operator had typed it. None of it is his.
IMG_META = re.compile(r"^\[Image:[^\]]*\]\s*", re.S)
DROP_WHOLE = (
    "Stop hook feedback:",
    "Caveat: The messages below were generated by the user",
    "[Image:",
)

# A transcript is written to disk and committed, so it may never carry a live
# credential. The operator pasted an ElevenLabs key into the chat on 12 Aug; that
# line is preserved with the key itself replaced.
SECRET_PATTERNS = [
    re.compile(r"\bsk-ant-[A-Za-z0-9_\-]{16,}"),
    re.compile(r"\bsk[_\-][A-Za-z0-9]{24,}"),
    re.compile(r"\b(?:ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9]{20,}"),
    re.compile(r"\bgithub_pat_[A-Za-z0-9_]{20,}"),
    re.compile(r"\bAIza[0-9A-Za-z_\-]{30,}"),
    re.compile(r"\bxox[abposr]-[A-Za-z0-9\-]{10,}"),
    re.compile(r"\beyJ[A-Za-z0-9_\-]{20,}\.[A-Za-z0-9_\-]{20,}\.[A-Za-z0-9_\-]{10,}"),
]
SECRET_ENV = (
    "ARK_API_KEY",
    "ELEVEN_API_KEY",
    "ELEVENLABS_API_KEY",
    "ANTHROPIC_API_KEY",
    "GH_PAT",
    "GITHUB_TOKEN",
)


def redact(s: str) -> str:
    for v in (os.environ.get(k) for k in SECRET_ENV):
        if v and len(v) > 12:
            s = s.replace(v, "[redacted key]")
    for p in SECRET_PATTERNS:
        s = p.sub("[redacted key]", s)
    return s


def project_dir(cwd: str) -> str:
    return os.path.join(PROJECTS, "-" + cwd.strip("/").replace("/", "-"))


def newest_log(d: str) -> str:
    logs = [os.path.join(d, f) for f in os.listdir(d) if f.endswith(".jsonl")]
    if not logs:
        sys.exit(f"no session log in {d}")
    return max(logs, key=os.path.getmtime)


def stamp(iso: str) -> str:
    if not iso:
        return "?"
    try:
        t = datetime.fromisoformat(iso.replace("Z", "+00:00")).astimezone(RO)
    except ValueError:
        return iso
    return t.strftime("%a %d %b, %H:%M")


def one_line(s: str, cap: int = 160) -> str:
    s = " ".join(str(s).split())
    return s if len(s) <= cap else s[: cap - 3] + "..."


def tool_line(name: str, inp: dict) -> str:
    """One readable line for a tool call. The point is what it touched, not its arguments."""
    g = lambda k: inp.get(k) if isinstance(inp, dict) else None
    if name == "Bash":
        return f"$ {one_line(g('command') or '')}"
    if name in ("Read", "Write"):
        return f"{name.lower()} {g('file_path')}"
    if name == "Edit":
        return f"edit {g('file_path')}: {one_line(g('old_string') or '', 60)}"
    if name == "Grep":
        return f"grep {one_line(g('pattern') or '', 60)} in {g('path') or '.'}"
    if name == "Glob":
        return f"glob {g('pattern')}"
    if name == "SendUserFile":
        return "sent to operator: " + ", ".join(g("files") or [])
    if name in ("WebSearch",):
        return f"web search: {one_line(g('query') or '')}"
    if name in ("WebFetch",):
        return f"web fetch: {g('url')}"
    if name == "TodoWrite":
        todos = g("todos") or []
        act = [t.get("content") for t in todos if t.get("status") == "in_progress"]
        return "todo: " + (one_line(act[0]) if act else f"{len(todos)} items")
    if name == "AskUserQuestion":
        qs = g("questions") or []
        return "asked: " + one_line(qs[0].get("question", "") if qs else "")
    keys = [k for k in ("file_path", "path", "url", "query", "prompt") if g(k)]
    return f"{name} " + (one_line(str(g(keys[0])), 100) if keys else "")


def render(log: str, thinking: bool, results: int) -> tuple[str, dict]:
    out: list[str] = []
    index: list[str] = []
    n = {"operator": 0, "reply": 0, "tools": 0, "images": 0}
    first = last = None
    day = None

    with open(log, encoding="utf-8") as f:
        for raw in f:
            raw = raw.strip()
            if not raw:
                continue
            try:
                d = json.loads(raw)
            except json.JSONDecodeError:
                continue

            kind = d.get("type")
            if kind not in ("user", "assistant"):
                continue
            ts = d.get("timestamp") or ""
            if ts:
                first = first or ts
                last = ts

            content = (d.get("message") or {}).get("content")
            if isinstance(content, str):
                content = [{"type": "text", "text": content}]
            if not isinstance(content, list):
                continue

            if kind == "user":
                parts: list[str] = []
                for b in content:
                    if not isinstance(b, dict):
                        continue
                    if b.get("type") == "image":
                        n["images"] += 1
                        parts.append("[screenshot uploaded]")
                    elif b.get("type") == "text":
                        txt = b.get("text") or ""
                        cmd = CMD_NAME.search(txt)
                        txt = SKIP_TAGS.sub("", txt)
                        txt = CMD_NAME.sub("", txt).strip()
                        if txt.startswith(DROP_WHOLE):
                            txt = IMG_META.sub("", txt).strip()
                            if not txt or txt.startswith(DROP_WHOLE):
                                continue
                        if cmd:
                            parts.append(f"[slash command {cmd.group(1).strip()}]")
                        if txt:
                            parts.append(redact(txt))
                    elif b.get("type") == "tool_result" and results:
                        r = b.get("content")
                        if isinstance(r, list):
                            r = " ".join(
                                x.get("text", "") for x in r if isinstance(x, dict)
                            )
                        if isinstance(r, str) and r.strip():
                            out.append(f"        -> {one_line(r, results)}")
                body = "\n".join(p for p in parts if p).strip()
                if body:
                    n["operator"] += 1
                    d_ = stamp(ts).split(",")[0]
                    if d_ != day:
                        day = d_
                        out.append("")
                        out.append("#" * 78)
                        out.append(f"#  {day}")
                        out.append("#" * 78)
                        index.append("")
                    out.append("")
                    out.append("=" * 78)
                    out.append(f"OPERATOR {n['operator']:03d}  [{stamp(ts)}]")
                    out.append("=" * 78)
                    out.append(body)
                    out.append("")
                    index.append(f"  {n['operator']:03d}  {stamp(ts)}   {one_line(body, 88)}")
                continue

            for b in content:
                if not isinstance(b, dict):
                    continue
                t = b.get("type")
                if t == "text":
                    txt = (b.get("text") or "").strip()
                    if txt:
                        n["reply"] += 1
                        out.append(f"CLAUDE  [{stamp(ts)}]")
                        out.append("-" * 78)
                        out.append(redact(txt))
                        out.append("")
                elif t == "thinking" and thinking:
                    txt = (b.get("thinking") or "").strip()
                    if txt:
                        out.append("(reasoning)")
                        out.append(txt)
                        out.append("")
                elif t == "tool_use":
                    n["tools"] += 1
                    out.append(
                        "    [" + redact(tool_line(b.get("name", "?"), b.get("input") or {})) + "]"
                    )

    head = [
        "ULTRON CONTENT SESSION TRANSCRIPT",
        "",
        f"session log   {os.path.basename(log)}",
        f"period        {stamp(first)} to {stamp(last)}  (Romania time)",
        f"operator      Tibi Serbaneci",
        f"repo          NexityNetwork/tiberiu-claude",
        "",
        f"{n['operator']} operator messages, {n['reply']} replies, {n['tools']} tool actions, "
        f"{n['images']} screenshots uploaded.",
        "",
        "Operator messages are verbatim. Tool actions are collapsed to one line each",
        "(the full results ran to 80 MB and are not reproduced). Screenshots appear as",
        "markers, since the images themselves live in the chat. Any API key pasted into",
        "the chat is replaced with [redacted key].",
        "",
        "Search for OPERATOR 087 to jump to that message.",
        "",
        "-" * 78,
        "INDEX OF OPERATOR MESSAGES",
        "-" * 78,
    ]
    return "\n".join(head + index + ["", "=" * 78, ""]) + "\n".join(out) + "\n", n


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--log", help="path to a .jsonl session log")
    ap.add_argument("--out", default=None)
    ap.add_argument("--thinking", action="store_true")
    ap.add_argument("--results", type=int, default=0, help="chars of each tool result to keep")
    a = ap.parse_args()

    log = a.log or newest_log(project_dir(os.getcwd()))
    text, n = render(log, a.thinking, a.results)

    out = a.out or os.path.join(
        "analysis", "transcript-" + datetime.now(RO).strftime("%Y-%m-%d") + ".txt"
    )
    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write(text)
    kb = os.path.getsize(out) / 1024
    print(f"{out}  {kb:.0f} KB  {len(text.splitlines())} lines")
    print("  " + json.dumps(n))


if __name__ == "__main__":
    main()
