#!/usr/bin/env python3
"""The eight Instagram carousels, rebuilt on the approved 2.5D working model.

Themes and copy carry over from the decks the operator kept; what changes is the machinery
underneath. Every slide is now header / STAGE / caption / footer against a declared pixel
workspace (CLAUDE.md 30), and the scene is built to fill the stage rather than sized to itself
and centred in the leftovers.

The three binding content rules are unchanged and still enforced by reading, not by hope:

1. FAST REWARD. The clock is 24 to 72 hours, never a month. Thirty days is a plan.
2. NO AGENT NAMES, EVER, and no internal mechanics as headlines. Plain words only.
3. GAIN, NOT AVOIDANCE. Become, launch, first customer, wake up shipped, revenue.

Graphic variety is asserted from what actually gets built: each scene stamps `data-ob` on its
own root, the run is read back off the slides, and the build fails on a repeat inside a deck,
a duplicate run, or two decks opening on the same form.
"""
import pathlib, re, sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from _clay25 import (build, scene_tower, scene_desk, scene_key, scene_seal, scene_ladder,
                     scene_split, scene_board, scene_bill, scene_clock, scene_thread,
                     scene_meter, scene_grid, scene_arch, scene_stack, scene_gantt,
                     scene_screen, scene_pillars)

DECKS = []


def D(slug, title, kw, slides):
    DECKS.append(dict(slug=slug, title=title, kw=kw, slides=slides,
                      run=[re.search(r'data-ob="([a-z0-9]+)"', s["scene"]).group(1)
                           for s in slides]))


def S(eyebrow, h, sub, scene, cap=None):
    return dict(eyebrow=eyebrow, h=h, sub=sub, scene=scene, cap=cap)


# ---------------------------------------------------------------- 01 CEO
D("clay-01-ceo", "BECOME A CEO", "CEO", [
  S("ONE DAY", "BECOME A<br><em>CEO</em> IN<br>24 HOURS.",
    "You already have the title. <b>You do not have the job.</b>",
    scene_tower([dict(n="01", b="Decide", i="the calls only you can make"),
                 dict(n="02", b="Sell", i="the rooms that need your face", acc=True),
                 dict(n="03", b="Say no", i="the thing nobody else may do")],
                "EVERYTHING ELSE", "DELEGATED"),
    ("HOUR 1", "Write the three down. It is always the same three.")),
  S("HOUR 2 - 8", "HAND OVER<br>THE <em>REST.</em>",
    "You describe each job once, in plain English. <b>It runs from there.</b>",
    scene_board("WHAT LEAVES YOUR DESK TODAY",
                [dict(b="Research", i="the accounts you named"),
                 dict(b="First drafts", i="in your own words", acc=True),
                 dict(b="Follow ups", i="every one, on time"),
                 dict(b="The paperwork", i="read and filed")],
                "BRIEFED ONCE, NOT DONE BY YOU"),
    ("NO FORMS", "One line each. No tickets, no handover doc.")),
  S("HOUR 9 - 14", "IT WORKS<br>WHILE YOU<br><em>DECIDE.</em>",
    "Two meetings that matter. <b>Eleven other jobs running.</b>",
    scene_arch([dict(b="You say what you want", i="one sentence, plain English"),
                dict(b="It runs unattended", i="start to finish, no check ins", acc=True),
                dict(b="It checks its own work", i="opens it and confirms")],
               "NONE OF IT NEEDS YOU IN THE ROOM"),
    ("HOUR 14", "You were in two meetings. Eleven jobs moved.")),
  S("HOUR 15 - 20", "EVERYTHING<br>ARRIVES<br><em>FINISHED.</em>",
    "Not a draft that hands the work back to you.",
    scene_screen("app.51ultron.com", "TODAY",
                 [dict(b="Research on 40 accounts", t="DONE", acc=True),
                  dict(b="Outreach drafted", t="WAITING"),
                  dict(b="The page, built and checked", t="LIVE", acc=True),
                  dict(b="Contract reviewed", t="DONE"),
                  dict(b="This week's posts", t="QUEUED")],
                 "FIVE THINGS, ONE AFTERNOON"),
    ("YOUR CALL", "Everything waits on one yes. Nothing sends without it.")),
  S("HOUR 21 - 24", "YOU <em>REVIEW.</em><br>YOU DO NOT<br>REBUILD.",
    "Twenty minutes of approvals <b>instead of a second working day.</b>",
    scene_gantt([dict(b="Doing it yourself", v="9h", p=100),
                 dict(b="Briefing and waiting", v="4h", p=48),
                 dict(b="Reviewing what arrived", v="20m", p=14, acc=True)],
                "THE SAME DAY, THREE WAYS"),
    ("HOUR 24", "The day ended. The work did not wait for tomorrow.")),
  S("WHAT ACTUALLY CHANGED", "YOU STOPPED<br>BEING YOUR OWN<br><em>EMPLOYEE.</em>",
    "Same company. Same day. <b>A different job inside it.</b>",
    scene_split(dict(u="BEFORE", b="DOING", i="every job on your own desk, in a queue"),
                dict(u="AFTER", b="DIRECTING", i="you decide, it executes, you approve"))),
  S("THE ASK", "TAKE THE<br>24 HOUR<br><em>SWITCH.</em>",
    "The three things to keep, and how to hand over the rest.",
    scene_key("CEO", "and I will send you the exact 24 hour switch.", "ALL ACCESS")),
])

# ---------------------------------------------------------------- 02 LAUNCH
D("clay-02-launch", "LAUNCH IN 24H", "LAUNCH", [
  S("ZERO CODE", "LAUNCH YOUR<br>PRODUCT IN<br>24 <em>HOURS.</em>",
    "Not a mockup. <b>A link you can send a customer tonight.</b>",
    scene_meter(72, "24h", "IDEA TO A REAL URL",
                [dict(b="Deciding what it is", v="1h", p=8),
                 dict(b="Building the whole thing", v="9h", p=62),
                 dict(b="Live and taking money", v="6h", p=40)],
                "YOU HAVE HAD THE IDEA FOR MONTHS"),
    ("THE GAP", "It was never the idea. It was the three weeks after it.")),
  S("HOUR 1", "DESCRIBE IT<br><em>ONCE.</em>",
    "One paragraph. What it does, and who it is for.",
    scene_thread([dict(t="a landing page, a signup, and a way to take payment"),
                  dict(t="writing the pages in your voice", you=True),
                  dict(t="signup wired, payment link live", you=True)],
                 "NO REPO, NO STACK, NO DEVELOPER"),
    ("PLAIN ENGLISH", "No forms to fill. One paragraph is the whole brief.")),
  S("HOUR 2 - 10", "IT <em>BUILDS</em><br>THE WHOLE<br>THING.",
    "Written from things you already said, <b>not from a template.</b>",
    scene_screen("yourproduct.com", "WHAT EXISTS NOW",
                 [dict(b="Landing page, in your voice", t="LIVE", acc=True),
                  dict(b="Signup that works", t="LIVE"),
                  dict(b="Payment link", t="LIVE", acc=True),
                  dict(b="Confirmation email", t="SENDING"),
                  dict(b="Lines of code you wrote", t="NONE")],
                 "BUILT WHILE YOU DID SOMETHING ELSE"),
    ("REAL", "Not a preview that expires. A URL that loads on your phone.")),
  S("HOUR 11 - 16", "IT GOES<br><em>LIVE</em> AND<br>CHECKS ITSELF.",
    "It opens the page and confirms it actually works.",
    scene_ladder([dict(k="STEP 1", b="Writes the pages"),
                  dict(k="STEP 2", b="Puts it on a real address"),
                  dict(k="STEP 3", b="Opens it like a customer would"),
                  dict(k="STEP 4", b="Confirms the payment goes through", acc=True)],
                 "WORK YOU MUST VERIFY IS NOT FINISHED"),
    ("VERIFIED", "It tested the signup before you ever saw it.")),
  S("HOUR 17 - 24", "YOU SEND<br>THE <em>LINK.</em>",
    "To a customer. <b>Not to a designer for feedback.</b>",
    scene_bill(("THE BILL", "24 HOURS"),
               [("Agency brief and revisions", "0"), ("Developer days", "0"),
                ("Lines of code you wrote", "0"), ("Weeks of waiting", "0"),
                ("Days from idea to a live URL", "1")],
               "TOTAL", "1 day"),
    ("CHANGES", "Another sentence, not another two weeks.")),
  S("WHAT ACTUALLY CHANGED", "YOU STOPPED<br><em>WAITING</em> ON<br>SOMEONE ELSE.",
    "The bottleneck was never the product.",
    scene_pillars([dict(b="Agency", v="6wk", p=100),
                   dict(b="Hiring a dev", v="3wk", p=52),
                   dict(b="This", v="1 day", p=12, acc=True)],
                  "IDEA TO SOMETHING REAL TO SHOW")),
  S("THE ASK", "TAKE THE<br>24 HOUR<br><em>BUILD.</em>",
    "How to brief it, and how it checks its own work.",
    scene_seal("LAUNCH", "and I will send you the 24 hour build.", "ALL ACCESS")),
])

# ---------------------------------------------------------------- 03 48H
D("clay-03-48h", "FIRST CUSTOMER", "48H", [
  S("THE 48 HOUR RUN", "YOUR FIRST<br>PAYING <em>CUSTOMER</em><br>IN 48 HOURS.",
    "No list bought. No team. <b>No agency.</b>",
    scene_clock("48", "HOURS",
                [dict(t="HOUR 1 - 4 &middot; find who would buy"),
                 dict(t="HOUR 5 - 12<br>reach them", acc=True),
                 dict(t="HOUR 31 - 48 &middot; ask for the money"),
                 dict(t="HOUR 13 - 30<br>give them<br>something", acc=True)],
                "TWO DAYS, FOUR MOVES"),
    ("START", "Two days is enough. Two months of planning is not.")),
  S("HOUR 1 - 4", "FIND <em>WHO</em><br>WOULD BUY.",
    "Forty companies, <b>and the person whose budget it comes from.</b>",
    scene_board("THE SHORT LIST",
                [dict(b="Northwind Systems", i="hiring two AEs this month", acc=True),
                 dict(b="Bellhaven Group", i="raised in March"),
                 dict(b="Calder and Vine", i="new ops lead, week two", acc=True),
                 dict(b="37 more", i="each with a reason, not a name")],
                "NOT A SCRAPED LIST"),
    ("WHY NOW", "Every one has a reason to care this week.")),
  S("HOUR 5 - 12", "REACH THEM<br>LIKE A <em>HUMAN.</em>",
    "One trigger, one question, <b>under sixty words.</b>",
    scene_gantt([dict(b="Written for you", v="40", p=100),
                 dict(b="You approved and sent", v="40", p=100),
                 dict(b="Replied", v="6", p=22, acc=True)],
                "WRITTEN FROM WHAT THEY ACTUALLY POSTED"),
    ("NOT A TEMPLATE", "A template with their name in it is still a template.")),
  S("HOUR 13 - 30", "GIVE THEM<br>SOMETHING<br>TO <em>OPEN.</em>",
    "A page built for this offer, <b>live by the time they reply.</b>",
    scene_thread([dict(t="interesting, send me something"),
                  dict(t="here is the page", you=True),
                  dict(t="that is exactly our problem")],
                 "MOST FIRST REPLIES DIE HERE"),
    ("THE REASON", "There was nothing on the other end of the link.")),
  S("HOUR 31 - 48", "ASK FOR<br>THE <em>MONEY.</em>",
    "The objection you were about to walk past, <b>answered first.</b>",
    scene_screen("app.51ultron.com", "DAY TWO",
                 [dict(b="Six replies, ranked", t="READY"),
                  dict(b="Objections answered in writing", t="DONE", acc=True),
                  dict(b="Price and terms drafted", t="WAITING"),
                  dict(b="First payment received", t="$49", acc=True)],
                 "MOST FIRST DEALS ARE LOST TO SILENCE"),
    ("NOT A NO", "Silence kills more first deals than a no ever does.")),
  S("WHAT ACTUALLY CHANGED", "YOU STOPPED<br><em>PLANNING</em><br>THE LAUNCH.",
    "Two days of doing it <b>beats two months preparing to.</b>",
    scene_arch([dict(b="Find", i="forty named, with a reason"),
                dict(b="Reach", i="one trigger, one question"),
                dict(b="Show", i="a page live before they reply"),
                dict(b="Ask", i="for the money, on day two", acc=True)],
               "NOBODY VALIDATES AN IDEA IN A DOCUMENT")),
  S("THE ASK", "TAKE THE<br>48 HOUR<br><em>RUN.</em>",
    "The order, the words, and where you approve.",
    scene_key("48H", "and I will send you the exact 48 hour run.", "ALL ACCESS")),
])

# ---------------------------------------------------------------- 04 NIGHT
D("clay-04-night", "WAKE UP SHIPPED", "NIGHT", [
  S("ONE NIGHT", "CLOSE THE<br>LAPTOP AT 11.<br>WAKE UP <em>SHIPPED.</em>",
    "Your company stops when you stop. <b>It does not have to.</b>",
    scene_stack([dict(u="23:47", b="You type one line and go to bed"),
                 dict(u="02:14", b="It builds the thing you postponed", acc=True),
                 dict(u="05:30", b="It opens what it made and checks it"),
                 dict(u="07:02", b="You read a result, not a to do list", acc=True)],
                "EIGHT HOURS YOU WERE NOT USING"),
    ("TONIGHT", "One sentence before bed. Nothing else.")),
  S("23:47", "ONE LINE<br>BEFORE <em>BED.</em>",
    "Not a spec. Not a ticket. <b>One sentence of what you want.</b>",
    scene_arch([dict(b="Type it", i="plain English, no forms"),
                dict(b="Sleep", i="nobody to brief in the morning"),
                dict(b="It runs", i="unattended, all night", acc=True),
                dict(b="Read it", i="finished, over coffee")],
               "NO STANDUP TO BOOK"),
    ("23:47", "The job you have moved to tomorrow four times.")),
  S("02:14", "IT DOES THE<br>WORK YOU<br><em>POSTPONED.</em>",
    "Reading the sources, writing the files, <b>running the build.</b>",
    scene_tower([dict(n="01", b="Reads what it needs", i="sources, and your own past work"),
                 dict(n="02", b="Writes the files", i="into the project, not into a chat", acc=True),
                 dict(n="03", b="Runs the build", i="and fixes it when it breaks")],
                "WHILE YOU SLEEP", "8 HOURS"),
    ("02:14", "Nobody is awake. The work is.")),
  S("05:30", "IT <em>CHECKS</em><br>ITS OWN WORK.",
    "Opens what it made and <b>confirms it actually works.</b>",
    scene_grid([dict(n="01", t="Opens the page"), dict(n="02", t="Clicks the signup"),
                dict(n="03", t="Runs the tests", acc=True), dict(n="04", t="Reads the errors"),
                dict(n="05", t="Fixes them", acc=True), dict(n="06", t="Runs them again"),
                dict(n="07", t="Confirms it loads"), dict(n="08", t="Writes what changed"),
                dict(n="09", t="Stops", acc=True)],
               "WORK YOU MUST VERIFY IS NOT FINISHED"),
    ("05:30", "Homework with extra steps is not a result.")),
  S("07:02", "YOU WAKE UP<br>TO A <em>RESULT.</em>",
    "Three things done, <b>sized and waiting for a yes.</b>",
    scene_board("WHAT WAS THERE AT 07:02",
                [dict(b="The page", i="live, open it on your phone", acc=True),
                 dict(b="This week's posts", i="written, sized, slotted"),
                 dict(b="The video", i="cut and ready", acc=True),
                 dict(b="What you typed", i="one line, at 23:47")],
                "FROM ONE SENTENCE"),
    ("07:02", "You approve. You do not start.")),
  S("WHAT ACTUALLY CHANGED", "THE DAY STOPPED<br>ENDING WHEN<br><em>YOU</em> DID.",
    "You did not find more hours. <b>You stopped being the thing they waited for.</b>",
    scene_meter(88, "3", "DONE BY 07:02",
                [dict(b="Hours you worked", v="0", p=4),
                 dict(b="Hours it worked", v="8", p=88),
                 dict(b="Things waiting on you at 07:02", v="1 yes", p=12)],
                "THE LIST YOU NEVER GET TO")),
  S("THE ASK", "TAKE THE<br>OVERNIGHT<br><em>RUN.</em>",
    "How to brief it at night, and how it verifies before it stops.",
    scene_seal("NIGHT", "and I will send you the overnight setup.", "ALL ACCESS")),
])

# ---------------------------------------------------------------- 05 POSTS
D("clay-05-posts", "30 DAYS IN AN HOUR", "POSTS", [
  S("ONE HOUR", "30 DAYS OF<br>POSTS IN<br>ONE <em>HOUR.</em>",
    "Not thirty posts. <b>Thirty days you never think about again.</b>",
    scene_grid([dict(n=str(d), t="", acc=(d in (3, 9, 14, 21, 27))) for d in range(1, 10)],
               "ONE HOUR OF WORK, A MONTH QUEUED"),
    ("WHY YOU STOP", "You stop on day four because every post starts blank.")),
  S("MINUTE 1 - 10", "IT READS<br>WHAT YOU<br>ALREADY <em>SAID.</em>",
    "Your posts, your decisions, <b>your numbers.</b>",
    scene_screen("app.51ultron.com", "WHAT IT READ",
                 [dict(b="Every post that already landed", t="YOURS", acc=True),
                  dict(b="The decisions you made, and why", t="YOURS"),
                  dict(b="Your real numbers, not rounded", t="YOURS", acc=True),
                  dict(b="How you actually write", t="READ"),
                  dict(b="A description of your voice", t="NOT USED")],
                 "IT READ YOUR VOICE, IT DID NOT IMITATE IT"),
    ("THE POINT", "Nobody can describe their own voice well enough to copy.")),
  S("MINUTE 11 - 25", "THIRTY <em>HOOKS</em><br>BEFORE ONE POST.",
    "The first line is the whole thing. <b>Write those first.</b>",
    scene_pillars([dict(b="Lines written", v="30", p=100),
                   dict(b="Worth a body", v="11", p=38, acc=True),
                   dict(b="Posted", v="9", p=30, acc=True)],
                  "ONLY A LINE THAT STOPS A SCROLL EARNS A POST"),
    ("THE FILTER", "Twenty one lines died so nine could work.")),
  S("MINUTE 26 - 45", "ONE IDEA.<br>THREE <em>CUTS.</em>",
    "A carousel, a short video and a written post <b>are not one post resized.</b>",
    scene_board("SAME IDEA, CUT THREE WAYS",
                [dict(b="Carousel", i="the one people save", acc=True),
                 dict(b="Short video", i="the one that travels"),
                 dict(b="Written post", i="the one people argue about", acc=True),
                 dict(b="One idea", i="underneath all three")],
                "CUT FOR THE PLACE IT IS GOING"),
    ("NOT RESIZED", "A resized post reads as a resized post.")),
  S("MINUTE 46 - 60", "A MONTH,<br><em>QUEUED.</em>",
    "Slotted for your window, <b>waiting on one approval.</b>",
    scene_gantt([dict(b="Deciding what to post", v="0m", p=6),
                 dict(b="Writing it", v="0m", p=6),
                 dict(b="Approving the month", v="14m", p=32, acc=True)],
                "YOU SAY YES ONCE INSTEAD OF THIRTY TIMES"),
    ("THEN STOP", "You stop thinking about it for thirty days.")),
  S("WHAT ACTUALLY CHANGED", "CONSISTENCY<br>STOPPED BEING<br><em>DISCIPLINE.</em>",
    "Nobody posts daily on willpower.",
    scene_clock("30", "DAYS",
                [dict(t="WRITTEN BEFORE THE DAY STARTED"),
                 dict(t="ONE<br>HOUR", acc=True),
                 dict(t="POSTED WITHOUT A DECISION"),
                 dict(t="ONE<br>YES", acc=True)],
                "THEY POST DAILY BECAUSE IT WAS ALREADY WRITTEN")),
  S("THE ASK", "TAKE THE<br>ONE HOUR<br><em>RUN.</em>",
    "Angles, thirty hooks, the cuts and the queue.",
    scene_key("POSTS", "and I will send you the one hour content run.", "ALL ACCESS")),
])

# ---------------------------------------------------------------- 06 72H
D("clay-06-72h", "IDEA TO REVENUE", "72H", [
  S("ONE WEEK", "IDEA <em>MONDAY.</em><br>REVENUE<br><em>THURSDAY.</em>",
    "The whole arc, <b>inside one working week.</b>",
    scene_ladder([dict(k="MONDAY", b="Test it before you build it"),
                  dict(k="TUESDAY", b="Build the smallest real version"),
                  dict(k="WEDNESDAY", b="Put it in front of forty people"),
                  dict(k="THURSDAY", b="The first one pays", acc=True)],
                 "FOUR DAYS, NOT FOUR MONTHS"),
    ("THE GAP", "Ideas die between having them and having something to show.")),
  S("MONDAY", "TEST IT<br>BEFORE YOU<br><em>BUILD</em> IT.",
    "Who has this problem, <b>and do they pay for anything near it today.</b>",
    scene_pillars([dict(b="Companies like this", v="900", p=100),
                   dict(b="Already paying for near", v="240", p=44),
                   dict(b="Underserved", v="61", p=18, acc=True)],
                  "AN AFTERNOON OF CHECKING"),
    ("MONDAY", "Beats a month of building the wrong thing.")),
  S("TUESDAY", "BUILD THE<br>SMALLEST <em>REAL</em><br>VERSION.",
    "Live, takes money, <b>does one thing properly.</b>",
    scene_split(dict(u="A WAITLIST", b="0", i="collects emails and proves nothing"),
                dict(u="LIVE AND PRICED", b="1", i="can take money this afternoon"))),
  S("WEDNESDAY", "PUT IT IN<br>FRONT OF<br>FORTY <em>PEOPLE.</em>",
    "Named, reachable, <b>and picked for a reason.</b>",
    scene_bill(("WEDNESDAY", "THE SEND LIST"),
               [("Named people", "40"), ("Scraped addresses", "0"),
                ("Written from a real signal", "40"), ("Approved by you", "40"),
                ("Sent without you reading it", "0")],
               "SENT", "40"),
    ("WEDNESDAY", "Forty right people beats four hundred addresses.")),
  S("THURSDAY", "THE FIRST<br>ONE <em>PAYS.</em>",
    "Not validation. <b>Money, from someone you did not know on Monday.</b>",
    scene_thread([dict(t="saw the page, this is our problem"),
                  dict(t="here is how it works and what it costs", you=True),
                  dict(t="payment received, day four", you=True)],
                 "ONE PAYING CUSTOMER TELLS YOU MORE THAN A HUNDRED CALLS"),
    ("THURSDAY", "A hundred conversations never told you this much.")),
  S("WHAT ACTUALLY CHANGED", "YOU STOPPED<br><em>RESEARCHING</em><br>AND SHIPPED.",
    "The week was never the constraint.",
    scene_tower([dict(n="4", b="days", i="idea to a paying customer"),
                 dict(n="1", b="person", i="no team, no agency", acc=True),
                 dict(n="0", b="code", i="you wrote none of it")],
                "THE CONSTRAINT WAS", "FINDING OUT")),
  S("THE ASK", "TAKE THE<br>FOUR DAY<br><em>RUN.</em>",
    "What to test Monday, and what to ship Tuesday.",
    scene_seal("72H", "and I will send you the four day run.", "ALL ACCESS")),
])

# ---------------------------------------------------------------- 07 TEN
D("clay-07-ten", "TEAM OF TEN", "TEN", [
  S("FOUR HOURS", "WORK FOUR<br>HOURS. SHIP<br>LIKE <em>TEN.</em>",
    "Not a productivity trick. <b>A different number of things running at once.</b>",
    scene_board("RUNNING RIGHT NOW",
                [dict(b="Research", i="forty accounts, ranked", acc=True),
                 dict(b="Outreach", i="written, held for you"),
                 dict(b="The page", i="built and verified", acc=True),
                 dict(b="This week's posts", i="written and slotted")],
                "ELEVEN JOBS, ONE PERSON"),
    ("THE CEILING", "One person does one job at a time. That was the ceiling.")),
  S("09:00", "YOU START<br><em>ELEVEN</em> JOBS.",
    "In about four minutes. <b>One line each, plain English.</b>",
    scene_clock("11", "AT ONCE",
                [dict(t="RESEARCH &middot; OUTREACH &middot; THE PAGE"),
                 dict(t="FOUR<br>MINUTES", acc=True),
                 dict(t="POSTS &middot; CONTRACT &middot; FOLLOW UPS"),
                 dict(t="ONE LINE<br>EACH", acc=True)],
                "STARTED BEFORE YOUR COFFEE WENT COLD"),
    ("09:04", "Eleven jobs started. None of them need you again.")),
  S("10:30", "THEY RUN<br><em>WITHOUT</em><br>YOU.",
    "No standup, no handover, <b>nobody waiting on your reply.</b>",
    scene_screen("app.51ultron.com", "10:30",
                 [dict(b="Research", t="DONE", acc=True),
                  dict(b="Outreach", t="WAITING"),
                  dict(b="The page", t="DONE", acc=True),
                  dict(b="The contract", t="RUNNING"),
                  dict(b="Follow ups", t="SENT")],
                 "THE WORK THAT USED TO QUEUE BEHIND YOU"),
    ("10:30", "You have not answered a single question.")),
  S("12:00", "THEY HAND<br>OFF TO <em>EACH</em><br>OTHER.",
    "What the research found <b>is what the outreach is written from.</b>",
    scene_gantt([dict(b="Alone, one job at a time", v="1", p=100),
                 dict(b="Together, handing off", v="11", p=40, acc=True)],
                "A TEAM OF FREELANCERS NEVER DOES THIS"),
    ("THE DIFFERENCE", "One context, held across all of it.")),
  S("13:00", "YOU <em>APPROVE</em><br>AND CLOSE<br>THE LAPTOP.",
    "Eleven finished things, one review pass, <b>four hours.</b>",
    scene_stack([dict(u="WHAT IT FOUND", b="feeds what it writes"),
                 dict(u="WHAT IT WROTE", b="feeds what it builds", acc=True),
                 dict(u="ONE CONTEXT", b="held across all eleven"),
                 dict(u="YOUR PASS", b="reading, not redoing", acc=True)],
                "IT ARRIVES CHECKED"),
    ("13:00", "Reviewing is reading. It is not redoing.")),
  S("WHAT ACTUALLY CHANGED", "YOU STOPPED<br>BEING THE<br><em>QUEUE.</em>",
    "Everything used to wait its turn behind you.",
    scene_grid([dict(n="1", t="job at a time"), dict(n="8h", t="a working day"),
                dict(n="1", t="of you", acc=True), dict(n="11", t="jobs at once"),
                dict(n="4h", t="a working day", acc=True), dict(n="1", t="of you"),
                dict(n="0", t="standups"), dict(n="0", t="handovers", acc=True),
                dict(n="1", t="review pass")],
               "YOUR DAY WAS NEVER SHORT. IT WAS SINGLE THREADED.")),
  S("THE ASK", "TAKE THE<br>FOUR HOUR<br><em>DAY.</em>",
    "The eleven jobs, and how to start them all at once.",
    scene_key("TEN", "and I will send you the four hour day.", "ALL ACCESS")),
])

# ---------------------------------------------------------------- 08 INVESTORS
D("clay-08-investors", "THEY CALL BACK", "INVESTORS", [
  S("48 HOURS", "BECOME THE<br>FOUNDER THEY<br><em>CALL BACK.</em>",
    "Nobody passes because the deck was ugly.",
    scene_bill(("THE ASK", "48 HOURS OUT"),
               [("Numbers pulled, not remembered", "yes"), ("Cohorts charted", "yes"),
                ("Cap table in order", "yes"), ("Objections answered in writing", "20"),
                ("Questions you have not thought about", "0")],
               "READY", "48h"),
    ("THE REAL REASON", "They pass because the second answer was not ready.")),
  S("HOUR 1 - 6", "YOUR OWN<br><em>NUMBERS</em><br>FIRST.",
    "Pulled from what actually happened, <b>not from a memory of it.</b>",
    scene_meter(64, "4", "NUMBERS THEY ALWAYS ASK FOR",
                [dict(b="Growth, month over month", v="pulled", p=100),
                 dict(b="Retention by cohort", v="pulled", p=88),
                 dict(b="What a customer costs", v="pulled", p=72),
                 dict(b="What a customer is worth", v="pulled", p=64)],
                "FROM THE SYSTEM, NOT FROM MEMORY"),
    ("HOUR 6", "You can answer without saying you will follow up.")),
  S("HOUR 7 - 20", "THE <em>STORY</em><br>THOSE NUMBERS<br>TELL.",
    "Not the story you wish they told.",
    scene_thread([dict(t="what is not working yet?"),
                  dict(t="churn above forty seats, here is the cohort", you=True),
                  dict(t="good. most founders hide that one")],
                 "WHERE YOU ARE EARLY, AND WHAT THE MONEY BUYS"),
    ("THE TEST", "The honest answer is the one that gets a second call.")),
  S("HOUR 21 - 36", "THE ROOM<br>THEY <em>ASK</em><br>FOR NEXT.",
    "The one you scramble to build <b>after the first good call.</b>",
    scene_tower([dict(n="01", b="The model", i="assumptions you can stand behind"),
                 dict(n="02", b="The cohorts", i="the chart they always request", acc=True),
                 dict(n="03", b="The paper", i="contracts and cap table, in order")],
                "ASSEMBLED WHILE THE CALL IS STILL WARM", "36h"),
    ("HOUR 36", "It exists before they ask, not after.")),
  S("HOUR 37 - 48", "THE <em>QUESTION</em><br>BEFORE THEY<br>ASK IT.",
    "Twenty objections, answered in writing, <b>before the second call.</b>",
    scene_stack([dict(u="MARKET", b="why this is bigger than it looks"),
                 dict(u="CHURN", b="what happens above forty seats", acc=True),
                 dict(u="MOAT", b="what a competitor cannot copy"),
                 dict(u="TEAM", b="why these people, now", acc=True)],
                "THE ONE THAT KILLS THE ROUND IS NEVER THE REHEARSED ONE"),
    ("HOUR 48", "You are not surprised in the room. That is the whole trick.")),
  S("WHAT ACTUALLY CHANGED", "YOU STOPPED<br>SOUNDING<br><em>EARLY.</em>",
    "Same company. Same numbers. <b>A different conversation.</b>",
    scene_split(dict(u="BEFORE", b="EARLY", i="answers that arrive a week after the call"),
                dict(u="AFTER", b="READY", i="answered in the room, from real numbers"))),
  S("THE ASK", "TAKE THE<br>48 HOUR<br><em>PREP.</em>",
    "The numbers to pull, and the twenty questions.",
    scene_seal("INVESTORS", "and I will send you the 48 hour prep.", "ALL ACCESS")),
])


# ---------------------------------------------------------------- 09 THE NEW JOB
# Rides the side-income demand the operator measured (#sidehustle 6.2M, #workfromhome 7.9M)
# without the genre's invented earnings claims. Every number here is published and dated:
# GTM engineering postings roughly doubled from ~1,400 mid-2025 to 3,000+ by January 2026,
# 205% year on year growth through 2025, 54% of the fastest growing B2B SaaS companies have
# one (Clay and The Signal), and the reported band is $132K to $241K. The backlog logged this
# as candidate 4 and marked it clean against every shipped episode.
D("clay-09-engineer", "THE NEW JOB", "ENGINEER", [
  S("A JOB TITLE FROM 2025", "THE JOB THAT<br>DID NOT EXIST<br>TWO <em>YEARS AGO.</em>",
    "Postings roughly doubled in six months. <b>Most founders are already doing it unpaid.</b>",
    scene_pillars([dict(b="Mid 2025", v="1.4k", p=42),
                   dict(b="Jan 2026", v="3k+", p=100, acc=True),
                   dict(b="Growth", v="205%", p=70, acc=True)],
                  "GTM ENGINEER POSTINGS, YEAR ON YEAR"),
    ("THE POINT", "You have been doing this job at 2am without the title.")),
  S("WHAT IT REPLACES", "ONE PERSON<br>SHIPS WHAT TOOK<br><em>FIVE.</em>",
    "Not a smaller team. <b>A different shape of one.</b>",
    scene_gantt([dict(b="A five person revenue team", v="5", p=100),
                 dict(b="One operator with AI running it", v="1", p=22, acc=True)],
                "WHAT USED TO NEED A DEPARTMENT"),
    ("THE SHIFT", "The work did not shrink. The number of people running it did.")),
  S("WHAT THE JOB IS", "FOUR THINGS,<br>ALL OF THEM<br><em>YOURS</em> ALREADY.",
    "Nothing here is new to you. <b>Only the fact that it has a name now.</b>",
    scene_board("THE ACTUAL DUTIES",
                [dict(b="Find who to talk to", i="and why this week", acc=True),
                 dict(b="Write what gets sent", i="in a voice that is yours"),
                 dict(b="Build the thing they open", i="a page, a demo, a doc", acc=True),
                 dict(b="Know what happened", i="numbers, not a feeling")],
                "54% OF THE FASTEST GROWING SAAS COMPANIES HIRE FOR THIS"),
    ("THE CATCH", "At two to fifty people you cannot hire it. You run it.")),
  S("HOW YOU START", "YOU CAN RUN IT<br>BY <em>FRIDAY.</em>",
    "No new hire, no new tool to learn. <b>Four moves.</b>",
    scene_arch([dict(b="Name forty accounts", i="with a reason each, not a scrape"),
                dict(b="Write to them like a person", i="one trigger, one question"),
                dict(b="Give them something to open", i="live before they reply", acc=True),
                dict(b="Read what actually happened", i="and change one thing")],
               "THE WHOLE JOB, IN FOUR MOVES"),
    ("BY FRIDAY", "One week is enough to run it once properly.")),
  S("WHAT IT RUNS ON", "ONE OPERATOR.<br>ELEVEN JOBS.<br>ONE <em>SCREEN.</em>",
    "The reason one person can hold it now.",
    scene_screen("app.51ultron.com", "THE DESK",
                 [dict(b="Accounts researched and ranked", t="RUNNING", acc=True),
                  dict(b="Outreach written, held for you", t="WAITING"),
                  dict(b="The page they will open", t="LIVE", acc=True),
                  dict(b="Contracts read and flagged", t="DONE"),
                  dict(b="What worked, in numbers", t="READ")],
                 "ONE CONTEXT ACROSS ALL OF IT"),
    ("THE DIFFERENCE", "A stack of tools makes you the integration.")),
  S("WHAT ACTUALLY CHANGED", "THE TITLE<br>CAUGHT UP<br>TO THE <em>WORK.</em>",
    "Reported band for the role: <b>$132K to $241K.</b>",
    scene_split(dict(u="TWO YEARS AGO", b="NO NAME", i="you did it after hours and called it admin"),
                dict(u="NOW", b="A ROLE", i="postings doubled in six months"))),
  S("THE ASK", "TAKE THE<br>ONE WEEK<br><em>RUN.</em>",
    "The four moves, and what to run on which day.",
    scene_key("ENGINEER", "and I will send you the one week run.", "ALL ACCESS")),
])

# ---------------------------------------------------------------- 10 THE SETUP
# Rides the "Claude tips" demand (#aihacks, #claudeai) the operator measured. The researched
# outline invents a `/ghost` command; nothing here is invented. These are three real habits,
# and the fix for each is behaviour this repo has already filmed, so the product answer is a
# feature rather than a claim.
D("clay-10-setup", "THREE THINGS", "SETUP", [
  S("MOST PEOPLE", "YOU ARE USING<br><em>CLAUDE</em> LIKE<br>A SEARCH BOX.",
    "It answers well. <b>Then you close the tab and it forgets you.</b>",
    scene_thread([dict(t="here is my company, here is what we sell, here is my ICP..."),
                  dict(t="great, what would you like help with?", you=True),
                  dict(t="...and tomorrow you type all of it again")],
                 "THE LOOP MOST FOUNDERS NEVER LEAVE"),
    ("MISTAKE 1", "You re-explain your company every single morning.")),
  S("MISTAKE ONE", "YOU START<br>FROM <em>ZERO</em><br>EVERY TIME.",
    "Your context is the most valuable thing you own. <b>Type it once.</b>",
    scene_stack([dict(u="WHAT YOU SELL", b="written once, read every time"),
                 dict(u="WHO BUYS IT", b="the ICP, not a description of it", acc=True),
                 dict(u="HOW YOU WRITE", b="read from your posts, not imitated"),
                 dict(u="WHAT YOU DECIDED", b="and why, so it stops re-asking", acc=True)],
                "CONTEXT HELD, NOT RETYPED"),
    ("THE FIX", "Written once. Applied to everything after it.")),
  S("MISTAKE TWO", "YOU ASK FOR A<br><em>DRAFT.</em> YOU GET<br>HOMEWORK.",
    "A draft moves the work back to you. <b>Ask for the finished thing.</b>",
    scene_desk("WHAT YOU ASKED FOR", "COMPARE", [
        dict(b="write me a draft email", i="you now edit it for twenty minutes", t="DRAFT"),
        dict(b="write it, check the facts, and hold it", i="you approve or you do not",
             t="FINISHED", acc=True),
        dict(b="give me some ideas", i="you now do the choosing", t="DRAFT"),
        dict(b="pick one and tell me why", i="a decision you can argue with",
             t="FINISHED", acc=True)],
        "THE WORDING IS THE WHOLE DIFFERENCE"),
    ("THE FIX", "Ask for the thing, the check, and the hold.")),
  S("MISTAKE THREE", "YOU SIT AND<br><em>WATCH</em> IT<br>WORK.",
    "If you have to be there, it is not finished. <b>It is supervised.</b>",
    scene_grid([dict(n="1", t="you type"), dict(n="2", t="you wait"),
                dict(n="3", t="you read", acc=True), dict(n="4", t="you correct"),
                dict(n="5", t="you wait", acc=True), dict(n="6", t="you read"),
                dict(n="7", t="you paste"), dict(n="8", t="you send", acc=True),
                dict(n="0", t="hours it saved")],
               "SUPERVISED WORK IS STILL YOUR WORK"),
    ("THE FIX", "Brief it, leave, and come back to a result.")),
  S("THE ORDER", "THREE FIXES.<br>ABOUT <em>TWENTY</em><br>MINUTES.",
    "You do this once and never think about it again.",
    scene_ladder([dict(k="MINUTE 1", b="Write your context down once"),
                  dict(k="MINUTE 6", b="Ask for finished things, not drafts"),
                  dict(k="MINUTE 12", b="Brief a job and walk away"),
                  dict(k="MINUTE 20", b="Read what came back and approve", acc=True)],
                 "ONCE, NOT EVERY MORNING"),
    ("TWENTY MINUTES", "The setup most people never do is the whole difference.")),
  S("WHAT ACTUALLY CHANGED", "IT STOPPED<br>BEING A <em>CHAT.</em><br>IT STARTED WORKING.",
    "Same model. Same day. <b>A different relationship with it.</b>",
    scene_meter(84, "0", "TIMES YOU EXPLAIN YOURSELF AGAIN",
                [dict(b="Context you retype each morning", v="none", p=6),
                 dict(b="Work that comes back finished", v="most", p=84),
                 dict(b="Jobs that need you in the room", v="few", p=18)],
                "THE MODEL WAS NEVER THE PROBLEM")),
  S("THE ASK", "TAKE THE<br>TWENTY MINUTE<br><em>SETUP.</em>",
    "The three fixes, in the order that makes each one stick.",
    scene_seal("SETUP", "and I will send you the twenty minute setup.", "ALL ACCESS")),
])


def main():
    fail, seen, openers, used = [], {}, {}, set()
    for d in DECKS:
        slug, run = d["slug"], d["run"]
        dupes = {o for o in run if run.count(o) > 1}
        if dupes:
            fail.append(f"{slug} reuses {', '.join(sorted(dupes))} within the deck")
        key = ",".join(run)
        if key in seen:
            fail.append(f"{slug} repeats the object run of {seen[key]}")
        seen[key] = slug
        if run[0] in openers:
            fail.append(f"{slug} opens on {run[0]}, same as {openers[run[0]]}")
        openers[run[0]] = slug
        used.update(run)
    if fail:
        sys.exit("GRAPHIC VARIETY:\n  " + "\n  ".join(fail))
    for d in DECKS:
        p = build(d["slug"], d["title"], d["slides"])
        print(f"  {p.name:22} {len(d['slides'])} slides  {d['kw']:9} {','.join(d['run'])}")
    print(f"{len(DECKS)} decks, {len(used)} forms in use, every run unique, "
          f"no form twice in a deck, every deck opens differently")


if __name__ == "__main__":
    main()
