#!/usr/bin/env python3
"""Bake the webfonts into a self-contained stylesheet.

Every material in this repo links Google Fonts with a <link> tag, and the export renderer
cannot reach it: headless Chromium in this sandbox gets no network, so `document.fonts` comes
back EMPTY and Anton, DM Sans, DM Mono and Instrument Serif all silently fall back to the
default grotesque. The pages looked deliberate on screen and shipped in the wrong typeface.

`_preflight.py` did not catch it because it read the @import line, which lists four families
whether or not any of them loaded. It now measures a real string instead (see check_fonts).

curl reaches the internet through the agent proxy even though the renderer does not, which is
the same fetch/verify/inline flow `_img.py` uses for images (CLAUDE.md 18). This fetches the
CSS with a browser user agent so Google serves woff2, pulls each font file, and rewrites the
URLs to data URIs. Latin subsets only, which is what these materials set.

Usage:
  python3 content/_fonts.py               # (re)build content/assets/fonts.css
  python3 content/_fonts.py --check       # report what is cached
"""
import base64, pathlib, re, subprocess, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
ASSETS = ROOT / "content" / "assets"
OUT = ASSETS / "fonts.css"

UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) "
      "Chrome/120.0.0.0 Safari/537.36")
SPEC = ("https://fonts.googleapis.com/css2?"
        "family=DM+Sans:opsz,wght@9..40,400;9..40,500;9..40,700;9..40,800;9..40,900"
        "&family=DM+Mono:wght@400;500&family=Anton&family=Instrument+Serif:ital@0;1"
        "&display=swap")


def curl(url: str, binary=False):
    r = subprocess.run(["curl", "-sS", "-A", UA, "--max-time", "60", url],
                       capture_output=True)
    if r.returncode != 0 or not r.stdout:
        sys.exit(f"fetch failed: {url}\n{r.stderr.decode()[:200]}")
    return r.stdout if binary else r.stdout.decode()


def build() -> pathlib.Path:
    ASSETS.mkdir(parents=True, exist_ok=True)
    css = curl(SPEC)
    blocks = re.findall(r"/\*\s*([\w\-\[\]]+)\s*\*/\s*(@font-face\s*\{.*?\})", css, re.S)
    if not blocks:
        blocks = [("latin", b) for b in re.findall(r"@font-face\s*\{.*?\}", css, re.S)]

    kept, cache, total = [], {}, 0
    for subset, block in blocks:
        # latin only: latin-ext and the rest double the payload for glyphs these never set
        if subset not in ("latin",):
            continue
        for url in re.findall(r"url\((https://[^)]+\.woff2)\)", block):
            if url not in cache:
                raw = curl(url, binary=True)
                if raw[:4] != b"wOF2":
                    sys.exit(f"not a woff2: {url}")
                cache[url] = "data:font/woff2;base64," + base64.b64encode(raw).decode()
                total += len(raw)
            block = block.replace(url, cache[url])
        kept.append(block.strip())

    header = ("/* Generated by content/_fonts.py. Do not edit.\n"
              "   The renderer has no network, so these are embedded rather than linked.\n"
              f"   {len(kept)} faces, {len(cache)} files, {total/1024:.0f} KB of woff2. */\n")
    OUT.write_text(header + "\n".join(kept) + "\n")
    print(f"  {OUT.relative_to(ROOT)}  {len(kept)} faces from {len(cache)} files, "
          f"{OUT.stat().st_size/1024:.0f} KB")
    fams = sorted({m for b in kept for m in re.findall(r"font-family:\s*'([^']+)'", b)})
    print(f"  families: {', '.join(fams)}")
    return OUT


def embedded_css() -> str:
    """The stylesheet text, for pages that inline it."""
    if not OUT.exists():
        build()
    return OUT.read_text()


if __name__ == "__main__":
    if "--check" in sys.argv:
        print(f"{OUT}: {'present, %.0f KB' % (OUT.stat().st_size/1024) if OUT.exists() else 'MISSING'}")
    else:
        build()
