#!/usr/bin/env python3
import base64, importlib.util, pathlib, html
REPO=pathlib.Path('/work'); OUT=REPO/'content/ultron-chatgpt-vs-claude-native.html'; ACC='#C84623'
def embedded(p): return 'data:image/svg+xml;base64,'+base64.b64encode(p.read_bytes()).decode()
def fonts():
 s=importlib.util.spec_from_file_location('_fonts',REPO/'content/_fonts.py'); m=importlib.util.module_from_spec(s); s.loader.exec_module(m); return m.embedded_css()
L=[('▧','An image for the ad','Claude generates none'),('◉','Hands-free thinking','voice mode, while you drive'),('◎','What changed this week','live web, with sources'),('↗','Click through a site for you','computer use'),('✦','A reusable team assistant','a custom GPT'),('▤','A multi-source brief','deep research'),('▦','A photo turned into data','vision, then a table')]
R=[('▤','A 300-page doc in one go','200K context, no chunking'),('□','A working page in the chat','Artifacts'),('◇','Your product, actually built','Claude Code'),('✎','Copy nobody clocks as AI','the writing model'),('▰','One private space per client','Projects'),('☑','A 20-step brief, followed','instruction following'),('✓','A check you can trust','fewer hallucinations')]
def rows(items,side):
 return ''.join(f'<div class="row {side}"><span class="ico">{i}</span><div><div class="title">{html.escape(t)}</div><div class="sub">{html.escape(s)}</div></div></div>' for i,t,s in items)
openai=embedded(REPO/'content/assets/icons/openai.svg'); claude=embedded(REPO/'content/assets/icons/claude-color.svg')
css=f'''{fonts()}\n/* FILM-META {{"duration":7.0,"w":1080,"h":1350,"fps":30,"beats":[{{"from":0,"to":3,"name":"reveal"}}]}} */\n:root{{--acc:{ACC};--ink:#111;--muted:#747474}}*{{box-sizing:border-box;margin:0;padding:0}}body{{background:#fff;color:var(--ink);font-family:'DM Sans',Arial,sans-serif}}#film{{position:relative;width:1080px;height:1350px;overflow:hidden;background:#fff}}.header{{position:absolute;top:0;left:0;width:1080px;height:187px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:5px;background:#111;color:#fff;z-index:5}}.h1{{font-size:58px;font-weight:800;letter-spacing:-2.2px;line-height:1.05}}.h2{{font-size:56px;font-weight:800;letter-spacing:-2.2px;line-height:1.05}}.h2 em{{font-style:normal;color:#fff}}.body{{position:absolute;top:187px;left:0;width:1080px;height:1003px;padding:0 58px;background:#fff}}.columns{{display:grid;grid-template-columns:1fr 1fr;column-gap:54px;height:100%;position:relative}}.columns::after{{content:"";position:absolute;left:50%;top:90px;bottom:38px;width:1px;background:#ededed}}.col{{position:relative;padding-top:26px;z-index:1}}.brand{{height:68px;display:flex;align-items:center;justify-content:center;gap:12px;font-size:31px;font-weight:800}}.brand img{{width:38px;height:38px;object-fit:contain}}.brand.right img{{width:42px;height:42px}}.vs{{position:absolute;top:80px;left:50%;transform:translateX(-50%);font-size:15px;font-weight:800;background:#fff;padding:9px 10px;z-index:2}}.row{{height:125px;display:flex;align-items:center;gap:18px;padding:0 24px;position:relative}}.ico{{width:40px;height:40px;display:grid;place-items:center;font-size:25px;line-height:1;flex:0 0 40px}}.row.left .ico{{color:#222}}.row.right .ico{{color:var(--acc)}}.title{{font-size:23px;font-weight:750;line-height:1.15;white-space:nowrap;color:var(--ink)}}.sub{{font-size:17px;font-weight:500;color:var(--muted);margin-top:7px;white-space:nowrap}}.footer{{position:absolute;left:0;top:1190px;width:1080px;height:160px;background:#fff;display:flex;align-items:center;justify-content:center;z-index:3}}.footer span{{font-size:31px;font-weight:750;white-space:nowrap}}.footer em{{font-style:normal;color:var(--acc)}}.veil{{position:absolute;left:0;top:187px;width:1080px;height:1163px;background:#000;opacity:.982;z-index:4;pointer-events:none;animation:reveal 3s linear forwards}}@keyframes reveal{{from{{opacity:.982}}to{{opacity:0}}}}'''
html_out=f'''<!doctype html><html><head><meta charset="utf-8"><title>People who use ChatGPT vs Claude</title><style>{css}</style></head><body><main id="film"><header class="header"><div class="h1">People who use</div><div class="h2">ChatGPT vs <em>Claude</em></div></header><section class="body"><div class="columns"><div class="col"><div class="brand"><img src="{openai}">ChatGPT</div>{rows(L,'left')}</div><div class="col"><div class="brand right"><img src="{claude}">Claude</div>{rows(R,'right')}</div></div></section><footer class="footer"><span>↓ Comment <em>CLAUDE</em> for the full breakdown</span></footer><div class="veil"></div></main></body></html>'''
OUT.write_text(html_out); print(f'generated {OUT}; imported body image: none; borders: none; CTA: comment')
