#!/usr/bin/env python3
import importlib.util, pathlib, html
ROOT=pathlib.Path('/work'); OUT=ROOT/'content/ultron-ai-business-models-v2.html'
def font_css():
 spec=importlib.util.spec_from_file_location('_fonts', ROOT/'content/_fonts.py')
 mod=importlib.util.module_from_spec(spec); spec.loader.exec_module(mod)
 return mod.embedded_css()
steps=[('⌕','Research','Find a market with a clear pain'),('◌','Build','Ship the smallest useful version'),('●','Decide','Keep the calls that need judgment'),('↗','Scale','Let the system create repeatable revenue')]
models=[
 ('⚒','Boring tool empire'),('⌖','Local directory factory'),('$','Too-expensive SaaS hunter'),('□','Digital product factory'),('↗','Affiliate SEO empire'),('⚙','AI workflow factory'),('◉','Game factory'),('✉','Cold email lead machine'),('▤','Data product factory'),('🚀','Startup opportunity finder')]
step_html=''.join(f'<article class="step"><span class="step-icon">{i}</span><div><strong>{html.escape(a)}</strong><small>{html.escape(b)}</small></div></article>'+('<span class="down">↓</span>' if n<3 else '') for n,(i,a,b) in enumerate(steps))
model_html=''.join(f'<article class="model p{n}"><span>{i}</span><b>{n+1:02d}</b><small>{html.escape(t)}</small></article>' for n,(i,t) in enumerate(models))
css='''
/* FILM-META {"duration":7.0,"w":1080,"h":1350,"fps":30,"beats":[{"from":0,"to":3,"name":"reveal"}]} */
:root{--ink:#17233d;--purple:#7356c8;--mint:#4ca878;--cream:#fbf9f2;--rule:#c8c7c2}
*{box-sizing:border-box;margin:0;padding:0}body{background:#000;font-family:'DM Sans',Arial,sans-serif;color:var(--ink)}#film{position:relative;width:1080px;height:1350px;overflow:hidden;background:var(--cream)}
.header{position:absolute;inset:0 0 auto 0;height:220px;background:#101010;color:#fff;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;z-index:3}.header h1{font-size:64px;line-height:1;font-weight:850;letter-spacing:-2.4px}.header p{font-size:31px;line-height:1.1;font-weight:400;margin-top:15px;letter-spacing:-.6px}
.body{position:absolute;top:220px;left:0;width:1080px;height:970px;background:var(--cream);padding:42px 56px 26px;display:grid;grid-template-columns:338px 1fr;gap:38px}.process{height:100%;padding:16px 32px 14px 0;border-right:1px solid var(--rule);display:flex;flex-direction:column;justify-content:space-between}.eyebrow{font-size:16px;font-weight:800;letter-spacing:1.6px;color:var(--purple);margin-bottom:4px}.step{display:flex;align-items:center;gap:16px}.step-icon{display:grid;place-items:center;width:62px;height:62px;border-radius:50%;background:#eee9fb;color:var(--purple);font-size:30px;font-weight:800;flex:none}.step:last-of-type .step-icon{background:#dff2e5;color:var(--mint)}.step strong{display:block;font-size:25px;line-height:1.05}.step small{display:block;margin-top:6px;font-size:16px;line-height:1.2;color:#5d687a}.down{height:20px;margin-left:22px;color:#364054;font-size:25px;line-height:.8}
.system{position:relative;height:100%}.system h2{position:absolute;top:0;left:0;font-size:17px;font-weight:800;letter-spacing:1.5px;color:var(--purple)}.orbit{position:absolute;left:72px;top:90px;width:510px;height:510px;border:2px dashed #aeb2b8;border-radius:50%}.orbit::after{content:"";position:absolute;inset:33px;border:1px solid #e6e3dd;border-radius:50%}.laptop{position:absolute;left:220px;top:260px;width:220px;height:138px;border:5px solid #3d4a5a;border-radius:11px 11px 5px 5px;background:#8e99a7;z-index:2;box-shadow:0 10px 0 -5px #64707e}.screen{position:absolute;inset:14px;background:#1c2b40;border-radius:4px;display:grid;place-items:center;color:#a68be9;font-size:54px;font-weight:850}.screen i{font-style:normal;position:absolute;right:17px;top:8px;color:#fff;font-size:18px}.base{position:absolute;left:192px;top:406px;width:277px;height:23px;border:3px solid #3d4a5a;border-radius:4px 4px 16px 16px;background:#7d8998;z-index:2}.model{position:absolute;width:156px;min-height:48px;display:grid;grid-template-columns:34px 24px 1fr;align-items:center;gap:7px;z-index:2}.model>span{display:grid;place-items:center;width:32px;height:32px;border:2px solid var(--purple);border-radius:8px;background:#f3efff;color:var(--purple);font-size:16px}.model b{font-size:13px;color:var(--purple)}.model small{font-size:14px;line-height:1.05;font-weight:800;color:#27354c;text-transform:uppercase}.p0{left:237px;top:58px}.p1{left:442px;top:113px}.p2{left:514px;top:238px}.p3{left:480px;top:389px}.p4{left:345px;top:520px}.p5{left:205px;top:637px}.p6{left:35px;top:520px}.p7{left:-10px;top:389px}.p8{left:0;top:238px}.p9{left:42px;top:113px}
.footer{position:absolute;top:1190px;left:0;width:1080px;height:160px;display:flex;align-items:center;justify-content:center;background:var(--cream);font-size:31px;font-weight:700;color:var(--ink);z-index:3}.footer em{color:var(--purple);font-style:normal;font-weight:850}.veil{position:absolute;left:0;top:220px;width:1080px;height:1130px;background:#000;opacity:.982;z-index:8;pointer-events:none;animation:reveal 3s linear forwards}@keyframes reveal{from{opacity:.982}to{opacity:0}}
'''
page=f'''<!doctype html><html><head><meta charset="utf-8"><title>10 AI Business Models</title><style>{font_css()}\n{css}</style></head><body><main id="film"><header class="header"><h1>10 AI BUSINESS MODELS</h1><p>(that make real mony in 2026)</p></header><section class="body"><aside class="process"><div class="eyebrow">THE OPERATING LOOP</div>{step_html}</aside><section class="system"><h2>10 REPEATABLE AI BUSINESS MODELS</h2><div class="orbit"></div>{model_html}<div class="laptop"><div class="screen">AI<i>✦</i></div></div><div class="base"></div></section></section><footer class="footer">↓ Comment <em>REAL</em> for the full breackdown</footer><div class="veil"></div></main></body></html>'''
OUT.write_text(page)
print(f'generated {OUT}: native body, centered header, no imported image')
