#!/usr/bin/env python3
import importlib.util, pathlib, html
REPO=pathlib.Path('/work'); OUT=REPO/'content/ultron-ai-business-models.html'
def fonts():
 s=importlib.util.spec_from_file_location('_fonts',REPO/'content/_fonts.py'); m=importlib.util.module_from_spec(s); s.loader.exec_module(m); return m.embedded_css()
steps=[('⌕','AI researches the market'),('◌','AI builds the first version'),('●','You make the key decisions'),('↗','The system keeps generating revenue')]
models=['1. BORING TOOL EMPIRE','2. LOCAL DIRECTORY FACTORY','3. TOO EXPENSIVE SAAS HUNTER','4. DIGITAL PRODUCT FACTORY','5. AFFILIATE SEO EMPIRE','6. AI WORKFLOW FACTORY','7. HYPERSCALABLE GAME FACTORY','8. COLD EMAIL LEAD MACHINE','9. DATA PRODUCT FACTORY','10. STARTUP OPPORTUNITY FINDER']
step_html=''.join(f'<div class="step"><div class="step-icon">{a}</div><div class="step-text">{html.escape(b)}</div></div>'+('<div class="arrow">↓</div>' if i<3 else '') for i,(a,b) in enumerate(steps))
model_html=''.join(f'<div class="model m{i}"><span class="model-icon">{["⚒","⌖","$","□","↗","⚙","◉","✉","▤","🚀"][i]}</span><span>{html.escape(x)}</span></div>' for i,x in enumerate(models))
css=fonts()+'''
/* FILM-META {{"duration":7.0,"w":1080,"h":1350,"fps":30,"beats":[{{"from":0,"to":3,"name":"reveal"}}]}} */
:root{{--ink:#17233d;--purple:#7356c8;--green:#4ca878;--cream:#faf8f1;--muted:#647084}}
*{{box-sizing:border-box;margin:0;padding:0}}body{{background:#000;font-family:'DM Sans',Arial,sans-serif;color:var(--ink)}}#film{{position:relative;width:1080px;height:1350px;background:var(--cream);overflow:hidden}}
.header{{height:255px;padding:0 62px;text-align:center;background:#111;color:#fff;display:flex;align-items:center;justify-content:center}}.headline{{font-size:65px;font-weight:850;letter-spacing:-2.8px;line-height:1.02;color:#fff}}.headline .ten{{color:#fff}}.headline .money{{display:inline;color:#fff;padding:0;margin-left:8px;border-radius:0;font-weight:400;font-size:.52em;letter-spacing:-.4px}}.subhead{{display:none}}.subhead .build{{display:none}}.subhead .generate{{display:none}}
.content{{position:absolute;top:255px;left:0;width:1080px;height:1015px;padding:0 58px;display:grid;grid-template-columns:390px 1fr;column-gap:34px}}.process{{padding-top:54px;border-right:1px solid #b7b8b6;padding-right:28px}}.step{{display:flex;align-items:center;gap:20px;min-height:115px}}.step-icon{{width:68px;height:68px;border-radius:50%;background:#eee8fb;color:var(--purple);display:grid;place-items:center;font-size:31px;font-weight:750;flex:none}}.step:last-of-type .step-icon{{background:#e3f4e8;color:var(--green)}}.step-text{{font-size:24px;line-height:1.12;font-weight:720}}.arrow{{height:30px;display:flex;align-items:center;justify-content:center;font-size:28px;color:#202735;margin-left:-208px}}
.diagram{{position:relative;height:850px;margin-top:4px}}.orbit{{position:absolute;left:76px;top:48px;width:515px;height:515px;border:2px dashed #9fa4ab;border-radius:50%}}.laptop{{position:absolute;left:218px;top:230px;width:235px;height:150px;background:#9aa2ad;border:4px solid #394453;border-radius:11px 11px 5px 5px;z-index:2;box-shadow:0 10px 0 -5px #697381}}.screen{{position:absolute;inset:15px;background:#202b3c;border-radius:4px;display:grid;place-items:center;color:var(--purple);font-size:58px;font-weight:800}}.spark{{position:absolute;right:30px;top:25px;color:#fff;font-size:22px}}.base{{position:absolute;left:190px;top:382px;width:290px;height:22px;background:#7d8793;border:3px solid #394453;border-radius:4px 4px 14px 14px;z-index:2}}.model{{position:absolute;width:176px;display:flex;align-items:center;gap:8px;font-size:15px;font-weight:750;line-height:1.08;color:#25334b}.model-icon{{width:32px;height:32px;display:grid;place-items:center;flex:none;border:2px solid var(--purple);border-radius:8px;background:#f4f0ff;color:var(--purple);font-size:18px}}.m0{{left:240px;top:4px}}.m1{{left:438px;top:75px}}.m2{{left:478px;top:203px}}.m3{{left:432px;top:355px}}.m4{{left:292px;top:495px}}.m5{{left:38px;top:495px}}.m6{{left:-20px;top:355px}}.m7{{left:-26px;top:203px}}.m8{{left:35px;top:75px}}.m9{{left:240px;top:610px}}.footer{{position:absolute;left:0;top:1190px;height:160px;width:1080px;display:flex;align-items:center;justify-content:center;background:var(--cream);font-size:31px;font-weight:800}}.footer em{{font-style:normal;color:var(--purple)}}.veil{{position:absolute;top:255px;left:0;width:1080px;height:1095px;background:#000;opacity:.982;z-index:8;pointer-events:none;animation:reveal 3s linear forwards}}@keyframes reveal{{from{{opacity:.982}}to{{opacity:0}}}}
'''.replace('{{','{').replace('}}','}')
out=f'''<!doctype html><html><head><meta charset="utf-8"><title>10 AI BUSINESS MODELS</title><style>{css}</style></head><body><main id="film"><header class="header"><div class="headline"><span class="ten">10 AI BUSINESS</span><br>MODELS <span class="money">(that make real mony in 2026)</span></div></header><section class="content"><div class="process">{step_html}</div><div class="diagram"><div class="orbit"></div>{model_html}<div class="laptop"><div class="screen">AI<span class="spark">✦</span></div></div><div class="base"></div></div></section><footer class="footer">↓ Comment <em>REAL for the full breackdown</em></footer><div class="veil"></div></main></body></html>'''
OUT.write_text(out); print(f'generated {OUT}; native body; footer=Comment REAL')
