#!/usr/bin/env python3
import importlib.util, pathlib, html
ROOT=pathlib.Path('/work'); OUT=ROOT/'content/ultron-ai-business-models-v2.html'
def font_css():
 spec=importlib.util.spec_from_file_location('_fonts',ROOT/'content/_fonts.py'); mod=importlib.util.module_from_spec(spec); spec.loader.exec_module(mod); return mod.embedded_css()
models=[
 ('⚒','Boring tool empire','Build one narrow utility for a painful workflow.'),('⌖','Local directory factory','Package useful local data into searchable listings.'),('$','Too-expensive SaaS hunter','Replace bloated software with a focused alternative.'),('□','Digital product factory','Turn expertise into repeatable templates and tools.'),('↗','Affiliate SEO empire','Publish useful pages with purchase intent built in.'),('⚙','AI workflow factory','Automate a repeatable operation for a specific niche.'),('◉','Game factory','Ship small, replayable products for defined audiences.'),('✉','Cold email lead machine','Find, qualify and route prospects into a clear offer.'),('▤','Data product factory','Make difficult data simple enough to buy and use.'),('🚀','Startup opportunity finder','Spot recurring pain before it becomes an obvious market.')]
cards=''.join(f'<article class="card"><b class="num">{n:02d}</b><h3>{html.escape(title)}</h3><p>{html.escape(desc)}</p></article>' for n,(_,title,desc) in enumerate(models,1))
css='''
/* FILM-META {"duration":7.0,"w":1080,"h":1350,"fps":30,"beats":[{"from":0,"to":3,"name":"reveal"}]} */
:root{--ink:#17233d;--accent:#e0642d;--cream:#fbf9f2;--rule:#dedbd3;--muted:#657083}*{box-sizing:border-box;margin:0;padding:0}body{background:#000;font-family:'DM Sans',Arial,sans-serif;color:var(--ink)}#film{position:relative;width:1080px;height:1350px;overflow:hidden;background:var(--cream)}
.header{position:absolute;top:0;left:0;width:1080px;height:187px;background:#111;color:#fff;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;z-index:3}.header h1{font-size:64px;line-height:1;font-weight:850;letter-spacing:-2.4px}.header p{font-size:40px;line-height:1.1;font-weight:450;margin-top:18px;letter-spacing:-.8px}
.body{position:absolute;top:187px;left:0;width:1080px;height:1003px;background:var(--cream);padding:34px 55px 28px}.intro{height:72px;display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid var(--rule);padding-bottom:20px}.intro h2{font-size:22px;letter-spacing:1.8px;color:var(--accent);font-weight:850}.intro p{font-size:18px;font-weight:600;color:var(--muted)}.grid{margin-top:24px;display:grid;grid-template-columns:repeat(2,1fr);grid-auto-rows:154px;gap:16px}.card{position:relative;border:1px solid var(--rule);border-radius:16px;background:#fffdf8;padding:20px 22px;display:flex;flex-direction:column;justify-content:center}.card{border-top:4px solid var(--accent)}.num{position:absolute;top:16px;right:21px;font-size:30px;font-weight:850;line-height:1;color:var(--accent);letter-spacing:-1px}.card h3{font-size:25px;line-height:1.03;text-transform:uppercase;letter-spacing:-.7px;margin:0;padding-right:62px;max-width:360px}.card p{font-size:16px;line-height:1.22;color:var(--muted);margin:10px 0 0;max-width:390px}.footer{position:absolute;top:1190px;left:0;width:1080px;height:160px;display:flex;align-items:center;justify-content:center;gap:12px;background:var(--cream);font-size:31px;font-weight:700;color:var(--ink);z-index:3}.footer em{color:var(--accent);font-style:normal;font-weight:850}.veil{position:absolute;left:0;top:187px;width:1080px;height:1163px;background:#000;opacity:.982;z-index:8;pointer-events:none;animation:reveal 3s linear forwards}@keyframes reveal{from{opacity:.982}to{opacity:0}}
'''
page=f'''<!doctype html><html><head><meta charset="utf-8"><title>10 AI Business Models</title><style>{font_css()}\n{css}</style></head><body><main id="film"><header class="header"><h1>10 AI BUSINESS MODELS</h1><p>(that make real money in 2026)</p></header><section class="body"><div class="intro"><h2>10 REPEATABLE AI BUSINESS MODELS</h2><p>Pick one problem. Build the system around it.</p></div><div class="grid">{cards}</div></section><footer class="footer"><span>↓ Comment</span><em>REAL</em><span>for the full breakdown</span></footer><div class="veil"></div></main></body></html>'''
OUT.write_text(page); print(f'generated {OUT}: native two-column card grid, no circular body')
